Prod-EU/force-app/main/default/objects/Account/fields/Account_18_Digit_Id__c.field-meta.xml
<CustomField>
    <fullName>Account_18_Digit_Id__c</fullName>
    <description>This will convert the 15 digit id to 18 digit id</description>
    <formula>CASESAFEID(Id)</formula>
    <label>Account 18 Digit Id</label>
    <type>Text</type>
</CustomField>

Prod-EU/force-app/main/default/objects/Account/fields/Fund__c.field-meta.xml
<CustomField>
    <fullName>Fund__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Fund the customer is associated to</description>
    <label>Fund</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 OR 3) AND 2</booleanFilter>
        <filterItems>
            <field>$Source.Payor__c</field>
            <operation>equals</operation>
            <valueField>Fund__c.Payor__c</valueField>
        </filterItems>
        <filterItems>
            <field>Fund__c.Is_Fund_Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>$Source.Id</field>
            <operation>equals</operation>
            <valueField>Fund__c.Payor__c</valueField>
        </filterItems>
        <infoMessage>Fund is not active.</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Fund__c</referenceTo>
    <relationshipLabel>Consumers</relationshipLabel>
    <relationshipName>Funds</relationshipName>
    <type>Lookup</type>
</CustomField>

Prod-EU/force-app/main/default/objects/Account/fields/Price_Book__c.field-meta.xml
<CustomField>
    <fullName>Price_Book__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Price Book</label>
    <referenceTo>Pricebook2</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

Prod-EU/force-app/main/default/objects/Fund__c/Fund__c.object-meta.xml
<CustomObject>
    <description>Object will track information related to Funded Patients.</description>
    <label>Fund</label>
    <nameField>
        <displayFormat>F-{00000}</displayFormat>
        <label>Fund Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fund</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Prod-EU/force-app/main/default/objects/Fund__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <defaultValue>If(OR(BEGINS($Profile.Name , &apos;UK&apos;), BEGINS($Profile.Name , &apos;System&apos;)), &apos;United Kingdom&apos;, &apos;&apos;)</defaultValue>
    <description>Possible countries that can be selected defaulted based on the Profile</description>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country</valueSetName>
    </valueSet>
</CustomField>

Prod-EU/force-app/main/default/objects/Marketing_Interaction__c/Marketing_Interaction__c.object-meta.xml
<CustomObject>
    <description>Object used to trigger journeys in Marketing Cloud.</description>
    <label>Marketing Interaction</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Marketing Interaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Marketing Interactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Prod-EU/force-app/main/default/objects/Marketing_Interaction__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Marketing Interactions</relationshipLabel>
    <relationshipName>Marketing_Interactions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

Prod-EU/force-app/main/default/objects/Marketing_Interaction__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <description>Country should always be required for all records entered in this object.</description>
    <label>Country</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country</valueSetName>
    </valueSet>
</CustomField>

Prod-EU/force-app/main/default/objects/SSIP_Rule__c/SSIP_Rule__c.object-meta.xml
<CustomObject>
    <description>Object stores all SSIP rule for the customers.</description>
    <label>SSIP Rule</label>
    <nameField>
        <displayFormat>SP-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SSIP Rule</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Prod-EU/force-app/main/default/objects/SSIP_Rule__c/fields/Account_18_Digit_Id__c.field-meta.xml
<CustomField>
    <fullName>Account_18_Digit_Id__c</fullName>
    <description>Records 18 digit Id. Mainly used for Duplicate Rule logic.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Account 18 Digit Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

Prod-EU/force-app/main/default/objects/SSIP_Rule__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Master detail relationship to the account.</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>SSIP Rule</relationshipLabel>
    <relationshipName>SSIP_Rule</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Prod-EU/force-app/main/default/objects/SSIP_Rule__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <description>Country to which this rule is tied to</description>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country</valueSetName>
    </valueSet>
</CustomField>

Prod-EU/force-app/main/default/objects/SSIP_Rule__c/fields/First_Order__c.field-meta.xml
<CustomField>
    <fullName>First_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>First Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>SSIP Rule</relationshipLabel>
    <relationshipName>SSIP_Rule</relationshipName>
    <type>Lookup</type>
</CustomField>

Prod-EU/force-app/main/default/objects/SSIP_Rule__c/fields/First_Repeat_Order_Lead_Days__c.field-meta.xml
<CustomField>
    <fullName>First_Repeat_Order_Lead_Days__c</fullName>
    <inlineHelpText>Lead days for the first shipment</inlineHelpText>
    <label>First Repeat Order Lead Days</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Prod-EU/force-app/main/default/objects/SSIP_Rule__c/fields/First_Shipment_Date__c.field-meta.xml
<CustomField>
    <fullName>First_Shipment_Date__c</fullName>
    <description>Date when the first shipment needs to happen for this Schedule. It cam be immediate or in the future and should fall between the Rule Start and End date.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Date should be within the Rule Start Date and Rule End Date (if applicable). This date is set with the first order is shipped. Setting this date will create the Schedules.</inlineHelpText>
    <label>First Shipment Date</label>
    <type>Date</type>
</CustomField>

Prod-EU/force-app/main/default/objects/SSIP_Rule__c/fields/Frequency_In_Days__c.field-meta.xml
<CustomField>
    <fullName>Frequency_In_Days__c</fullName>
    <description>Schedule interval between each shipments.</description>
    <label>Frequency (In Days)</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Prod-EU/force-app/main/default/objects/SSIP_Rule__c/fields/Payment_Term__c.field-meta.xml
<CustomField>
    <fullName>Payment_Term__c</fullName>
    <defaultValue>IF( $RecordType.DeveloperName = &apos;CH_SSIP_Rule&apos;, &apos;net30&apos;, &apos;net30&apos;)</defaultValue>
    <description>Payment terms that will be used to track the payment. The default value will be based on the country&apos; preference</description>
    <label>Payment Term</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Payment_Term</valueSetName>
    </valueSet>
</CustomField>

Prod-EU/force-app/main/default/objects/SSIP_Rule__c/fields/Price_Book__c.field-meta.xml
<CustomField>
    <fullName>Price_Book__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Price book, which will filter out only SSIP Pricebooks</description>
    <label>Price Book</label>
    <referenceTo>Pricebook2</referenceTo>
    <relationshipLabel>SSIP Rule</relationshipLabel>
    <relationshipName>SSIP_Rule</relationshipName>
    <type>Lookup</type>
</CustomField>

Prod-EU/force-app/main/default/objects/SSIP_Rule__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>SSIP Rule</relationshipLabel>
    <relationshipName>SSIP_Rule</relationshipName>
    <type>Lookup</type>
</CustomField>

Prod-EU/force-app/main/default/objects/SSIP_Rule__c/fields/Product_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Product Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Prod-EU/force-app/main/default/objects/SSIP_Rule__c/fields/Rule_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Rule_End_Date__c</fullName>
    <description>Date when the rule will end.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Date should be greater than or equal to today&apos;s date. Setting this date will delete any open schedules past this date.</inlineHelpText>
    <label>Rule End Date</label>
    <type>Date</type>
</CustomField>

Prod-EU/force-app/main/default/objects/SSIP_Rule__c/fields/Schedule_Count__c.field-meta.xml
<CustomField>
    <fullName>Schedule_Count__c</fullName>
    <description>Field holds the number of Schedules that can be created for this rule.</description>
    <inlineHelpText>Count determines how many schedules will be created at first for this Rule.</inlineHelpText>
    <label>Schedule Count</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Prod-EU/force-app/main/default/objects/SSIP_Rule__c/fields/Shipping_Address__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Address__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>List of all Ship To addresses tied to the customer.</description>
    <label>Shipping Address</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Address__c.Account__c</field>
            <operation>equals</operation>
            <valueField>$Source.Account__c</valueField>
        </filterItems>
        <filterItems>
            <field>Address__c.Type__c</field>
            <operation>equals</operation>
            <value>Ship To</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Address__c</referenceTo>
    <relationshipLabel>SSIP Rule</relationshipLabel>
    <relationshipName>SSIP_Rule</relationshipName>
    <type>Lookup</type>
</CustomField>

Prod-EU/force-app/main/default/objects/SSIP_Schedule__c/SSIP_Schedule__c.object-meta.xml
<CustomObject>
    <description>Object stores all the schedules related to the rule.</description>
    <label>SSIP Schedule</label>
    <nameField>
        <displayFormat>SP-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SSIP Schedule</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Prod-EU/force-app/main/default/objects/SSIP_Schedule__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Will be referencing the grand parent and will be defaulted at the time of the Schedule creation. Need this for constraining the addressed tied to the customer.</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>SSIP Schedule</relationshipLabel>
    <relationshipName>SSIP_Schedule</relationshipName>
    <type>Lookup</type>
</CustomField>

Prod-EU/force-app/main/default/objects/SSIP_Schedule__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <description>Will be defaulted from SSIP Rule at the time of creation.</description>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country</valueSetName>
    </valueSet>
</CustomField>

Prod-EU/force-app/main/default/objects/SSIP_Schedule__c/fields/First_Shipment_Date__c.field-meta.xml
<CustomField>
    <fullName>First_Shipment_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Scheduled Shipment Date</label>
    <type>Date</type>
</CustomField>

Prod-EU/force-app/main/default/objects/SSIP_Schedule__c/fields/Fund__c.field-meta.xml
<CustomField>
    <fullName>Fund__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Fund</label>
    <referenceTo>Fund__c</referenceTo>
    <relationshipLabel>SSIP Schedule</relationshipLabel>
    <relationshipName>SSIP_Schedule</relationshipName>
    <type>Lookup</type>
</CustomField>

Prod-EU/force-app/main/default/objects/SSIP_Schedule__c/fields/Payment_Term__c.field-meta.xml
<CustomField>
    <fullName>Payment_Term__c</fullName>
    <description>Will be defaulted from Parent SSIP Rule</description>
    <inlineHelpText>Value can be overridden only for this schedule.</inlineHelpText>
    <label>Payment Term</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Payment_Term</valueSetName>
    </valueSet>
</CustomField>

Prod-EU/force-app/main/default/objects/SSIP_Schedule__c/fields/Price_Book__c.field-meta.xml
<CustomField>
    <fullName>Price_Book__c</fullName>
    <formula>IF(  NOT(ISBLANK(Order__c))  , 
 HYPERLINK(&quot;/&quot;+     Order__r.Pricebook2.Id, Order__r.Pricebook2.Name, &quot;_blank&quot;), 
 HYPERLINK(&quot;/&quot;+SSIP_Rule__r.Price_Book__c, SSIP_Rule__r.Price_Book__r.Name, &quot;_blank&quot;)   )</formula>
    <label>Price Book</label>
    <type>Text</type>
</CustomField>

Prod-EU/force-app/main/default/objects/SSIP_Schedule__c/fields/Product_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Name__c</fullName>
    <formula>SSIP_Rule__r.Product__r.Name</formula>
    <inlineHelpText>Product Name tied to the Rule.</inlineHelpText>
    <label>Product Name</label>
    <type>Text</type>
</CustomField>

Prod-EU/force-app/main/default/objects/SSIP_Schedule__c/fields/SSIP_Rule__c.field-meta.xml
<CustomField>
    <fullName>SSIP_Rule__c</fullName>
    <description>Master Detail relationship to the parent Rule.</description>
    <label>SSIP Rule</label>
    <referenceTo>SSIP_Rule__c</referenceTo>
    <relationshipLabel>SSIP Schedule</relationshipLabel>
    <relationshipName>SSIP_Schedule</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Prod-EU/force-app/main/default/classes/SSIPRuleTriggerHandler.cls
/**********************************************************************
@Description    : Class will handle logic for SSIPRule object
***********************************************************************/
public class SSIPRuleTriggerHandler {
    
    
    public void onBeforeInsert(List<SSIP_Rule__c> lstSSIPRuleNew){
        //Collection variables
        Set<Id> productIds = new Set<Id>();
        Set<Id> PBIds = new set<Id>();
        Map<Id, String> productNameMap = new Map<Id, String>();
        List<PricebookEntry> PBEItemList = new List<PricebookEntry>();
        //Prepares the product map for the rules that need to be updated with Product Name
        for(SSIP_Rule__c objSSIPRule : lstSSIPRuleNew){
            if(objSSIPRule.Product__c != null && objSSIPRule.Product_Name__c == null) productIds.add(objSSIPRule.Product__c);
            
            PBIds.add(objSSIPRule.Price_Book__c); 
        }
        if(!productIds.isEmpty()){
            for(Product2 prod : [SELECT Id, Name FROM Product2 WHERE Id IN : productIds])
                productNameMap.put(prod.Id, prod.Name);
        }
        for(PricebookEntry pbe : [select id, Name, UnitPrice, Pricebook2Id, Product2Id from PricebookEntry where Pricebook2Id IN :PBIds] )   PBEItemList.add(pbe); 
        
        system.debug('PBEItemList'+PBEItemList);
        //For every rule update the 18 digit account id and Product name based on the chosen product
        for(SSIP_Rule__c objSSIPRule : lstSSIPRuleNew)
        {
            objSSIPRule.Account_18_Digit_Id__c = objSSIPRule.Account__c;
            Boolean Prodfound = false;
            for(PricebookEntry PBE :PBEItemList){  
                if(PBE.Pricebook2Id == objSSIPRule.Price_Book__c && PBE.Product2Id == objSSIPRule.Product__c){                    
                    Prodfound = True ;
                    objSSIPRule.Unit_Price__c = PBE.UnitPrice;
                    
                }
            }
            if(!Prodfound){
                objSSIPRule.addError('Wrong combination of Product and Pricbook.');
                return;
            }  
            if(!productNameMap.isEmpty() && objSSIPRule.Product__c != null && objSSIPRule.Product_Name__c == null && productNameMap.containsKey(objSSIPRule.Product__c))
                objSSIPRule.Product_Name__c = productNameMap.get(objSSIPRule.Product__c);
        }
    }
    
    public void onAfterInsert(List<SSIP_Rule__c> lstSSIPRuleNew){
        createSSIPScheduleRecord(lstSSIPRuleNew, new Map<Id,SSIP_Rule__c>());
    }
    
    public void onAfterUpdate(List<SSIP_Rule__c> lstSSIPRuleNew, Map<Id, SSIP_Rule__c> mapSSIPRuleOld){
        //NS-1619 - CA- Subscription Renewal Journeys for Perficient - Part -I
        List<SSIP_Rule__c> ssipRenewed = new List<SSIP_Rule__c>();
        List<SSIP_Rule__c> lstSSIP = [Select id,Name,Rule_End_Date__c,Account__r.Id,Account__r.RecordType.DeveloperName,
                                      Account__r.RecordType.Name,Price_Book__r.Name,Product_Name__c
                                      from SSIP_Rule__c where id IN:lstSSIPRuleNew];
        for(SSIP_Rule__c ssipRl : lstSSIP){
            String accRecName =  ssipRl.Account__r.RecordType.Name;
            String PBName = ssipRl.Price_Book__r.Name;
            String PrdName = ssipRl.Product_Name__c; 
            if((ssipRl.Rule_End_Date__c != null && ssipRl.Rule_End_Date__c != mapSSIPRuleOld.get(ssipRl.Id).Rule_End_Date__c) && (accRecName.containsIgnoreCase('CA Consumer')) 
               && (PBName.containsIgnoreCase('CAN G6 SUBSCRIPTION 12MOS NO Renewal')) || (PBName.containsIgnoreCase('CAN G6 SUBSCRIPTION 12MOS Auto Renewal')) 
               && (PrdName.containsIgnoreCase('MTRNTCAGS-12MOS'))){
                   ssipRenewed.add(ssipRl);
               }    
        }       
        
        createSSIPScheduleRecord(lstSSIPRuleNew, mapSSIPRuleOld); 
        ClsSSIPRuleRenewal.handleSSIPRuleRenwal(lstSSIPRuleNew, mapSSIPRuleOld); 
        if(ssipRenewed.size()>0){
            onUpdatecreateMIRecords(ssipRenewed);
        }
    }
    
    
    private void createSSIPScheduleRecord(List<SSIP_Rule__c> lstSSIPRuleNew, Map<Id, SSIP_Rule__c> mapSSIPRuleOld){
        Map<Id, SSIP_Rule__c> mapSSIPRuleNew = new Map<Id, SSIP_Rule__c>(lstSSIPRuleNew);
        Map<Id, Id> ruleToFundMap = new Map<Id, Id>();      
        Map<Id, List<SSIP_Schedule__c>> mapSSIPIdTolstSSIPSchedule = new Map<Id, List<SSIP_Schedule__c>>();
        List<SSIP_Schedule__c> lstSSIPSchedule = new List<SSIP_Schedule__c>();
        Set<SSIP_Schedule__c>  lstSSIPSet  = new Set<SSIP_Schedule__c>();        
        List<SSIP_Schedule__c> lstSSIPScheduleToDelete = new List<SSIP_Schedule__c>();
        Set<Id> setSSIPRuleId = new Set<Id>();
        
        
        //Find if the Rule has order association and prepare the map
        for(SSIP_Rule__c objSSIPRule : [SELECT Id, First_Order__r.Fund__c FROM SSIP_Rule__c WHERE First_Order__c != null AND Id IN: lstSSIPRuleNew]){
            if(objSSIPRule.First_Order__r.Fund__c != null)
                ruleToFundMap.put(objSSIPRule.Id, objSSIPRule.First_Order__r.Fund__c);
        }        
        
        //Process the SSIP Rule records to create Schedules
        for(SSIP_Rule__c objSSIPRule : lstSSIPRuleNew){
            System.debug('createSSIPScheduleRecord for loop');                
            
            Integer count = objSSIPRule.Schedule_Count__c != null ? Integer.valueOf(objSSIPRule.Schedule_Count__c) : 3;
            Integer firstRepeatOrderLeadDays = objSSIPRule.First_Repeat_Order_Lead_Days__c != null ? Integer.valueOf(objSSIPRule.First_Repeat_Order_Lead_Days__c) : 0;
            if((Trigger.isInsert && objSSIPRule.First_Shipment_Date__c != null) || (Trigger.isUpdate && mapSSIPRuleOld.get(objSSIPRule.Id).First_Shipment_Date__c == null && objSSIPRule.First_Shipment_Date__c != null) && objSSIPRule.Frequency_In_Days__c != null){
                // Code Added by Pravin  - NS-1357
                String Prdname = objSSIPRule.Product_Name__c;
                System.debug('**Country--'+objSSIPRule.Country__c);
                if(objSSIPRule.Country__c == 'Canada' && prdName.startsWith('MT')){
                    Integer dayofMonth = objSSIPRule.First_Shipment_Date__c.Day();
                    if(dayofMonth <= 28){
                        for(Integer i = 1; i <= count; i++){
                            lstSSIPSchedule.add(new SSIP_Schedule__c(Account__c = objSSIPRule.Account__c, Country__c = objSSIPRule.Country__c, Payment_Term__c = objSSIPRule.Payment_Term__c, Shipping_Address__c = objSSIPRule.Shipping_Address__c,
                                                                     Shipping_Method__c = objSSIPRule.Shipping_Method__c, SSIP_Rule__c = objSSIPRule.Id, Status__c = 'Open',
                                                                     Fund__c = !ruleToFundMap.isEmpty() ? ruleToFundMap.get(objSSIPRule.Id) : null,     
                                                                     Schedule_Date__c = objSSIPRule.First_Shipment_Date__c.addMonths(1 * i) - firstRepeatOrderLeadDays));
                        }
                    }else if(dayofMonth > 28){
                        date myDate = objSSIPRule.First_Shipment_Date__c; 
                        date newDate = myDate.addMonths(1);
                        date expectedDate = newDate.toStartOfMonth();
                        for(Integer i = 1; i <= count; i++){
                            lstSSIPSchedule.add(new SSIP_Schedule__c(Account__c = objSSIPRule.Account__c, Country__c = objSSIPRule.Country__c, Payment_Term__c = objSSIPRule.Payment_Term__c, Shipping_Address__c = objSSIPRule.Shipping_Address__c,
                                                                     Shipping_Method__c = objSSIPRule.Shipping_Method__c, SSIP_Rule__c = objSSIPRule.Id, Status__c = 'Open',
                                                                     Fund__c = !ruleToFundMap.isEmpty() ? ruleToFundMap.get(objSSIPRule.Id) : null,     
                                                                     Schedule_Date__c = expectedDate.addMonths(1 * i) - firstRepeatOrderLeadDays));
                        }
                    }
                }else{
                    
                    for(Integer i = 1; i <= count; i++){
                        lstSSIPSchedule.add(new SSIP_Schedule__c(Account__c = objSSIPRule.Account__c, Country__c = objSSIPRule.Country__c, Payment_Term__c = objSSIPRule.Payment_Term__c, Shipping_Address__c = objSSIPRule.Shipping_Address__c,
                                                                 Shipping_Method__c = objSSIPRule.Shipping_Method__c, SSIP_Rule__c = objSSIPRule.Id, Status__c = 'Open',
                                                                 Fund__c = !ruleToFundMap.isEmpty() ? ruleToFundMap.get(objSSIPRule.Id) : null,     
                                                                 Schedule_Date__c = objSSIPRule.First_Shipment_Date__c.addDays(Integer.valueOf(objSSIPRule.Frequency_In_Days__c) * i) - firstRepeatOrderLeadDays));
                    }
                }
                
                
            }                        
            if(Trigger.isUpdate && ((mapSSIPRuleOld.get(objSSIPRule.Id).First_Shipment_Date__c != null && objSSIPRule.Rule_End_Date__c != mapSSIPRuleOld.get(objSSIPRule.Id).Rule_End_Date__c) 
                                    || mapSSIPRuleOld.get(objSSIPRule.Id).Payment_Term__c != objSSIPRule.Payment_Term__c || mapSSIPRuleOld.get(objSSIPRule.Id).Shipping_Method__c != objSSIPRule.Shipping_Method__c
                                    /*|| (objSSIPRule.Rule_Re_schedule_Date__c != null && mapSSIPRuleOld.get(objSSIPRule.Id).Rule_Re_schedule_Date__c != objSSIPRule.Rule_Re_schedule_Date__c ) */)){
                                        
                                        system.debug('objSSIPRule.Id = '+ objSSIPRule.Id);
                                        setSSIPRuleId.add(objSSIPRule.Id);
                                    }
            if(Trigger.isUpdate && (objSSIPRule.Rule_Re_schedule_Date__c != null && mapSSIPRuleOld.get(objSSIPRule.Id).Rule_Re_schedule_Date__c != objSSIPRule.Rule_Re_schedule_Date__c ))
                handleScheduleChange(objSSIPRule);
        }
        //Set Payment Term, Shipping Method from the Rule to the schedule records. Also delete all schedules once the Rule End Date is set on the Rule
        for(SSIP_Schedule__c objSSIPSchedule : [SELECT Id, SSIP_Rule__c, SSIP_Rule__r.Rule_End_Date__c, Rescheduled_Shipment_Date__c, Schedule_Date__c FROM SSIP_Schedule__c WHERE SSIP_Rule__c IN: setSSIPRuleId AND Status__c = 'Open']){
            System.debug('createSSIPScheduleRecord for loop 2');                
            
            //Process deletion logic first and then go to update logic
            //If the Reschedued Shipment Date is populated on the SSIP Schedule that takes the precedence
            if(objSSIPSchedule.Rescheduled_Shipment_Date__c != null && (objSSIPSchedule.Rescheduled_Shipment_Date__c > objSSIPSchedule.SSIP_Rule__r.Rule_End_Date__c))
                lstSSIPScheduleToDelete.add(objSSIPSchedule);
            else
                if(objSSIPSchedule.Rescheduled_Shipment_Date__c == null && (objSSIPSchedule.Schedule_Date__c > objSSIPSchedule.SSIP_Rule__r.Rule_End_Date__c))
                lstSSIPScheduleToDelete.add(objSSIPSchedule);
            else{
                if(mapSSIPRuleNew.get(objSSIPSchedule.SSIP_Rule__c).Payment_Term__c != mapSSIPRuleOld.get(objSSIPSchedule.SSIP_Rule__c).Payment_Term__c){
                    objSSIPSchedule.Payment_Term__c = mapSSIPRuleNew.get(objSSIPSchedule.SSIP_Rule__c).Payment_Term__c;
                }
                if(mapSSIPRuleNew.get(objSSIPSchedule.SSIP_Rule__c).Shipping_Method__c != mapSSIPRuleOld.get(objSSIPSchedule.SSIP_Rule__c).Shipping_Method__c){
                    objSSIPSchedule.Shipping_Method__c = mapSSIPRuleNew.get(objSSIPSchedule.SSIP_Rule__c).Shipping_Method__c;
                }    
                
                lstSSIPSchedule.add(objSSIPSchedule);
            }
        }
        delete lstSSIPScheduleToDelete;
        upsert lstSSIPSchedule;
        
    }
    
    public Static void handleScheduleChange(SSIP_Rule__c objSSIPRule) {
        List<SSIP_Schedule__c> scheds = [Select Id, Schedule_Date__c from SSIP_Schedule__c where SSIP_Rule__c = :objSSIPRule.id and Status__c = 'OPEN'];
        Integer count = objSSIPRule.Schedule_Count__c != null ? Integer.valueOf(objSSIPRule.Schedule_Count__c) : 3;
        Integer firstRepeatOrderLeadDays = objSSIPRule.First_Repeat_Order_Lead_Days__c != null ? Integer.valueOf(objSSIPRule.First_Repeat_Order_Lead_Days__c) : 0;
        List<SSIP_Schedule__c> lstSSIPSchedule = new List<SSIP_Schedule__c>();
        integer schedCounter = 0;
        System.debug('**scheds--'+scheds.size());
        for(SSIP_Schedule__c sched : scheds) {
            if (schedCounter == 0 && (objSSIPRule.Rule_End_Date__c == null ||  objSSIPRule.Rule_Re_schedule_Date__c <= objSSIPRule.Rule_End_Date__c)){ 
                String prdNAme1 = objSSIPRule.Product_Name__c;
                if(objSSIPRule.Country__c =='Canada' && prdNAme1.StartsWith('MT')){
                    Integer dayofMonth = objSSIPRule.Rule_Re_schedule_Date__c.Day();
                    if(dayofMonth<=28){
                        lstSSIPSchedule.add(new SSIP_Schedule__c(id=sched.Id, Schedule_Date__c = objSSIPRule.Rule_Re_schedule_Date__c));
                    }else{
                        date myDate = objSSIPRule.Rule_Re_schedule_Date__c;
                        date newDate = myDate.addMonths(1);
                        date expectedDate = newDate.toStartOfMonth();
                        // lstSSIPSchedule.add(new SSIP_Schedule__c(id=sched.Id, Schedule_Date__c = expectedDate));
                        //  lstSSIPSchedule.add(new SSIP_Schedule__c(id=sched.Id, Schedule_Date__c = expectedDate.adddays((Integer) ((objSSIPRule.Frequency_In_Days__c * schedCounter) - firstRepeatOrderLeadDays))));
                        lstSSIPSchedule.add(new SSIP_Schedule__c(id=sched.Id, Schedule_Date__c = expectedDate.addMonths((Integer) ((1 * schedCounter) - firstRepeatOrderLeadDays))));
                        
                    }
                }else{
                    lstSSIPSchedule.add(new SSIP_Schedule__c(id=sched.Id, Schedule_Date__c = objSSIPRule.Rule_Re_schedule_Date__c));
                }
            }else if (objSSIPRule.Rule_End_Date__c == null  || objSSIPRule.Rule_Re_schedule_Date__c.adddays((Integer) ((objSSIPRule.Frequency_In_Days__c * schedCounter) - firstRepeatOrderLeadDays)) <= objSSIPRule.Rule_End_Date__c) {
                
                String prdNAme2 = objSSIPRule.Product_Name__c;
                if(objSSIPRule.Country__c =='Canada' && prdNAme2.StartsWith('MT')){
                    Integer dayofMonth = objSSIPRule.Rule_Re_schedule_Date__c.Day();
                    if(dayofMonth<=28){
                        //lstSSIPSchedule.add(new SSIP_Schedule__c(id=sched.Id, Schedule_Date__c = objSSIPRule.Rule_Re_schedule_Date__c.adddays((Integer) ((objSSIPRule.Frequency_In_Days__c * schedCounter) - firstRepeatOrderLeadDays))));
                        lstSSIPSchedule.add(new SSIP_Schedule__c(id=sched.Id, Schedule_Date__c = objSSIPRule.Rule_Re_schedule_Date__c.addMonths((1 * schedCounter) - firstRepeatOrderLeadDays)));
                        
                    }else{
                        date myDate = objSSIPRule.Rule_Re_schedule_Date__c;
                        date newDate = myDate.addMonths(1);
                        date expectedDate = newDate.toStartOfMonth();
                        System.debug('***ElseIfexpectedDate---'+expectedDate);
                        lstSSIPSchedule.add(new SSIP_Schedule__c(id=sched.Id, Schedule_Date__c = expectedDate.addMonths((Integer) ((1 * schedCounter) - firstRepeatOrderLeadDays))));
                        //lstSSIPSchedule.add(new SSIP_Schedule__c(id=sched.Id, Schedule_Date__c = objSSIPRule.Rule_Re_schedule_Date__c.adddays((Integer) ((objSSIPRule.Frequency_In_Days__c * schedCounter) - firstRepeatOrderLeadDays))));
                        //System.debug('***After-Calculation-expectedDate---'+expectedDate.adddays((Integer) ((objSSIPRule.Frequency_In_Days__c * schedCounter) - firstRepeatOrderLeadDays)));
                    }
                }else{ 
                    lstSSIPSchedule.add(new SSIP_Schedule__c(id=sched.Id, Schedule_Date__c = objSSIPRule.Rule_Re_schedule_Date__c.adddays((Integer) ((objSSIPRule.Frequency_In_Days__c * schedCounter) - firstRepeatOrderLeadDays))));
                }
            }
            schedCounter++;
        }
        System.debug('**count--'+count);
        System.debug('**schedCounter--'+schedCounter);
        If (count > schedCounter) {
            for(Integer i = schedCounter; i < count; i++){
                if (objSSIPRule.Rule_End_Date__c == null  || objSSIPRule.Rule_Re_schedule_Date__c.adddays((Integer) ((objSSIPRule.Frequency_In_Days__c * i) - firstRepeatOrderLeadDays)) <= objSSIPRule.Rule_End_Date__c){
                    String prdNAme = objSSIPRule.Product_Name__c;
                    if(objSSIPRule.Country__c =='Canada' && prdNAme.StartsWith('MT')){
                        Integer dayofMonth = objSSIPRule.Rule_Re_schedule_Date__c.Day();
                        if(dayofMonth<=28){
                            lstSSIPSchedule.add(new SSIP_Schedule__c(Account__c = objSSIPRule.Account__c, Country__c = objSSIPRule.Country__c, Payment_Term__c = objSSIPRule.Payment_Term__c, Shipping_Address__c = objSSIPRule.Shipping_Address__c,
                                                                     Shipping_Method__c = objSSIPRule.Shipping_Method__c, SSIP_Rule__c = objSSIPRule.Id, Status__c = 'Open',
                                                                     //Fund__c = !ruleToFundMap.isEmpty() ? ruleToFundMap.get(objSSIPRule.Id) : null,   
                                                                     //Schedule_Date__c = objSSIPRule.Rule_Re_schedule_Date__c.addDays(Integer.valueOf(objSSIPRule.Frequency_In_Days__c) * i) - firstRepeatOrderLeadDays));
                                                                     Schedule_Date__c = objSSIPRule.Rule_Re_schedule_Date__c.addMonths((1 * i) - firstRepeatOrderLeadDays)));
                        }else{
                            date myDate = objSSIPRule.Rule_Re_schedule_Date__c;
                            date newDate = myDate.addMonths(1);
                            date expectedDate = newDate.toStartOfMonth();
                            lstSSIPSchedule.add(new SSIP_Schedule__c(Account__c = objSSIPRule.Account__c, Country__c = objSSIPRule.Country__c, Payment_Term__c = objSSIPRule.Payment_Term__c, Shipping_Address__c = objSSIPRule.Shipping_Address__c,
                                                                     Shipping_Method__c = objSSIPRule.Shipping_Method__c, SSIP_Rule__c = objSSIPRule.Id, Status__c = 'Open',
                                                                     //Fund__c = !ruleToFundMap.isEmpty() ? ruleToFundMap.get(objSSIPRule.Id) : null,   
                                                                     Schedule_Date__c = expectedDate.addMonths((1 * i)  - firstRepeatOrderLeadDays)));
                            //Schedule_Date__c = expectedDate.addDays(Integer.valueOf(objSSIPRule.Frequency_In_Days__c) * i) - firstRepeatOrderLeadDays));
                        }
                    }else{
                        lstSSIPSchedule.add(new SSIP_Schedule__c(Account__c = objSSIPRule.Account__c, Country__c = objSSIPRule.Country__c, Payment_Term__c = objSSIPRule.Payment_Term__c, Shipping_Address__c = objSSIPRule.Shipping_Address__c,
                                                                 Shipping_Method__c = objSSIPRule.Shipping_Method__c, SSIP_Rule__c = objSSIPRule.Id, Status__c = 'Open',
                                                                 //Fund__c = !ruleToFundMap.isEmpty() ? ruleToFundMap.get(objSSIPRule.Id) : null,   
                                                                 Schedule_Date__c = objSSIPRule.Rule_Re_schedule_Date__c.addDays(Integer.valueOf(objSSIPRule.Frequency_In_Days__c) * i) - firstRepeatOrderLeadDays));
                    }
                }
            }
        }
        upsert lstSSIPSchedule;
        
    }
    //NS-1546 Check Same Price book configred for all SSIP rule under account 
    public static void pricebookCheck(List<SSIP_Rule__C> newList,Map<id,SSIP_Rule__C> oldMap){
        //Check if different pricebooks are there for same account in newList 
        Map<id,Set<Id>> actSSIPMap=new Map<id,Set<Id>>();
        for(SSIP_Rule__C ssip: newList){
            if(ssip.status__c=='Active'){
                if(!actSSIPMap.containsKey(ssip.account__C)){
                    actSSIPMap.put(ssip.account__C,new Set<id>{ssip.price_book__C});
                }else{
                    Set<id> priceIds=actSSIPMap.get(ssip.account__C);
                    priceIds.add(ssip.price_book__C);
                    actSSIPMap.put(ssip.account__C,priceIds);   
                }
            }
        }
        for(SSIP_Rule__C ssip: newList){
            if(actSSIPMap.containsKey(ssip.account__C) && ssip.status__C== 'Active' && actSSIPMap.get(ssip.account__C).size()>1){            
                ssip.addError('Different pricebooks cannot be used for single customer');
            }    
        }
        
        //Check if Pricebook is already configured in Active SSIP rule
        Map<id,Set<id>> mapActIdToPricebookId=new Map<id,Set<Id>>();
        if(actSSIPMap.keyset().size()>0){
            for(SSIP_Rule__C ssip : [select id,price_book__C,account__C from SSIP_Rule__C where status__C='Active' and account__C IN : actSSIPMap.keyset()]){                  
                if(!mapActIdToPricebookId.containsKey(ssip.account__C)){
                    mapActIdToPricebookId.put(ssip.account__C,new Set<id>{ssip.price_book__C});
                }else{
                    Set<id> priceIds=mapActIdToPricebookId.get(ssip.account__C);
                    priceIds.add(ssip.price_book__C);
                    mapActIdToPricebookId.put(ssip.account__C,priceIds);   
                } 
            }
            
            for(SSIP_Rule__C ssip: newList){
                if(ssip.status__c=='Active' && mapActIdToPricebookId.containsKey(ssip.account__C)){
                    if(mapActIdToPricebookId.get(ssip.account__C).size()>1 ){
                        ssip.addError('Active SSIP Rules cannot be created/updated with different pricebooks, please use same pricebook which is already configured in existing active SSIP Rule');
                    }else if(mapActIdToPricebookId.get(ssip.account__C).size()==1 && (new List<Id>( mapActIdToPricebookId.get(ssip.account__C ))[0]) != ssip.price_book__C){                    
                        ssip.addError('Active SSIP Rules cannot be created/updated with different pricebooks, please use same pricebook which is already configured in existing active SSIP Rule.');
                        
                    }
                }
            }   
            
        }  
        
    }
    
    //NS-1619 - CA- Subscription Renewal Journeys for Perficient
    public static void onUpdatecreateMIRecords(List<SSIP_Rule__c> lstRuleEndDateSSIP){
        List<marketing_interaction__c> newMI = new list<marketing_interaction__c>();
        for(SSIP_Rule__c ssRule :lstRuleEndDateSSIP){
            marketing_interaction__c mi = new marketing_interaction__c();
            mi.Account__c=ssRule.Account__r.Id;
            mi.Communication_Type__c='CA - Subscription Renewal - Updated';
            mi.Source_Record_Id__c=ssRule.id; 
            if(ssRule.Rule_End_Date__c != null){
                mi.Related_Information__c=ssRule.Rule_End_Date__c.format();
            }
            mi.Country__c='Canada';
            newMI.add(mi);
        }
        insert newMI;
        System.debug('--NS-1619--NewMI--'+newMI);
    }
}