Prod-EU/force-app/main/default/objects/Account/fields/Address_Line_2__c.field-meta.xml
<CustomField>
    <fullName>Address_Line_2__c</fullName>
    <description>To Populate Address Line 2 in S-Docs.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Address Line 2 (S-Docs)</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

Prod-EU/force-app/main/default/objects/Account/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <label>Gender</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Gender</valueSetName>
    </valueSet>
</CustomField>

Prod-EU/force-app/main/default/objects/Account/fields/OK_Status__c.field-meta.xml
<CustomField>
    <fullName>OK_Status__c</fullName>
    <description>OneKey - Picklist Code = STA</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Provisional</fullName>
            </value>
            <value>
                <fullName>Valid</fullName>
            </value>
            <value>
                <fullName>Invalid</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Prod-EU/force-app/main/default/objects/Account/fields/Prescriber_Id__c.field-meta.xml
<CustomField>
    <fullName>Prescriber_Id__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Prescriber ID</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

Prod-EU/force-app/main/default/objects/Address__c/Address__c.object-meta.xml
<CustomObject>
    <description>Created this custom object to track Address information.</description>
    <label>Address</label>
    <nameField>
        <displayFormat>A-{0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Prod-EU/force-app/main/default/objects/Address__c/fields/Address_Line_1__c.field-meta.xml
<CustomField>
    <fullName>Address_Line_1__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Straße, Hausnummer</inlineHelpText>
    <label>Address Line 1</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

Prod-EU/force-app/main/default/objects/Address__c/fields/Address_Line_2__c.field-meta.xml
<CustomField>
    <fullName>Address_Line_2__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Zusätzliche Informationen</inlineHelpText>
    <label>Address Line 2</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

Prod-EU/force-app/main/default/objects/Address__c/fields/Address_Line_3__c.field-meta.xml
<CustomField>
    <fullName>Address_Line_3__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Alternativer Empfänger</inlineHelpText>
    <label>Address Line 3</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

Prod-EU/force-app/main/default/objects/Address__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>City</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

Prod-EU/force-app/main/default/objects/Address__c/fields/Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Postal_Code__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Postal Code</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

Prod-EU/force-app/main/default/objects/Address__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Bill To</fullName>
            </value>
            <value>
                <fullName>Ship To</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Prod-EU/force-app/main/default/objects/Related_Account__c/Related_Account__c.object-meta.xml
<CustomObject>
    <description>Jagan 04/25/2017 - Object holds many to many relationship between Accounts.</description>
    <label>Related Account</label>
    <nameField>
        <displayFormat>RA-{00000}</displayFormat>
        <label>Relation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Related Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Prod-EU/force-app/main/default/objects/Related_Account__c/fields/Child_Account__c.field-meta.xml
<CustomField>
    <fullName>Child_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Field holds the child account (Prescriber) information</description>
    <label>Child Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>contains</operation>
            <value>Prescriber, Facility, Pharmacy</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Linked Accounts</relationshipLabel>
    <relationshipName>Related_Child_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

Prod-EU/force-app/main/default/objects/Related_Account__c/fields/OK_Status__c.field-meta.xml
<CustomField>
    <fullName>OK_Status__c</fullName>
    <description>OneKey - Status like Valid, Invalid, Provisional</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Provisional</fullName>
            </value>
            <value>
                <fullName>Valid</fullName>
            </value>
            <value>
                <fullName>Invalid</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Prod-EU/force-app/main/default/objects/Related_Account__c/fields/Parent_Account__c.field-meta.xml
<CustomField>
    <fullName>Parent_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Field holds the parent account information</description>
    <label>Parent Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>contains</operation>
            <value>Facility, Hospital, Payor, Pharmacy</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Linked Accounts</relationshipLabel>
    <relationshipName>Related_Parent_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

Prod-EU/force-app/main/default/classes/ClsAccountValRequestTriggerHandlerTest.cls
/****************************************************************************************************************
@Author        : Pradeep Sadasivan
@Date Created    : 04/09/2020
@Description    : Test class for AccountChangeEvent IQVIA requiremnet- NS-743                  - 
****************************************************************************************************************/@isTest
private class ClsAccountValRequestTriggerHandlerTest{
     @testSetup
     //create Test data
     private static void setup(){
     Account prescriberAccount = new Account(FirstName = 'Joe',
                                       LastName  = 'Prescriber',
                                       Gender__c =  'Male',
                                       ShippingStreet = 'Street1',
                                       ShippingCity ='Petersburger',
                                       ShippingPostalCode = '10247',
                                       ShippingState = 'Berlin',
                                       ShippingCountry = 'Germany',
                                       Prescriber_Id__c = '23333333',
                                       BillingStreet = 'Street1',
                                       BillingCity ='Petersburger',
                                       BillingPostalCode = '10247',
                                       BillingState = 'Berlin',
                                       BillingCountry = 'Germany',
                                       OK_Status__c = 'Valid',    
                                       RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('DE Prescriber').getRecordTypeId());
    insert prescriberAccount ;
    Account medicalFacilityAccount = new Account(Name  = 'Medical facility',
                                                 ShippingStreet = 'Street1',
                                                 ShippingCity ='Petersburger',
                                                 ShippingPostalCode = '10247',
                                                 ShippingState = 'Berlin',
                                                 ShippingCountry = 'Germany',
                                                 BillingStreet = 'Street1',
                                                 BillingCity ='Petersburger',
                                                 BillingPostalCode = '10247',
                                                 BillingState = 'Berlin',
                                                 BillingCountry = 'Germany',
                                                 RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('DE Medical Facility').getRecordTypeId());
    insert medicalFacilityAccount;
    Related_Account__c childAccount = new Related_Account__c(Parent_Account__c = medicalFacilityAccount.Id,
                                       Child_Account__c = prescriberAccount.Id
                                      );
    insert childAccount;
    Address__c  addressShip = new Address__c (Address_Line_1__c  = 'Line1',
                                       Address_Line_2__c = 'Line2',
                                       Address_Line_3__c =  'Line3',
                                       City__c= 'Petersburger',
                                       Country__c = 'Germany',
                                       Postal_Code__c = '10247',
                                       Type__c ='Ship To',
                                       RecordTypeID = '0120Y000000Arkq',
                                       Account__c = prescriberAccount.Id );
    insert addressShip;
    Address__c  addressBill = new Address__c (Address_Line_1__c  = 'Line1',
                                       Address_Line_2__c = 'Line2',
                                       Address_Line_3__c =  'Line3',
                                       City__c= 'Petersburger',
                                       Country__c = 'Germany',
                                       Postal_Code__c = '10247',
                                       Type__c ='Bill To',
                                       RecordTypeID = '0120Y000000Arkq',
                                       Account__c = prescriberAccount.Id);
    insert addressBill;
	}         
    @isTest
    //Update Activity Account
    Static void creativeActivityValidationRequestActivity(){
   	Account acc =  [SELECT Id,LastName FROM Account WHERE LastName = 'Prescriber' LIMIT 1];    
    Test.enableChangeDataCapture();
    acc.LastName ='Test change';
   	acc.ShippingPostalCode = '46236';
    Test.startTest();
    update acc;
    Test.stopTest();
    }
    //Update Workplace Account
    @isTest
    Static void creativeActivityValidationRequestWorkplace(){
    Test.enableChangeDataCapture();
    Account acc =  [SELECT Id,Name,ShippingPostalCode FROM Account WHERE Name = 'Medical facility' LIMIT 1];
    acc.Name ='Facility level2';
    acc.ShippingPostalCode = '46236';
    Test.startTest();
    update acc;
    Test.stopTest();
    }
     @isTest
    //Update Activity Account
    Static void inactivateAccount(){
   	Account acc =  [SELECT Id,LastName,OK_Status__c FROM Account WHERE LastName = 'Prescriber' LIMIT 1];    
    Test.enableChangeDataCapture();
    acc.OK_Status__c = 'Invalid';
    Test.startTest();
    update acc;
    Test.stopTest();
    }
}