Prod-EU/force-app/main/default/objects/Account/fields/Address_Line_2__c.field-meta.xml
<CustomField>
    <fullName>Address_Line_2__c</fullName>
    <description>To Populate Address Line 2 in S-Docs.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Address Line 2 (S-Docs)</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

Prod-EU/force-app/main/default/objects/Address__c/Address__c.object-meta.xml
<CustomObject>
    <description>Created this custom object to track Address information.</description>
    <label>Address</label>
    <nameField>
        <displayFormat>A-{0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Prod-EU/force-app/main/default/objects/Address__c/fields/Address_Line_1__c.field-meta.xml
<CustomField>
    <fullName>Address_Line_1__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Straße, Hausnummer</inlineHelpText>
    <label>Address Line 1</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

Prod-EU/force-app/main/default/objects/Address__c/fields/Address_Line_2__c.field-meta.xml
<CustomField>
    <fullName>Address_Line_2__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Zusätzliche Informationen</inlineHelpText>
    <label>Address Line 2</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

Prod-EU/force-app/main/default/objects/Address__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>City</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

Prod-EU/force-app/main/default/objects/Address__c/fields/Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Postal_Code__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Postal Code</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

Prod-EU/force-app/main/default/objects/Address__c/fields/Primary_Flag__c.field-meta.xml
<CustomField>
    <fullName>Primary_Flag__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Primary</label>
    <type>Checkbox</type>
</CustomField>

Prod-EU/force-app/main/default/objects/Address__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State/Province</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Country__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>States</valueSetName>
    </valueSet>
</CustomField>

Prod-EU/force-app/main/default/objects/Address__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Bill To</fullName>
            </value>
            <value>
                <fullName>Ship To</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Prod-EU/force-app/main/default/classes/ClsAddressChangeEventTriggerHandler.cls
public class ClsAddressChangeEventTriggerHandler
{
    //Method will process the inserted onekey id from onekey (Ship To) and creates a corresponding Bill To if there isn't one already
    public static void processOneKeyAddresses(Set<String> oneKeyAddressIds, Set<String> accountIds)
    {
        system.debug('*******ADDRCHGEVT - Entered the method processOneKeyAddresses');
        Set<Id> accountIdsWithBillTo = new Set<Id>();
        List<Address__c> billToAddressesToBeCreated = new List<Address__c>();

        //Populate the set with the accountIds that have already Billto association
        for(Address__c addr : [SELECT Id, Account__c FROM Address__c WHERE Account__c IN : accountIds AND Type__c = 'Bill To'])
            accountIdsWithBillTo.add(addr.Account__c);
        
        //For the addresses that are inserted by OneKey
        for(Address__c shipToAddr : [SELECT Id, Account__c, RecordTypeId, Createdby.Name, Address_Line_1__c, Address_Line_2__c, City__c, State__c, Postal_Code__c, Country__c, Primary_Flag__c FROM Address__c WHERE Id IN : oneKeyAddressIds])
        {
            system.debug('Createdby Name is ' + shipToAddr.Createdby.Name);
            //If there isn't any Billto associated to associated then create a bill to with the ship to details
            if(accountIdsWithBillTo!= null && !accountIdsWithBillTo.contains(shipToAddr.Account__c) && shipToAddr.Createdby.Name != 'Automated Process')
            {
                system.debug('*******ADDRCHGEVT - No Bill to exists for this account, so creating one');
                Address__c billToAddr = new Address__c();
                billToAddr.Account__c = shipToAddr.Account__c;
                billToAddr.Address_Line_1__c = shipToAddr.Address_Line_1__c;
                billToAddr.Address_Line_2__c = shipToAddr.Address_Line_2__c;
                billToAddr.City__c = shipToAddr.City__c;
                billToAddr.State__c = shipToAddr.State__c;
                billToAddr.Postal_Code__c = shipToAddr.Postal_Code__c;
                billToAddr.Country__c = shipToAddr.Country__c;
                billToAddr.Primary_Flag__c = shipToAddr.Primary_Flag__c;
                billToAddr.Type__c = 'Bill To';
                billToAddr.RecordTypeId = shipToAddr.RecordTypeId;
                billToAddressesToBeCreated.add(billToAddr);
            }

        }
        if(!billToAddressesToBeCreated.isEmpty()){
            system.debug('*******ADDRCHGEVT - Insert Billto list of addresses');
            ClsAccountAddressTriggerStaticClass.addressChangeInvokedFromAddress = true;
            insert billToAddressesToBeCreated;
        }
    }
}