Prod-EU/force-app/main/default/objects/Account/fields/Benefit__c.field-meta.xml
<CustomField>
    <fullName>Benefit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Tracks the primary benefit record</description>
    <label>Primary Benefit</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Id</field>
            <operation>equals</operation>
            <valueField>Benefit__c.Account__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Benefit__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>AccountBenefits</relationshipName>
    <type>Lookup</type>
</CustomField>

Prod-EU/force-app/main/default/objects/Account/fields/Fund__c.field-meta.xml
<CustomField>
    <fullName>Fund__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Fund the customer is associated to</description>
    <label>Fund</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 OR 3) AND 2</booleanFilter>
        <filterItems>
            <field>$Source.Payor__c</field>
            <operation>equals</operation>
            <valueField>Fund__c.Payor__c</valueField>
        </filterItems>
        <filterItems>
            <field>Fund__c.Is_Fund_Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>$Source.Id</field>
            <operation>equals</operation>
            <valueField>Fund__c.Payor__c</valueField>
        </filterItems>
        <infoMessage>Fund is not active.</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Fund__c</referenceTo>
    <relationshipLabel>Consumers</relationshipLabel>
    <relationshipName>Funds</relationshipName>
    <type>Lookup</type>
</CustomField>

Prod-EU/force-app/main/default/objects/Account/fields/Payor__c.field-meta.xml
<CustomField>
    <fullName>Payor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Payor tied to the Benefit record</description>
    <label>Payor</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>contains</operation>
            <value>Payor</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Accounts (Payor)</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

Prod-EU/force-app/main/default/objects/Account/fields/Price_Book__c.field-meta.xml
<CustomField>
    <fullName>Price_Book__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Price Book</label>
    <referenceTo>Pricebook2</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

Prod-EU/force-app/main/default/objects/Benefit__c/Benefit__c.object-meta.xml
<CustomObject>
    <description>Jagan 03/29/2017 - Created this custom object to track Benefits information.</description>
    <label>Benefit</label>
    <nameField>
        <displayFormat>B-{0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Benefits</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Prod-EU/force-app/main/default/objects/Benefit__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup field for Account</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Benefits</relationshipLabel>
    <relationshipName>Benefits</relationshipName>
    <type>Lookup</type>
</CustomField>

Prod-EU/force-app/main/default/objects/Benefit__c/fields/Auth_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Auth_End_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Auth End Date</label>
    <type>Date</type>
</CustomField>

Prod-EU/force-app/main/default/objects/Benefit__c/fields/Auth_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Auth_Start_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Auth Start Date</label>
    <type>Date</type>
</CustomField>

Prod-EU/force-app/main/default/objects/Benefit__c/fields/Benefit_Hierarchy__c.field-meta.xml
<CustomField>
    <fullName>Benefit_Hierarchy__c</fullName>
    <label>Benefit Hierarchy</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Primary</fullName>
            </value>
            <value>
                <fullName>Secondary</fullName>
            </value>
            <value>
                <fullName>Tertiary</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Prod-EU/force-app/main/default/objects/Benefit__c/fields/Member_Id__c.field-meta.xml
<CustomField>
    <fullName>Member_Id__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Member ID</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

Prod-EU/force-app/main/default/objects/Benefit__c/fields/Payor__c.field-meta.xml
<CustomField>
    <fullName>Payor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to Account with Payer record type</description>
    <label>Payor</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>contains</operation>
            <value>Payor</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Payors</relationshipLabel>
    <relationshipName>Payors</relationshipName>
    <type>Lookup</type>
</CustomField>

Prod-EU/force-app/main/default/objects/Benefit__c/recordTypes/CA_Benefit.recordType-meta.xml
<RecordType>
    <fullName>CA_Benefit</fullName>
    <active>true</active>
    <description>Benefit for Canada</description>
    <label>CA Benefit</label>
</RecordType>

Prod-EU/force-app/main/default/objects/Fund__c/Fund__c.object-meta.xml
<CustomObject>
    <description>Object will track information related to Funded Patients.</description>
    <label>Fund</label>
    <nameField>
        <displayFormat>F-{00000}</displayFormat>
        <label>Fund Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fund</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Prod-EU/force-app/main/default/objects/Fund__c/fields/Amount_Limit__c.field-meta.xml
<CustomField>
    <fullName>Amount_Limit__c</fullName>
    <description>Amount limit enforced in PO</description>
    <label>Amount Limit</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

Prod-EU/force-app/main/default/objects/Fund__c/fields/Auth_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Auth_End_Date__c</fullName>
    <description>Date when the authorization ends</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Auth End Date</label>
    <type>Date</type>
</CustomField>

Prod-EU/force-app/main/default/objects/Fund__c/fields/Auth_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Auth_Start_Date__c</fullName>
    <defaultValue>Today()</defaultValue>
    <description>Date when the authorization starts</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Auth Start Date</label>
    <type>Date</type>
</CustomField>

Prod-EU/force-app/main/default/objects/Fund__c/fields/Is_Fund_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Fund_Active__c</fullName>
    <description>Check if the current date falls between the Auth start and end date.</description>
    <formula>If(ISBLANK(Auth_End_Date__c), TRUE, If(Today() &lt;=  Auth_End_Date__c, TRUE, FALSE))</formula>
    <label>Is Fund Active?</label>
    <type>Checkbox</type>
</CustomField>

Prod-EU/force-app/main/default/objects/Fund__c/fields/Limit_Type__c.field-meta.xml
<CustomField>
    <fullName>Limit_Type__c</fullName>
    <description>Type of limit enforce in PO</description>
    <label>Limit Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Quantity</fullName>
            </value>
            <value>
                <fullName>Amount</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Prod-EU/force-app/main/default/objects/Fund__c/fields/Payor__c.field-meta.xml
<CustomField>
    <fullName>Payor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Fund associated with the Payor.</description>
    <label>Payor</label>
    <lookupFilter>
        <active>false</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <errorMessage>Fund Payor should be of Payor type if using GBP or EUR. Otherwise Fund Currency should be in USD.</errorMessage>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>contains</operation>
            <value>Payor</value>
        </filterItems>
        <filterItems>
            <field>$Source.CurrencyIsoCode</field>
            <operation>equals</operation>
            <value>USD</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Fund (Payor)</relationshipLabel>
    <relationshipName>Payor_Fund</relationshipName>
    <type>Lookup</type>
</CustomField>

Prod-EU/force-app/main/default/objects/Fund__c/fields/PO_Reference_Number__c.field-meta.xml
<CustomField>
    <fullName>PO_Reference_Number__c</fullName>
    <description>Tracks the PO Number</description>
    <encryptionScheme>None</encryptionScheme>
    <label>PO Reference Number</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

Prod-EU/force-app/main/default/objects/Fund__c/fields/Receiver_Qty_Limit__c.field-meta.xml
<CustomField>
    <fullName>Receiver_Qty_Limit__c</fullName>
    <description>Qty of Receivers that can be used within the Authorized period</description>
    <label>Receiver Qty Limit</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Prod-EU/force-app/main/default/objects/Fund__c/fields/Sensor_Limit__c.field-meta.xml
<CustomField>
    <fullName>Sensor_Limit__c</fullName>
    <description>Qty of Sensors that can be used within the Authorized period</description>
    <label>Sensor Qty Limit</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Prod-EU/force-app/main/default/objects/Fund__c/fields/Transmitter_Qty_Limit__c.field-meta.xml
<CustomField>
    <fullName>Transmitter_Qty_Limit__c</fullName>
    <description>Qty of Transmitters that can be used within the Authorized period</description>
    <label>Transmitter Qty Limit</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Prod-EU/force-app/main/default/objects/Fund__c/recordTypes/Purchase_Order.recordType-meta.xml
<RecordType>
    <fullName>Purchase_Order</fullName>
    <active>true</active>
    <description>Purchase Order Recordtype to track the Funds</description>
    <label>Purchase Order</label>
</RecordType>

Prod-EU/force-app/main/default/classes/ClsFundService_Test.cls
@isTest
public class ClsFundService_Test {
   /* 
     @isTest static void TestOrderCreationAndUpdateCA(){
        Test.startTest();
        //Insert 1 consumer account record
        List<Account> consumerAccts = ClsTestDataFactory.createAccountsWithBillingAddress(1, 'CA Consumer', 'Canada');
        Account payorAccount = ClsTestDataFactory.createAccountsWithBillingAddress(1, 'CA Payor', 'Canada')[0];

        //Create Pricebook
        Map<String, Id> customPricebookMap = ClsTestDataFactory.createCustomPricebook(new List <String>{'CA Cash'});
        String customPricebookId = customPricebookMap.get('CA Cash');
         
         //payorAccount.Price_Book__c = customPricebookId;
         //update payorAccount;
        
        //Create Products
        Map<String, Id> products = ClsTestDataFactory.createProducts(new List<String> {'STK-GF-013', 'STT-GF-004', 'DEX-SHIP-01','FREIGHT CHARGE'});
        
        //Update the virtual sku productIdToPbeId
        Product2 virtualProd = [SELECT Id, Is_Virtual_Product__c FROM Product2 WHERE NAME = 'DEX-SHIP-01'];
        virtualProd.Is_Virtual_Product__c = true;
        update virtualProd;
        
        //Create Pricebook EntryPair
        Map<Id, Decimal> productIdToPriceMap = new Map<Id, Decimal>();
        for(String productName : products.keySet()){
            productIdToPriceMap.put(products.get(productName), 125.00);
            
        }
        Map<Id, Id> productIdToPbeId = ClsTestDataFactory.createCustomPricebookEntriesCA(productIdToPriceMap, customPricebookId);
        Id caOrderRecdTypeId = Schema.SObjectType.Order.getRecordTypeInfosByDeveloperName().get('CA_Sales_Order').getRecordTypeId();
        
        Id caOppRecType = Schema.SObjectType.Benefit__c.getRecordTypeInfosByDeveloperName().get('CA_Benefit').getRecordTypeId();
           // [Select Id from RecordType where isActive = true AND SobjectType = 'Benefit__c' and DeveloperName = 'CA_Benefit'].Id;
         payorAccount.Price_Book__c = customPricebookId;   
         update payorAccount ; 
         
         //Create new Benefit and associate it to the payor
        Benefit__c primaryBenefit = new Benefit__c();
        primaryBenefit.RecordTypeId = caOppRecType;
        primaryBenefit.Account__c = consumerAccts[0].Id;
        primaryBenefit.Member_Id__c = '1789657890';
        primaryBenefit.Payor__c =payorAccount.Id;
        primaryBenefit.Benefit_Hierarchy__c = 'Primary';
        insert primaryBenefit;
        
       Recordtype recType=[select id from recordtype where developername='Purchase_Order'];
        Fund__c Fd = new Fund__c();
        Fd.PO_Reference_Number__c ='87666787';
        Fd.Limit_Type__c ='Quantity';        
        Fd.Payor__c = payorAccount.Id;
        Fd.Amount_Limit__c = 100000;
        Fd.Auth_End_Date__c = Date.today()+10;
        Fd.Auth_Start_Date__c = Date.today();
        Fd.Receiver_Qty_Limit__c = 100; 
        Fd.Sensor_Limit__c = 100; 
        Fd.Transmitter_Qty_Limit__c = 100 ;     
        fd.recordtypeid=recType.id;
       // fd.Is_Fund_Active__c = true;
        insert Fd ;  
  		System.debug('**fd---'+fd);
         
        //Create Order record
        ClsOrderTriggerStaticClass.isExecuting = false;
        Order newOrder = new Order();
        newOrder.AccountId = consumerAccts[0].Id;
        newOrder.RecordtypeId = caOrderRecdTypeId;
        newOrder.Type = 'CA STANDARD';
        newOrder.EffectiveDate = System.today();
        newOrder.Price_Book__c = customPricebookId;
        newOrder.Pricebook2Id = customPricebookId; 
        newOrder.Status = 'Draft';
         newOrder.Fund__c = fd.Id;
        insert newOrder;        
      
        
        //List order line items
        List<OrderItem> orderItemList = new List<OrderItem>();
        for(Id pbeId : productIdToPbeId.values()){
            OrderItem oi = new OrderItem();
            oi.OrderId = newOrder.Id;
            oi.PricebookEntryId = pbeId;
            oi.Quantity = 1;
            oi.UnitPrice = 125.00;
            oi.Tracking_Number__c = '12345';
            oi.Product_Name__c = 'STK-GF-109' ;
            orderItemList.add(oi);
        }
        insert orderItemList;
        
         ClsFundService.getPONumber(fd.Id);
         clsFundService.checkFundBalance(newOrder.Id);  
         ClsFundService.chargeFund(newOrder.Id);
        Test.stopTest();
    }
	*/
}