Prod-EU/force-app/main/default/objects/Account/fields/Credit_Hold__c.field-meta.xml
<CustomField>
    <fullName>Credit_Hold__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Flag denotes if a customer is on Credit hold or not</description>
    <label>Credit Hold</label>
    <type>Checkbox</type>
</CustomField>

Prod-EU/force-app/main/default/objects/Account/fields/Payment_Terms__c.field-meta.xml
<CustomField>
    <fullName>Payment_Terms__c</fullName>
    <description>Use to set the Payment Terms at the Account Level</description>
    <label>Payment Terms</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Payment_Term</valueSetName>
    </valueSet>
</CustomField>

Prod-EU/force-app/main/default/objects/Account/fields/Subscription_Pending_Payments__c.field-meta.xml
<CustomField>
    <fullName>Subscription_Pending_Payments__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Subscription Pending Payments</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Prod-EU/force-app/main/default/objects/Account/fields/System_Of_Origin__c.field-meta.xml
<CustomField>
    <fullName>System_Of_Origin__c</fullName>
    <defaultValue>&apos;crm&apos;</defaultValue>
    <encryptionScheme>None</encryptionScheme>
    <label>System Of Origin</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

Prod-EU/force-app/main/default/objects/Account/fields/System_Of_Origin_Id__c.field-meta.xml
<CustomField>
    <fullName>System_Of_Origin_Id__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>System Of Origin ID</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

Prod-EU/force-app/main/default/objects/Address__c/Address__c.object-meta.xml
<CustomObject>
    <description>Created this custom object to track Address information.</description>
    <label>Address</label>
    <nameField>
        <displayFormat>A-{0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Prod-EU/force-app/main/default/objects/Address__c/fields/Address_Line_1__c.field-meta.xml
<CustomField>
    <fullName>Address_Line_1__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Straße, Hausnummer</inlineHelpText>
    <label>Address Line 1</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

Prod-EU/force-app/main/default/objects/Address__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>City</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

Prod-EU/force-app/main/default/objects/Address__c/fields/Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Postal_Code__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Postal Code</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

Prod-EU/force-app/main/default/objects/Address__c/fields/Primary_Flag__c.field-meta.xml
<CustomField>
    <fullName>Primary_Flag__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Primary</label>
    <type>Checkbox</type>
</CustomField>

Prod-EU/force-app/main/default/objects/Address__c/fields/System_Of_Origin__c.field-meta.xml
<CustomField>
    <fullName>System_Of_Origin__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>System Of Origin</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

Prod-EU/force-app/main/default/objects/Address__c/fields/System_Of_Origin_Id__c.field-meta.xml
<CustomField>
    <fullName>System_Of_Origin_Id__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>System Of Origin ID</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

Prod-EU/force-app/main/default/objects/Address__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Bill To</fullName>
            </value>
            <value>
                <fullName>Ship To</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Prod-EU/force-app/main/default/objects/CRM_Attachment_Event__e/CRM_Attachment_Event__e.object-meta.xml
<CustomObject>
    <description>Platform event invoked from Kafka to Salesforce to attach document to an entity in Salesforce.</description>
    <label>CRM Attachment Event - In</label>
    <pluralLabel>CRM Attachment Events - In</pluralLabel>
</CustomObject>

Prod-EU/force-app/main/default/objects/CRM_Attachment_Event__e/fields/classification__c.field-meta.xml
<CustomField>
    <fullName>classification__c</fullName>
    <label>classification</label>
    <length>254</length>
    <type>Text</type>
</CustomField>

Prod-EU/force-app/main/default/objects/CRM_Attachment_Event__e/fields/content__c.field-meta.xml
<CustomField>
    <fullName>content__c</fullName>
    <label>content</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

Prod-EU/force-app/main/default/objects/CRM_Attachment_Event__e/fields/name__c.field-meta.xml
<CustomField>
    <fullName>name__c</fullName>
    <label>name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

Prod-EU/force-app/main/default/objects/CRM_Attachment_Event__e/fields/operation__c.field-meta.xml
<CustomField>
    <fullName>operation__c</fullName>
    <label>operation</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

Prod-EU/force-app/main/default/objects/CRM_Attachment_Event__e/fields/referenceNumberName__c.field-meta.xml
<CustomField>
    <fullName>referenceNumberName__c</fullName>
    <label>referenceNumberName</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

Prod-EU/force-app/main/default/objects/CRM_Attachment_Event__e/fields/referenceNumberValue__c.field-meta.xml
<CustomField>
    <fullName>referenceNumberValue__c</fullName>
    <label>referenceNumberValue</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

Prod-EU/force-app/main/default/objects/CRM_Attachment_Event__e/fields/version__c.field-meta.xml
<CustomField>
    <fullName>version__c</fullName>
    <label>version</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

Prod-EU/force-app/main/default/objects/Finance_Detail__c/Finance_Detail__c.object-meta.xml
<CustomObject>
    <label>Finance Detail</label>
    <nameField>
        <displayFormat>FD-{0000}</displayFormat>
        <label>Finance Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Finance Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Prod-EU/force-app/main/default/objects/Finance_Detail__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Finance Details</relationshipLabel>
    <relationshipName>Finance_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Prod-EU/force-app/main/default/objects/Finance_Detail__c/fields/Card_Type__c.field-meta.xml
<CustomField>
    <fullName>Card_Type__c</fullName>
    <label>Card Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>N/A</fullName>
                <default>true</default>
                <label>N/A</label>
            </value>
            <value>
                <fullName>Visa</fullName>
            </value>
            <value>
                <fullName>Mastercard</fullName>
            </value>
            <value>
                <fullName>Amex</fullName>
                <label>AMEX</label>
            </value>
            <value>
                <fullName>American Express</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Prod-EU/force-app/main/default/objects/Finance_Detail__c/fields/CC_Address__c.field-meta.xml
<CustomField>
    <fullName>CC_Address__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CC Address</label>
    <referenceTo>Address__c</referenceTo>
    <relationshipLabel>Finance Details</relationshipLabel>
    <relationshipName>Finance_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

Prod-EU/force-app/main/default/objects/Finance_Detail__c/fields/CC_CUR__c.field-meta.xml
<CustomField>
    <fullName>CC_CUR__c</fullName>
    <label>CC CUR</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CC_Currency</valueSetName>
    </valueSet>
</CustomField>

Prod-EU/force-app/main/default/objects/Finance_Detail__c/fields/Expiry_Date__c.field-meta.xml
<CustomField>
    <fullName>Expiry_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Expiry Date</label>
    <length>7</length>
    <type>Text</type>
</CustomField>

Prod-EU/force-app/main/default/objects/Finance_Detail__c/fields/Token__c.field-meta.xml
<CustomField>
    <fullName>Token__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Card Token</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

Prod-EU/force-app/main/default/objects/Finance_Detail__c/recordTypes/Credit_Card.recordType-meta.xml
<RecordType>
    <fullName>Credit_Card</fullName>
    <active>true</active>
    <label>Credit Card</label>
</RecordType>

Prod-EU/force-app/main/default/objects/GoogleStorage__c/GoogleStorage__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>GoogleStorage</label>
</CustomObject>

Prod-EU/force-app/main/default/objects/GoogleStorage__c/fields/AccessToken__c.field-meta.xml
<CustomField>
    <fullName>AccessToken__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>AccessToken</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

Prod-EU/force-app/main/default/objects/GoogleStorage__c/fields/Expiration_Time__c.field-meta.xml
<CustomField>
    <fullName>Expiration_Time__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Expiration_Time</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

Prod-EU/force-app/main/default/classes/ClsTrgCRMAttachmentEvent_Test.cls
@isTest
public class ClsTrgCRMAttachmentEvent_Test{
    
    @testSetup static void setup() {
        Map<String, String> mapPriceBook = ClsTestDataFactory.createCPB(new List<String>{'CH Cash','DE Netto-Preis Cash'}, 'CHF');        
        Map<String, Id> mapProduct = ClsTestDataFactory.createProducts(new List<String>{'Product-01', 'Product-02', 'Product-03', 'DEX-SHIP-01'});
        Map<Id, Decimal> productIdToPriceMap = new Map<Id, Decimal>{mapProduct.values()[0] => 10, mapProduct.values()[1] => 0, mapProduct.values()[2] => 0 };
        Map<Id, Id> mapPBE = ClsTestDataFactory.CreateCPBEntries(productIdToPriceMap, mapPriceBook.get('CH Cash'), 'CHF');
    }
    
    @isTest public static void TestAttchment(){
          
        GoogleStorage__c supportConfig = GoogleStorage__c.getOrgDefaults();
        system.debug('Custom Setting Before: ' + supportConfig);
        supportConfig.Name = 'Test';
        supportConfig.AccessToken__c = 'ya29.c.Ko8B1QcDgdGnI7_zCMVY7d518kmkLCHyqtgONAkFjF3P0r5SXMSoWtkv9tp5a4_Wik74_KIzI30VJEXA_UNuO0GjWEsrM5tyjrMm73RgECReXSllCUBKpNiVHQiEachrxfT6aTwn6Bb-1YlbVte__xtwJc67nzOLUXyqIJd_ogW4yQgNsYd-VQ7pMT7HbC229nk';
        Long timeSince = System.now().getTime();
        Long longIssueTime = timeSince;
        String expTime = String.valueOf(longIssueTime + 3600000); // 1 hr
        supportConfig.Expiration_Time__c = expTime;
        upsert supportConfig;
        
        Id chOrderRecdTypeId = Schema.SObjectType.Order.getRecordTypeInfosByDeveloperName().get('CH_Sales_Order').getRecordTypeId();
        
        Account payorAccount = ClsTestDataFactory.createAccountsWithBillingAddress(1, 'CH Consumer', 'Switzerland')[0];
        payorAccount.Subscription_Pending_Payments__c = 1;
        update payorAccount;
            List<Account> lstAccount = [SELECT Id, Name,Credit_Hold__c FROM Account where Subscription_Pending_Payments__c >0];
            
            List<Product2> lstProduct = [SELECT Id, Name FROM Product2];  
            List<Address__c> lstAddress = new List<Address__c>{
                new Address__c(Account__c = lstAccount[0].Id,Type__c = 'Bill To', Country__c = 'Switzerland', City__c = 'Rosemont', Address_Line_1__c = 'W Higgins Rd', Postal_Code__c = '60089', Primary_Flag__c = true, System_Of_Origin__c = '12345', System_Of_Origin_Id__c = 'abcdefg'),
                    new Address__c(Account__c = lstAccount[0].Id,Type__c = 'Ship To',Country__c = 'Switzerland', City__c = 'Rosemont', Address_Line_1__c = 'W Higgins Rd', Postal_Code__c = '60089', Primary_Flag__c = true, System_Of_Origin__c = '12345', System_Of_Origin_Id__c = 'abcdefg'),
                    new Address__c(Account__c = payorAccount.Id,Type__c = 'Bill To', Country__c = 'Switzerland', City__c = 'Rosemont', Address_Line_1__c = 'W Higgins Rd', Postal_Code__c = '60089', Primary_Flag__c = true, System_Of_Origin__c = '12345', System_Of_Origin_Id__c = 'abcdefg'),
                    new Address__c(Account__c = payorAccount.Id,Type__c = 'Ship To',Country__c = 'Switzerland', City__c = 'Rosemont', Address_Line_1__c = ' W Higgins Rd', Postal_Code__c = '60089', Primary_Flag__c = true, System_Of_Origin__c = '12345', System_Of_Origin_Id__c = 'abcdefg')
                    };
                        insert lstAddress;
            
            Id rtIdFDCC = Schema.SObjectType.Finance_Detail__c.getRecordTypeInfosByDeveloperName().get('Credit_Card').getRecordTypeId();
            Finance_Detail__c fd1= new Finance_Detail__c(Account__c=payorAccount.Id,Token__c='1111', Card_Type__c='Mastercard',CC_CUR__c='CHF',
                                                         Expiry_Date__c='1112/21', Primary__c=true, CC_Address__c=lstAddress[0].id, RecordTypeId=rtIdFDCC);
            insert fd1;
            List<PricebookEntry> lstPBE = [SELECT Id,Name, Pricebook2Id, Product2Id FROM PricebookEntry WHERE Pricebook2.Name = 'CH Cash'];
            Order objOrder = new Order(AccountId = payorAccount.Id, EffectiveDate = Date.today(), Status = 'Draft', Type = 'CH STANDARD', 
                                       Pricebook2Id = lstPBE[0].Pricebook2Id,
                                       Payment_Terms__c = 'net30',
                                       Finance_Detail__c = fd1.Id,
                                       RecordTypeId = chOrderRecdTypeId, CurrencyISOCode = 'CHF');
            insert objOrder;
            List<OrderItem> lstOrderItem = new List<OrderItem>();
            lstOrderItem.add(new OrderItem(PricebookEntryId = lstPBE[0].Id, OrderId = objOrder.Id, Quantity = 1, UnitPrice = 10));
            insert lstOrderItem;
            
            order ord = [Select id,OrderNumber from Order where Id=:objOrder.Id];
            System.debug('**objOrder--'+ord.Id+'**--ordNumber--'+ord.OrderNumber); 
            
            
            CRM_Attachment_Event__e crmAttachObj = new CRM_Attachment_Event__e(version__c='3.0',eventDate__c='2020-04-22T23=14=07.943Z',
                                                                               entityType__c='attachment',eventSource__c='3pl',eventSourceID__c='JVGL06093702501486166029',operation__c='create',
                                                                               stage__c='confirmed',systemOfOrigin__c='crm',systemOfOriginID__c='01200020',parentSystemOfOriginID__c=null,author__c=null,
                                                                               metadata__c='',classification__c='proofOfDelivery',referenceNumberName__c='orderNumber',
                                                                               referenceNumberValue__c=ord.OrderNumber,name__c='ePod-JVGL06093702501486166029',type__c='pdf',
                                                                               content__c='gcp=eu.attachment.3pl.raw/content/5f9ce630-9bab-4d10-aa03-7517e0d5aa1f');
         
        Database.SaveResult sr = EventBus.publish(crmAttachObj);
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new ClsMockHttpResponseGoogleStorage());
        //System.enqueueJob(new PEClsHandleAttachmentEvents.LoadFileQueuable(ord.OrderNumber,crmAttachObj.content__c,
                                                                          // crmAttachObj.name__c,crmAttachObj.eventSource__c, crmAttachObj.eventSourceID__c, ord.Id));
        
        Test.stopTest();
        
    }
    
     @isTest public static void TestAttchment2(){
          
        GoogleStorage__c supportConfig = GoogleStorage__c.getOrgDefaults();
        system.debug('Custom Setting Before: ' + supportConfig);
        supportConfig.Name = 'Test';
        //supportConfig.AccessToken__c = 'ya29.c.Ko8B1QcDgdGnI7_zCMVY7d518kmkLCHyqtgONAkFjF3P0r5SXMSoWtkv9tp5a4_Wik74_KIzI30VJEXA_UNuO0GjWEsrM5tyjrMm73RgECReXSllCUBKpNiVHQiEachrxfT6aTwn6Bb-1YlbVte__xtwJc67nzOLUXyqIJd_ogW4yQgNsYd-VQ7pMT7HbC229nk';
       
        upsert supportConfig;
        
        Id chOrderRecdTypeId = Schema.SObjectType.Order.getRecordTypeInfosByDeveloperName().get('CH_Sales_Order').getRecordTypeId();
        
        Account payorAccount = ClsTestDataFactory.createAccountsWithBillingAddress(1, 'CH Consumer', 'Switzerland')[0];
        payorAccount.Subscription_Pending_Payments__c = 1;
        update payorAccount;
            List<Account> lstAccount = [SELECT Id, Name,Credit_Hold__c FROM Account where Subscription_Pending_Payments__c >0];
            
            List<Product2> lstProduct = [SELECT Id, Name FROM Product2];  
            List<Address__c> lstAddress = new List<Address__c>{
                new Address__c(Account__c = lstAccount[0].Id,Type__c = 'Bill To', Country__c = 'Switzerland', City__c = 'Rosemont', Address_Line_1__c = 'W Higgins Rd', Postal_Code__c = '60089', Primary_Flag__c = true, System_Of_Origin__c = '12345', System_Of_Origin_Id__c = 'abcdefg'),
                    new Address__c(Account__c = lstAccount[0].Id,Type__c = 'Ship To',Country__c = 'Switzerland', City__c = 'Rosemont', Address_Line_1__c = 'W Higgins Rd', Postal_Code__c = '60089', Primary_Flag__c = true, System_Of_Origin__c = '12345', System_Of_Origin_Id__c = 'abcdefg'),
                    new Address__c(Account__c = payorAccount.Id,Type__c = 'Bill To', Country__c = 'Switzerland', City__c = 'Rosemont', Address_Line_1__c = 'W Higgins Rd', Postal_Code__c = '60089', Primary_Flag__c = true, System_Of_Origin__c = '12345', System_Of_Origin_Id__c = 'abcdefg'),
                    new Address__c(Account__c = payorAccount.Id,Type__c = 'Ship To',Country__c = 'Switzerland', City__c = 'Rosemont', Address_Line_1__c = ' W Higgins Rd', Postal_Code__c = '60089', Primary_Flag__c = true, System_Of_Origin__c = '12345', System_Of_Origin_Id__c = 'abcdefg')
                    };
                        insert lstAddress;
            
            Id rtIdFDCC = Schema.SObjectType.Finance_Detail__c.getRecordTypeInfosByDeveloperName().get('Credit_Card').getRecordTypeId();
            Finance_Detail__c fd1= new Finance_Detail__c(Account__c=payorAccount.Id,Token__c='1111', Card_Type__c='Mastercard',CC_CUR__c='CHF',
                                                         Expiry_Date__c='1112/21', Primary__c=true, CC_Address__c=lstAddress[0].id, RecordTypeId=rtIdFDCC);
            insert fd1;
            List<PricebookEntry> lstPBE = [SELECT Id,Name, Pricebook2Id, Product2Id FROM PricebookEntry WHERE Pricebook2.Name = 'CH Cash'];
            Order objOrder = new Order(AccountId = payorAccount.Id, EffectiveDate = Date.today(), Status = 'Draft', Type = 'CH STANDARD', 
                                       Pricebook2Id = lstPBE[0].Pricebook2Id,
                                       Payment_Terms__c = 'net30',
                                       Finance_Detail__c = fd1.Id,
                                       RecordTypeId = chOrderRecdTypeId, CurrencyISOCode = 'CHF');
            insert objOrder;
            List<OrderItem> lstOrderItem = new List<OrderItem>(); 
            lstOrderItem.add(new OrderItem(PricebookEntryId = lstPBE[0].Id, OrderId = objOrder.Id, Quantity = 1, UnitPrice = 10));
            insert lstOrderItem;
            
            order ord = [Select id,OrderNumber from Order where Id=:objOrder.Id]; 
            CRM_Attachment_Event__e crmAttachObj = new CRM_Attachment_Event__e(version__c='3.0',eventDate__c='2020-04-22T23=14=07.943Z',
                                                                               entityType__c='attachment',eventSource__c='3pl',eventSourceID__c='JVGL06093702501486166029',operation__c='create',
                                                                               stage__c='confirmed',systemOfOrigin__c='crm',systemOfOriginID__c='01200020',parentSystemOfOriginID__c=null,author__c=null,
                                                                               metadata__c='',classification__c='proofOfDelivery',referenceNumberName__c='orderNumber',
                                                                               referenceNumberValue__c=ord.OrderNumber,name__c='ePod-JVGL06093702501486166029',type__c='pdf',
                                                                               content__c='gcp=eu.attachment.3pl.raw/content/5f9ce630-9bab-4d10-aa03-7517e0d5aa1f');
            
        
         Test.startTest();
         Test.setMock(HttpCalloutMock.class, new ClsMockHttpResponseGoogleStorage());
         EventBus.publish(crmAttachObj);
         Test.stopTest();
        
    } 
}