Prod-EU/force-app/main/default/objects/Account/fields/Email_Opt_In_Method__c.field-meta.xml
<CustomField>
    <fullName>Email_Opt_In_Method__c</fullName>
    <description>Method customer opted in for email</description>
    <label>Email Opt In Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Opt_In_Method</valueSetName>
    </valueSet>
</CustomField>

Prod-EU/force-app/main/default/objects/Account/fields/Price_Book__c.field-meta.xml
<CustomField>
    <fullName>Price_Book__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Price Book</label>
    <referenceTo>Pricebook2</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

Prod-EU/force-app/main/default/objects/SSIP_Rule__c/SSIP_Rule__c.object-meta.xml
<CustomObject>
    <description>Object stores all SSIP rule for the customers.</description>
    <label>SSIP Rule</label>
    <nameField>
        <displayFormat>SP-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SSIP Rule</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Prod-EU/force-app/main/default/objects/SSIP_Rule__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Master detail relationship to the account.</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>SSIP Rule</relationshipLabel>
    <relationshipName>SSIP_Rule</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Prod-EU/force-app/main/default/objects/SSIP_Rule__c/fields/Price_Book__c.field-meta.xml
<CustomField>
    <fullName>Price_Book__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Price book, which will filter out only SSIP Pricebooks</description>
    <label>Price Book</label>
    <referenceTo>Pricebook2</referenceTo>
    <relationshipLabel>SSIP Rule</relationshipLabel>
    <relationshipName>SSIP_Rule</relationshipName>
    <type>Lookup</type>
</CustomField>

Prod-EU/force-app/main/default/objects/SSIP_Rule__c/fields/PriceBookEntryId__c.field-meta.xml
<CustomField>
    <fullName>PriceBookEntryId__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>PriceBookEntryId</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

Prod-EU/force-app/main/default/objects/SSIP_Rule__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>SSIP Rule</relationshipLabel>
    <relationshipName>SSIP_Rule</relationshipName>
    <type>Lookup</type>
</CustomField>

Prod-EU/force-app/main/default/objects/SSIP_Rule__c/fields/Renewal_Date__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Date__c</fullName>
    <description>Date when the contract can be renewed</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Date should be greater than or equal to today&apos;s date.</inlineHelpText>
    <label>Renewal Date</label>
    <type>Date</type>
</CustomField>

Prod-EU/force-app/main/default/objects/SSIP_Rule__c/fields/Rule_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Rule_End_Date__c</fullName>
    <description>Date when the rule will end.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Date should be greater than or equal to today&apos;s date. Setting this date will delete any open schedules past this date.</inlineHelpText>
    <label>Rule End Date</label>
    <type>Date</type>
</CustomField>

Prod-EU/force-app/main/default/objects/SSIP_Rule__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&apos;Active&apos;</defaultValue>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Prod-EU/force-app/main/default/classes/BclsMICARenewalAndRuleEnd_Test.cls
@isTest
public class BclsMICARenewalAndRuleEnd_Test {
	
    @isTest
    static void MIRenewalBatchTest() {
        
        Map<String, String> mapPriceBook = ClsTestDataFactory.createCPB(new List<String>{'CAN G6 SUBSCRIPTION 12MOS Auto Renewal'},'CAD');
        Map<String, Id> mapProduct = ClsTestDataFactory.createProducts(new List<String>{'MTRNTCAGS-12MOS'});
        Map<Id, Decimal> productIdToPriceMap = new Map<Id, Decimal>();
        for(Id productId : mapProduct.values()){
            productIdToPriceMap.put(productId, 10); 
        }
        Map<Id, Id> mapPBE = ClsTestDataFactory.createCustomPricebookEntriesCA(productIdToPriceMap, mapPriceBook.get('CAN G6 SUBSCRIPTION 12MOS Auto Renewal'));
        List<PricebookEntry> lstPBE = [SELECT Id, Pricebook2Id, Product2Id FROM PricebookEntry WHERE Pricebook2.Name = 'CAN G6 SUBSCRIPTION 12MOS Auto Renewal'];
        List<Account> accountList= new List<Account>();
        Date renwalDate= date.today().adddays(90);
        Account testAccount = TestUtils.testCAConsumerAccount();
        testAccount.PersonEmail='jane.smith@sundog.net';
        testAccount.Email_Opt_In_Method__c = 'Via Email';
        insert testAccount;
        
        Product2 p = new product2();
        P.Name ='MTRNTCAGS-12MOS';
        //insert p;
        
        //for(Id ids : mapPBE.keySet()){
            SSIP_Rule__c ssip = new SSIP_Rule__c();
            ssip.Account__c=testAccount.Id;
            ssip.Renewal_Date__c=renwalDate;
            ssip.product__c=lstPBE[0].Product2Id;
            ssip.Price_Book__c = lstPBE[0].Pricebook2Id;
            ssip.PriceBookEntryId__c = lstPBE[0].Id;
            ssip.Status__c='Active';
            insert ssip; 
       // }
        
        
        Test.startTest();
        Database.executeBatch(new BclsMarketingInteractionCARenewalBatch(),200); 
        Test.stopTest();
        
        
    }
    @isTest
    static void MIRuleEndBatchTest() {
        Map<String, String> mapPriceBook = ClsTestDataFactory.createCPB(new List<String>{'CAN G6 SUBSCRIPTION 12MOS NO Renewal'},'CAD');
        Map<String, Id> mapProduct = ClsTestDataFactory.createProducts(new List<String>{'MTRNTCAGS-12MOS'});
        Map<Id, Decimal> productIdToPriceMap = new Map<Id, Decimal>();
        for(Id productId : mapProduct.values()){
            productIdToPriceMap.put(productId, 10); 
        }
        Map<Id, Id> mapPBE = ClsTestDataFactory.createCustomPricebookEntriesCA(productIdToPriceMap, mapPriceBook.get('CAN G6 SUBSCRIPTION 12MOS NO Renewal'));
        List<PricebookEntry> lstPBE = [SELECT Id, Pricebook2Id, Product2Id FROM PricebookEntry WHERE Pricebook2.Name = 'CAN G6 SUBSCRIPTION 12MOS NO Renewal'];
        List<Account> accountList= new List<Account>();
        Date renwalDate= date.today().adddays(90);
        Account testAccount = TestUtils.testCAConsumerAccount();
        testAccount.PersonEmail='jane.smith@sundog.net';
        testAccount.Email_Opt_In_Method__c = 'Via Email';
        insert testAccount;
        
        Product2 p = new product2();
        P.Name ='MTRNTCAGS-12MOS';
        //insert p;
        
        //for(Id ids : mapPBE.keySet()){
            SSIP_Rule__c ssip = new SSIP_Rule__c();
            ssip.Account__c=testAccount.Id;
            ssip.Rule_End_Date__c =renwalDate;
            ssip.product__c=lstPBE[0].Product2Id;
            ssip.Price_Book__c = lstPBE[0].Pricebook2Id;
            ssip.PriceBookEntryId__c = lstPBE[0].Id;
            ssip.Status__c='Active';
            insert ssip; 
       // }
        
        
        Test.startTest();
        Database.executeBatch(new BclsMarketingInteractionCARuleEndBatch(),200); 
        Test.stopTest();
    }
}