Prod-EU/force-app/main/default/objects/Account/fields/Fund__c.field-meta.xml
<CustomField>
    <fullName>Fund__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Fund the customer is associated to</description>
    <label>Fund</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 OR 3) AND 2</booleanFilter>
        <filterItems>
            <field>$Source.Payor__c</field>
            <operation>equals</operation>
            <valueField>Fund__c.Payor__c</valueField>
        </filterItems>
        <filterItems>
            <field>Fund__c.Is_Fund_Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>$Source.Id</field>
            <operation>equals</operation>
            <valueField>Fund__c.Payor__c</valueField>
        </filterItems>
        <infoMessage>Fund is not active.</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Fund__c</referenceTo>
    <relationshipLabel>Consumers</relationshipLabel>
    <relationshipName>Funds</relationshipName>
    <type>Lookup</type>
</CustomField>

Prod-EU/force-app/main/default/objects/Account/fields/Payor__c.field-meta.xml
<CustomField>
    <fullName>Payor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Payor tied to the Benefit record</description>
    <label>Payor</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>contains</operation>
            <value>Payor</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Accounts (Payor)</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

Prod-EU/force-app/main/default/objects/Account_Fund__c/Account_Fund__c.object-meta.xml
<CustomObject>
    <description>Junction object between Account and Fund objects. 
This object will be used to maintain the Account to Fund relationships.</description>
    <label>Account Fund</label>
    <nameField>
        <displayFormat>AFN-{0000}</displayFormat>
        <label>Account Fund Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Fund</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Prod-EU/force-app/main/default/objects/Account_Fund__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Related Funds</relationshipLabel>
    <relationshipName>Related_Funds</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Prod-EU/force-app/main/default/objects/Account_Fund__c/fields/Fund__c.field-meta.xml
<CustomField>
    <fullName>Fund__c</fullName>
    <label>Fund</label>
    <referenceTo>Fund__c</referenceTo>
    <relationshipLabel>Related Consumers</relationshipLabel>
    <relationshipName>Related_Accounts</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Prod-EU/force-app/main/default/objects/Account_Fund__c/fields/Primary_Flag__c.field-meta.xml
<CustomField>
    <fullName>Primary_Flag__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Primary Flag</label>
    <type>Checkbox</type>
</CustomField>

Prod-EU/force-app/main/default/objects/Fund__c/Fund__c.object-meta.xml
<CustomObject>
    <description>Object will track information related to Funded Patients.</description>
    <label>Fund</label>
    <nameField>
        <displayFormat>F-{00000}</displayFormat>
        <label>Fund Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fund</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Prod-EU/force-app/main/default/objects/Fund__c/fields/Amount_Limit__c.field-meta.xml
<CustomField>
    <fullName>Amount_Limit__c</fullName>
    <description>Amount limit enforced in PO</description>
    <label>Amount Limit</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

Prod-EU/force-app/main/default/objects/Fund__c/fields/Auth_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Auth_End_Date__c</fullName>
    <description>Date when the authorization ends</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Auth End Date</label>
    <type>Date</type>
</CustomField>

Prod-EU/force-app/main/default/objects/Fund__c/fields/Auth_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Auth_Start_Date__c</fullName>
    <defaultValue>Today()</defaultValue>
    <description>Date when the authorization starts</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Auth Start Date</label>
    <type>Date</type>
</CustomField>

Prod-EU/force-app/main/default/objects/Fund__c/fields/Limit_Type__c.field-meta.xml
<CustomField>
    <fullName>Limit_Type__c</fullName>
    <description>Type of limit enforce in PO</description>
    <label>Limit Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Quantity</fullName>
            </value>
            <value>
                <fullName>Amount</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Prod-EU/force-app/main/default/objects/Fund__c/fields/Payor__c.field-meta.xml
<CustomField>
    <fullName>Payor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Fund associated with the Payor.</description>
    <label>Payor</label>
    <lookupFilter>
        <active>false</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <errorMessage>Fund Payor should be of Payor type if using GBP or EUR. Otherwise Fund Currency should be in USD.</errorMessage>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>contains</operation>
            <value>Payor</value>
        </filterItems>
        <filterItems>
            <field>$Source.CurrencyIsoCode</field>
            <operation>equals</operation>
            <value>USD</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Fund (Payor)</relationshipLabel>
    <relationshipName>Payor_Fund</relationshipName>
    <type>Lookup</type>
</CustomField>

Prod-EU/force-app/main/default/objects/Fund__c/fields/PO_Reference_Number__c.field-meta.xml
<CustomField>
    <fullName>PO_Reference_Number__c</fullName>
    <description>Tracks the PO Number</description>
    <encryptionScheme>None</encryptionScheme>
    <label>PO Reference Number</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

Prod-EU/force-app/main/default/objects/Fund__c/fields/Receiver_Qty_Limit__c.field-meta.xml
<CustomField>
    <fullName>Receiver_Qty_Limit__c</fullName>
    <description>Qty of Receivers that can be used within the Authorized period</description>
    <label>Receiver Qty Limit</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Prod-EU/force-app/main/default/objects/Fund__c/fields/Sensor_Limit__c.field-meta.xml
<CustomField>
    <fullName>Sensor_Limit__c</fullName>
    <description>Qty of Sensors that can be used within the Authorized period</description>
    <label>Sensor Qty Limit</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Prod-EU/force-app/main/default/objects/Fund__c/fields/Succeeding_Fund__c.field-meta.xml
<CustomField>
    <fullName>Succeeding_Fund__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Succeeding Fund</label>
    <referenceTo>Fund__c</referenceTo>
    <relationshipLabel>Fund</relationshipLabel>
    <relationshipName>Fund</relationshipName>
    <type>Lookup</type>
</CustomField>

Prod-EU/force-app/main/default/objects/Fund__c/fields/Transmitter_Qty_Limit__c.field-meta.xml
<CustomField>
    <fullName>Transmitter_Qty_Limit__c</fullName>
    <description>Qty of Transmitters that can be used within the Authorized period</description>
    <label>Transmitter Qty Limit</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Prod-EU/force-app/main/default/objects/Fund__c/recordTypes/Purchase_Order.recordType-meta.xml
<RecordType>
    <fullName>Purchase_Order</fullName>
    <active>true</active>
    <description>Purchase Order Recordtype to track the Funds</description>
    <label>Purchase Order</label>
</RecordType>

Prod-EU/force-app/main/default/classes/ClsFundTriggerHandler_Test.cls
@isTest()
private class ClsFundTriggerHandler_Test {
    @isTest private static void test(){
        Account payorAccount = ClsTestDataFactory.createAccountsWithBillingAddress(1, 'DE Payor', 'Germany')[0];
        Fund__c fund = new Fund__c(Payor__c = payorAccount.Id, Amount_Limit__c = 100000, Auth_End_Date__c = Date.today().addDays(100), Auth_Start_Date__c = Date.today(), 
                                   Receiver_Qty_Limit__c = 100, Sensor_Limit__c = 100, Transmitter_Qty_Limit__c = 100);
        insert fund;
    }
    
    @isTest static void TestFundTriggerHandler(){
       List<Account> lstGBAcc = ClsTestDataFactory.createAccountsWithBillingAddress(2, 'GB Consumer', 'United Kingdom');
      Account payorAccount = ClsTestDataFactory.createAccountsWithBillingAddress(1, 'GB Payor', 'United Kingdom')[0];
        Recordtype recType=[select id from recordtype where developername='Purchase_Order'];
        Fund__c Fd = new Fund__c();
        Fd.PO_Reference_Number__c ='87666787';
        Fd.Limit_Type__c ='Quantity';        
        Fd.Payor__c = payorAccount.Id;
        Fd.Amount_Limit__c = 100000;
        Fd.Auth_End_Date__c = Date.today().addDays(100);
        Fd.Auth_Start_Date__c = Date.today();
        Fd.Receiver_Qty_Limit__c = 100; 
        Fd.Sensor_Limit__c = 100; 
        Fd.Transmitter_Qty_Limit__c = 100 ;     
        fd.recordtypeid=recType.id;
        insert Fd ;
        
        Fund__c Fd1 = new Fund__c();
        Fd1.PO_Reference_Number__c ='87666711';
        Fd1.Limit_Type__c ='Quantity';        
        Fd1.Payor__c = payorAccount.Id;
        Fd1.Amount_Limit__c = 100000;
        Fd1.Auth_End_Date__c = Date.today().addDays(100);
        Fd1.Auth_Start_Date__c = Date.today();
        Fd1.Receiver_Qty_Limit__c = 100; 
        Fd1.Sensor_Limit__c = 100; 
        Fd1.Transmitter_Qty_Limit__c = 100 ;
        fd1.recordtypeid=recType.id;        
        insert Fd1 ;
        lstGBAcc[0].fund__C=fd.id;
        Account_Fund__c af= new Account_Fund__c(Account__c=lstGBAcc[0].Id, Fund__c=fd.Id, Primary_Flag__c=true);        
        insert af;
        Account_Fund__c af1= new Account_Fund__c(Account__c=lstGBAcc[1].Id, Fund__c=fd.Id, Primary_Flag__c=true);        
        insert af1;
        Account_Fund__c af2= new Account_Fund__c(Account__c=lstGBAcc[0].Id, Fund__c=fd1.Id, Primary_Flag__c=false);        
        insert af2;
        
        
        
        
        test.starttest();
          fd.Succeeding_Fund__c=fd1.id;
          update fd;
        test.stoptest();
    }
}