Prod-EU/force-app/main/default/objects/Account/fields/Fund__c.field-meta.xml
<CustomField>
    <fullName>Fund__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Fund the customer is associated to</description>
    <label>Fund</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 OR 3) AND 2</booleanFilter>
        <filterItems>
            <field>$Source.Payor__c</field>
            <operation>equals</operation>
            <valueField>Fund__c.Payor__c</valueField>
        </filterItems>
        <filterItems>
            <field>Fund__c.Is_Fund_Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>$Source.Id</field>
            <operation>equals</operation>
            <valueField>Fund__c.Payor__c</valueField>
        </filterItems>
        <infoMessage>Fund is not active.</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Fund__c</referenceTo>
    <relationshipLabel>Consumers</relationshipLabel>
    <relationshipName>Funds</relationshipName>
    <type>Lookup</type>
</CustomField>

Prod-EU/force-app/main/default/objects/Account/fields/Payor__c.field-meta.xml
<CustomField>
    <fullName>Payor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Payor tied to the Benefit record</description>
    <label>Payor</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>contains</operation>
            <value>Payor</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Accounts (Payor)</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

Prod-EU/force-app/main/default/objects/Fund__c/Fund__c.object-meta.xml
<CustomObject>
    <description>Object will track information related to Funded Patients.</description>
    <label>Fund</label>
    <nameField>
        <displayFormat>F-{00000}</displayFormat>
        <label>Fund Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fund</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Prod-EU/force-app/main/default/objects/Fund__c/fields/Payor__c.field-meta.xml
<CustomField>
    <fullName>Payor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Fund associated with the Payor.</description>
    <label>Payor</label>
    <lookupFilter>
        <active>false</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <errorMessage>Fund Payor should be of Payor type if using GBP or EUR. Otherwise Fund Currency should be in USD.</errorMessage>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>contains</operation>
            <value>Payor</value>
        </filterItems>
        <filterItems>
            <field>$Source.CurrencyIsoCode</field>
            <operation>equals</operation>
            <value>USD</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Fund (Payor)</relationshipLabel>
    <relationshipName>Payor_Fund</relationshipName>
    <type>Lookup</type>
</CustomField>

Prod-EU/force-app/main/default/objects/Fund__c/fields/Succeeding_Fund__c.field-meta.xml
<CustomField>
    <fullName>Succeeding_Fund__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Succeeding Fund</label>
    <referenceTo>Fund__c</referenceTo>
    <relationshipLabel>Fund</relationshipLabel>
    <relationshipName>Fund</relationshipName>
    <type>Lookup</type>
</CustomField>

Prod-EU/force-app/main/default/objects/Fund__c/recordTypes/Purchase_Order.recordType-meta.xml
<RecordType>
    <fullName>Purchase_Order</fullName>
    <active>true</active>
    <description>Purchase Order Recordtype to track the Funds</description>
    <label>Purchase Order</label>
</RecordType>

Prod-EU/force-app/main/default/classes/ClsFundTriggerHandler.cls
public class ClsFundTriggerHandler {
    public void onBeforeInsert(List<Fund__c> lstFund){
        //Set the Currency Code on the Fund upon insert
        Set<Id> setAccountId = new Set<Id>();
        for(Fund__c fund : lstFund) setAccountId.add(fund.Payor__c);
        Map<Id, Account> mapAccount = new Map<Id, Account>([SELECT Id, RecordType.DeveloperName FROM Account WHERE Id IN: setAccountId]);
        for(Fund__c fund : lstFund){
            String recordTypeDName = mapAccount.get(fund.Payor__c).RecordType.DeveloperName;
            String currencyCode = recordTypeDName.startsWithIgnoreCase('CA_') ? 'CAD' : recordTypeDName.startsWithIgnoreCase('CH_') ? 'CHF' : 
                                  recordTypeDName.startsWithIgnoreCase('GB_') ? 'GBP' : recordTypeDName.startsWithIgnoreCase('IE_') ? 'EUR' : 
                                  recordTypeDName.startsWithIgnoreCase('INTL_') ? 'USD' : 'EUR';
            if(String.isNotBlank(currencyCode) && String.isNotEmpty(currencyCode)) fund.CurrencyIsoCode = currencyCode;
        }
    }
    
    public void onAfterUpdate(List<Fund__C> newList,Map<id,Fund__C> oldMap){
        Id recordTypeId = Schema.SObjectType.Fund__c.getRecordTypeInfosByDeveloperName().get('Purchase_Order').getRecordTypeId();
        Map<Id,Id> mapOfFundToSuccFund=new Map<Id,Id>();
        //Prepare a map between the Fund and Succeeding fund to be passed on to the Batch class
        for(Fund__C fund:newList){
             system.debug('fund.Succeeding_Fund__c'+fund.Succeeding_Fund__c+'>>'+fund.recordtypeid+'<>'+recordTypeId);
             if(fund.Succeeding_Fund__c !=null && fund.recordtypeid==recordTypeId && fund.Succeeding_Fund__c != oldMap.get(fund.id).Succeeding_Fund__c){
                mapOfFundToSuccFund.put(fund.id,fund.Succeeding_Fund__c);
             }
        }
        if(!mapOfFundToSuccFund.isEmpty())
            database.executeBatch(new BclsHandleAccountFundBatch(mapOfFundToSuccFund),10);
    }
}