Prod-EU/force-app/main/default/objects/Account/fields/Fund__c.field-meta.xml
<CustomField>
    <fullName>Fund__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Fund the customer is associated to</description>
    <label>Fund</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 OR 3) AND 2</booleanFilter>
        <filterItems>
            <field>$Source.Payor__c</field>
            <operation>equals</operation>
            <valueField>Fund__c.Payor__c</valueField>
        </filterItems>
        <filterItems>
            <field>Fund__c.Is_Fund_Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>$Source.Id</field>
            <operation>equals</operation>
            <valueField>Fund__c.Payor__c</valueField>
        </filterItems>
        <infoMessage>Fund is not active.</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Fund__c</referenceTo>
    <relationshipLabel>Consumers</relationshipLabel>
    <relationshipName>Funds</relationshipName>
    <type>Lookup</type>
</CustomField>

Prod-EU/force-app/main/default/objects/Account/fields/Payor__c.field-meta.xml
<CustomField>
    <fullName>Payor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Payor tied to the Benefit record</description>
    <label>Payor</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>contains</operation>
            <value>Payor</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Accounts (Payor)</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

Prod-EU/force-app/main/default/objects/Account/fields/Price_Book__c.field-meta.xml
<CustomField>
    <fullName>Price_Book__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Price Book</label>
    <referenceTo>Pricebook2</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

Prod-EU/force-app/main/default/objects/Account_Fund__c/Account_Fund__c.object-meta.xml
<CustomObject>
    <description>Junction object between Account and Fund objects. 
This object will be used to maintain the Account to Fund relationships.</description>
    <label>Account Fund</label>
    <nameField>
        <displayFormat>AFN-{0000}</displayFormat>
        <label>Account Fund Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Fund</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Prod-EU/force-app/main/default/objects/Account_Fund__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Related Funds</relationshipLabel>
    <relationshipName>Related_Funds</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Prod-EU/force-app/main/default/objects/Account_Fund__c/fields/Fund__c.field-meta.xml
<CustomField>
    <fullName>Fund__c</fullName>
    <label>Fund</label>
    <referenceTo>Fund__c</referenceTo>
    <relationshipLabel>Related Consumers</relationshipLabel>
    <relationshipName>Related_Accounts</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Prod-EU/force-app/main/default/objects/Fund__c/Fund__c.object-meta.xml
<CustomObject>
    <description>Object will track information related to Funded Patients.</description>
    <label>Fund</label>
    <nameField>
        <displayFormat>F-{00000}</displayFormat>
        <label>Fund Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fund</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Prod-EU/force-app/main/default/objects/Fund__c/fields/Amount_Limit__c.field-meta.xml
<CustomField>
    <fullName>Amount_Limit__c</fullName>
    <description>Amount limit enforced in PO</description>
    <label>Amount Limit</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

Prod-EU/force-app/main/default/objects/Fund__c/fields/Auth_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Auth_End_Date__c</fullName>
    <description>Date when the authorization ends</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Auth End Date</label>
    <type>Date</type>
</CustomField>

Prod-EU/force-app/main/default/objects/Fund__c/fields/Auth_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Auth_Start_Date__c</fullName>
    <defaultValue>Today()</defaultValue>
    <description>Date when the authorization starts</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Auth Start Date</label>
    <type>Date</type>
</CustomField>

Prod-EU/force-app/main/default/objects/Fund__c/fields/Limit_Type__c.field-meta.xml
<CustomField>
    <fullName>Limit_Type__c</fullName>
    <description>Type of limit enforce in PO</description>
    <label>Limit Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Quantity</fullName>
            </value>
            <value>
                <fullName>Amount</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Prod-EU/force-app/main/default/objects/Fund__c/fields/Payor__c.field-meta.xml
<CustomField>
    <fullName>Payor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Fund associated with the Payor.</description>
    <label>Payor</label>
    <lookupFilter>
        <active>false</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <errorMessage>Fund Payor should be of Payor type if using GBP or EUR. Otherwise Fund Currency should be in USD.</errorMessage>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>contains</operation>
            <value>Payor</value>
        </filterItems>
        <filterItems>
            <field>$Source.CurrencyIsoCode</field>
            <operation>equals</operation>
            <value>USD</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Fund (Payor)</relationshipLabel>
    <relationshipName>Payor_Fund</relationshipName>
    <type>Lookup</type>
</CustomField>

Prod-EU/force-app/main/default/objects/Fund__c/fields/PO_Reference_Number__c.field-meta.xml
<CustomField>
    <fullName>PO_Reference_Number__c</fullName>
    <description>Tracks the PO Number</description>
    <encryptionScheme>None</encryptionScheme>
    <label>PO Reference Number</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

Prod-EU/force-app/main/default/objects/Fund__c/fields/Receiver_Qty_Limit__c.field-meta.xml
<CustomField>
    <fullName>Receiver_Qty_Limit__c</fullName>
    <description>Qty of Receivers that can be used within the Authorized period</description>
    <label>Receiver Qty Limit</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Prod-EU/force-app/main/default/objects/Fund__c/fields/Receiver_Qty_Used__c.field-meta.xml
<CustomField>
    <fullName>Receiver_Qty_Used__c</fullName>
    <description>Total number of receiver qty used within the authorized time frame</description>
    <label>Receiver Qty Used</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Prod-EU/force-app/main/default/objects/Fund__c/fields/Sensor_Limit__c.field-meta.xml
<CustomField>
    <fullName>Sensor_Limit__c</fullName>
    <description>Qty of Sensors that can be used within the Authorized period</description>
    <label>Sensor Qty Limit</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Prod-EU/force-app/main/default/objects/Fund__c/fields/Succeeding_Fund__c.field-meta.xml
<CustomField>
    <fullName>Succeeding_Fund__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Succeeding Fund</label>
    <referenceTo>Fund__c</referenceTo>
    <relationshipLabel>Fund</relationshipLabel>
    <relationshipName>Fund</relationshipName>
    <type>Lookup</type>
</CustomField>

Prod-EU/force-app/main/default/objects/Fund__c/fields/Transmitter_Qty_Limit__c.field-meta.xml
<CustomField>
    <fullName>Transmitter_Qty_Limit__c</fullName>
    <description>Qty of Transmitters that can be used within the Authorized period</description>
    <label>Transmitter Qty Limit</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Prod-EU/force-app/main/default/objects/Fund__c/fields/Transmitter_Qty_Used__c.field-meta.xml
<CustomField>
    <fullName>Transmitter_Qty_Used__c</fullName>
    <description>Total number of transmitter qty used within the authorized time frame</description>
    <label>Transmitter Qty Used</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Prod-EU/force-app/main/default/objects/Fund__c/recordTypes/Purchase_Order.recordType-meta.xml
<RecordType>
    <fullName>Purchase_Order</fullName>
    <active>true</active>
    <description>Purchase Order Recordtype to track the Funds</description>
    <label>Purchase Order</label>
</RecordType>

Prod-EU/force-app/main/default/classes/ClsTestFundObject.cls
/*******************************************************************************************
@Author        : Kumar Navneet
@Date Created    : 08/13/2019
@Description    : Test class to test the scenarios involved in Fund object
*********************************************************************************************/
@isTest
private class ClsTestFundObject {
    
    @isTest static void TestOrderFundCreationAndUpdate(){
        //Insert 1 consumer account record
        List<Account> consumerAccts = ClsTestDataFactory.createAccountsWithBillingAddress(1, 'GB Consumer', 'United Kingdom');
        Account payorAccount = ClsTestDataFactory.createAccountsWithBillingAddress(1, 'GB Payor', 'United Kingdom')[0];
        
        //Create Pricebook
        Map<String, Id> customPricebookMap = ClsTestDataFactory.createCustomPricebook(new List <String>{'GB Cash'});
        String customPricebookId = customPricebookMap.get('GB Cash');
        
        //Create Products
        Map<String, Id> products = ClsTestDataFactory.createProducts(new List<String> {'STK-GF-013', 'STT-GF-004', 'DEX-SHIP-01','FREIGHT CHARGE'});
        
        //Update the virtual sku productIdToPbeId
        Product2 virtualProd = [SELECT Id, Is_Virtual_Product__c FROM Product2 WHERE NAME = 'DEX-SHIP-01'];
        virtualProd.Is_Virtual_Product__c = true;
        update virtualProd;
        
        //Create Pricebook EntryPair
        Map<Id, Decimal> productIdToPriceMap = new Map<Id, Decimal>();
        for(String productName : products.keySet())
        {
            productIdToPriceMap.put(products.get(productName), 125.00);
            
        }
        
        
        Fund__c Fd = new Fund__c();
        Fd.PO_Reference_Number__c ='87666787';
        Fd.Limit_Type__c ='Quantity';        
        Fd.Payor__c = payorAccount.Id;
        Fd.Amount_Limit__c = 100000;
        Fd.Auth_End_Date__c = Date.today().addDays(100);
        Fd.Auth_Start_Date__c = Date.today();
        Fd.Receiver_Qty_Limit__c = 100; 
        Fd.Sensor_Limit__c = 100; 
        Fd.Transmitter_Qty_Limit__c = 100 ;
        fd.Receiver_Qty_Used__c=50;
        fd.Transmitter_Qty_Used__c=10;
        
        insert Fd ; 
        
        Map<Id, Id> productIdToPbeId = ClsTestDataFactory.CreateCPBEntries(productIdToPriceMap, customPricebookId, 'GBP');
        Id chOrderRecdTypeId = Schema.SObjectType.Order.getRecordTypeInfosByDeveloperName().get('GB_Sales_Order').getRecordTypeId();
        payorAccount.Price_Book__c = customPricebookId;   
        update payorAccount ;
        
        //Create Order record
        ClsOrderTriggerStaticClass.isExecuting = false;
        Order newOrder = new Order();
        newOrder.AccountId = consumerAccts[0].Id;
        newOrder.RecordtypeId = chOrderRecdTypeId;
        newOrder.Type = 'GB STANDARD';
        newOrder.EffectiveDate = System.today();
        newOrder.Price_Book__c = customPricebookId;       
        newOrder.Status = 'Draft';
        newOrder.Payor__c = payorAccount.Id ;
        newOrder.Fund__c = Fd.id; 
        insert newOrder;
        
        newOrder.Pricebook2Id = customPricebookId; 
        update newOrder;
        
        
        //List order line items
        List<OrderItem> orderItemList = new List<OrderItem>();
        for(Id pbeId : productIdToPbeId.values())
        {
            OrderItem oi = new OrderItem();
            oi.OrderId = newOrder.Id;
            oi.PricebookEntryId = pbeId;
            oi.Quantity = 1;
            oi.UnitPrice = 125.00;
            oi.Tracking_Number__c = '12345';
            oi.Product_Name__c = 'STK-GF-109' ;
            orderItemList.add(oi);
        }
        insert orderItemList;
        
        //Update tracking number information
        ClsOrderTriggerStaticClass.isExecuting = false;
        OrderItem newOrderItem = [SELECT Id, Tracking_Number__c,Product_Name__c FROM OrderItem WHERE Id = : orderItemList[0].Id];
        system.debug('********product name is ' +newOrderItem.Product_Name__c);
        newOrderItem.Tracking_Number__c = '123456|10';
        newOrderItem.Serial_Number__c = 'SM1236547';
        update newOrderItem;
        Test.startTest();
        //  ClsFundService clsfd =new ClsFundService();
        ClsFundService.getPONumber(Fd.id);
         ClsFundService.chargeFund(newOrder.id);         
        ClsFundService.checkFundBalance(newOrder.id);
		Test.stopTest();
       
    }
    
     @isTest static void TestOrderSuccedingFundBatch(){
        List<Account> consumerAccts = ClsTestDataFactory.createAccountsWithBillingAddress(2, 'GB Consumer', 'United Kingdom');
        Account payorAccount = ClsTestDataFactory.createAccountsWithBillingAddress(1, 'GB Payor', 'United Kingdom')[0];
        RecordType recId=[select id from recordtype where developername='Purchase_Order' limit 1];
        List<Fund__C> listFund=new List<Fund__C>();
        Fund__c Fd = new Fund__c();
        Fd.PO_Reference_Number__c ='87666787';
        Fd.Limit_Type__c ='Quantity';        
        Fd.Payor__c = payorAccount.Id;
        Fd.Amount_Limit__c = 100000;
        Fd.Auth_End_Date__c = Date.today().addDays(100);
        Fd.Auth_Start_Date__c = Date.today();
        Fd.Receiver_Qty_Limit__c = 100; 
        Fd.Sensor_Limit__c = 100; 
        Fd.Transmitter_Qty_Limit__c = 100 ;
        fd.Receiver_Qty_Used__c=50;
        fd.Transmitter_Qty_Used__c=10;
        fd.recordtypeId=recId.id;
        listFund.add(fd);
        
        Fund__c Fd1 = new Fund__c();
        fd1.PO_Reference_Number__c ='87666788';
        fd1.Limit_Type__c ='Quantity';        
        fd1.Payor__c = payorAccount.Id;
        fd1.recordtypeId=recId.id;
        fd1.Amount_Limit__c = 100000;
        fd1.Auth_End_Date__c = Date.today().addDays(100);
        fd1.Auth_Start_Date__c = Date.today();
        fd1.Receiver_Qty_Limit__c = 100; 
        fd1.Sensor_Limit__c = 100; 
        fd1.Transmitter_Qty_Limit__c = 100 ;
        fd1.Receiver_Qty_Used__c=50;
        fd1.Transmitter_Qty_Used__c=10;
        listFund.add(fd1);
        insert listFund;
        List<Account_Fund__C> aflist=new List<Account_Fund__C>();
                     
        Account_Fund__C af=new Account_Fund__C();
        af.account__C=consumerAccts[0].id;
        af.Fund__C=fd.id;
        aflist.add(af);
        Account_Fund__C af1=new Account_Fund__C();
        af1.account__C=consumerAccts[1].id;
        af1.Fund__C=fd.id;
        aflist.add(af1);
        insert aflist;

        //consumerAccts[0].fund__C=fd.id;
        //update consumerAccts[0];
        test.startTest();
         fd.succeeding_fund__c=fd1.id;
         update fd;
        Test.stoptest();
        
     }
}