Prod-EU/force-app/main/default/objects/Account/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <label>Gender</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Gender</valueSetName>
    </valueSet>
</CustomField>

Prod-EU/force-app/main/default/objects/Account/fields/IQVIA_OneKeyId__c.field-meta.xml
<CustomField>
    <fullName>IQVIA_OneKeyId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>Contains unique IQVIA OneKey identifier</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>OneKey Id</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Prod-EU/force-app/main/default/objects/Account/fields/Medical_Facility__c.field-meta.xml
<CustomField>
    <fullName>Medical_Facility__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Medical Facility</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>contains</operation>
            <value>Facility</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Medical Facilities</relationshipLabel>
    <relationshipName>Medical_Facilities</relationshipName>
    <type>Lookup</type>
</CustomField>

Prod-EU/force-app/main/default/objects/Account/fields/OK_Ind_Type__c.field-meta.xml
<CustomField>
    <fullName>OK_Ind_Type__c</fullName>
    <description>OneKey - Picklist Code = TYP</description>
    <label>Ind. Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Administrator</fullName>
            </value>
            <value>
                <fullName>Researcher/Scientist</fullName>
            </value>
            <value>
                <fullName>Counselor/Social worker</fullName>
            </value>
            <value>
                <fullName>Dentist</fullName>
            </value>
            <value>
                <fullName>Dental Assistant</fullName>
            </value>
            <value>
                <fullName>Nurse</fullName>
            </value>
            <value>
                <fullName>Physical Therapist</fullName>
            </value>
            <value>
                <fullName>Laboratory technician</fullName>
            </value>
            <value>
                <fullName>Physician</fullName>
            </value>
            <value>
                <fullName>Medical Assistant</fullName>
            </value>
            <value>
                <fullName>Optician</fullName>
            </value>
            <value>
                <fullName>Optometrist</fullName>
            </value>
            <value>
                <fullName>Pharmacist</fullName>
            </value>
            <value>
                <fullName>Dental Prosthetist</fullName>
            </value>
            <value>
                <fullName>Pharmacy technician</fullName>
            </value>
            <value>
                <fullName>Pharmacist Assistant / Technician</fullName>
            </value>
            <value>
                <fullName>Allied Health Professionals</fullName>
            </value>
            <value>
                <fullName>Midwife</fullName>
            </value>
            <value>
                <fullName>Technician/Technologist</fullName>
            </value>
            <value>
                <fullName>Veterinarian</fullName>
            </value>
            <value>
                <fullName>Veterinary Assistant</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Prod-EU/force-app/main/default/objects/Account/fields/OK_Main_Category__c.field-meta.xml
<CustomField>
    <fullName>OK_Main_Category__c</fullName>
    <description>OneKey - Picklist Code = LEX</description>
    <label>Main Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pharmacy/Wholesaler</fullName>
            </value>
            <value>
                <fullName>Hospital</fullName>
            </value>
            <value>
                <fullName>Supplying Medical Center</fullName>
            </value>
            <value>
                <fullName>Practice</fullName>
            </value>
            <value>
                <fullName>Other Institution</fullName>
            </value>
            <value>
                <fullName>Home Address</fullName>
            </value>
            <value>
                <fullName>Miscellaneous</fullName>
            </value>
            <value>
                <fullName>Academic Institution</fullName>
            </value>
            <value>
                <fullName>Medical Health Teams</fullName>
            </value>
            <value>
                <fullName>Long Term Care Facility</fullName>
            </value>
            <value>
                <fullName>Medical Center</fullName>
            </value>
            <value>
                <fullName>Private Address</fullName>
            </value>
            <value>
                <fullName>Laboratory</fullName>
            </value>
            <value>
                <fullName>Clinic</fullName>
            </value>
            <value>
                <fullName>Health Insurance</fullName>
            </value>
            <value>
                <fullName>Government Body</fullName>
            </value>
            <value>
                <fullName>Administrative Institution</fullName>
            </value>
            <value>
                <fullName>Medical Health Network</fullName>
            </value>
            <value>
                <fullName>Dental Practice</fullName>
            </value>
            <value>
                <fullName>Single Practice</fullName>
            </value>
            <value>
                <fullName>Group Practice</fullName>
            </value>
            <value>
                <fullName>Association</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Prod-EU/force-app/main/default/objects/Account/fields/OK_Specialty_1__c.field-meta.xml
<CustomField>
    <fullName>OK_Specialty_1__c</fullName>
    <description>OneKey - Picklist Code = SP</description>
    <label>Specialty 1</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>General Medicine</fullName>
            </value>
            <value>
                <fullName>Anatomical Pathology</fullName>
            </value>
            <value>
                <fullName>Anaesthesiology</fullName>
            </value>
            <value>
                <fullName>Homeopathy</fullName>
            </value>
            <value>
                <fullName>Gastroenterology</fullName>
            </value>
            <value>
                <fullName>Biochemistry</fullName>
            </value>
            <value>
                <fullName>Cardiology</fullName>
            </value>
            <value>
                <fullName>Abdominal / Digestive  Surgery</fullName>
            </value>
            <value>
                <fullName>HIV Medicine</fullName>
            </value>
            <value>
                <fullName>Lesion Care</fullName>
            </value>
            <value>
                <fullName>Cardiovascular/Vascular Surgery</fullName>
            </value>
            <value>
                <fullName>General Surgery</fullName>
            </value>
            <value>
                <fullName>Oral Surgery</fullName>
            </value>
            <value>
                <fullName>Child Surgery</fullName>
            </value>
            <value>
                <fullName>Thoracic Surgery</fullName>
            </value>
            <value>
                <fullName>Plastic Surgery</fullName>
            </value>
            <value>
                <fullName>Dermatology</fullName>
            </value>
            <value>
                <fullName>Social Paediatrics</fullName>
            </value>
            <value>
                <fullName>Endocrinology</fullName>
            </value>
            <value>
                <fullName>Veterinary</fullName>
            </value>
            <value>
                <fullName>Psychology</fullName>
            </value>
            <value>
                <fullName>Laboratory</fullName>
            </value>
            <value>
                <fullName>Dialysis Center - big -</fullName>
            </value>
            <value>
                <fullName>Lasercenter</fullName>
            </value>
            <value>
                <fullName>Physiology</fullName>
            </value>
            <value>
                <fullName>Pharmaceutical Commercial Assistant</fullName>
            </value>
            <value>
                <fullName>Pharmaceutical Engineer</fullName>
            </value>
            <value>
                <fullName>Gynaeco Oncology</fullName>
            </value>
            <value>
                <fullName>Hospital Pharmacy</fullName>
            </value>
            <value>
                <fullName>Geriatrics</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Prod-EU/force-app/main/default/classes/ClsValRequestAccountTriggerHandlerTest.cls
@isTest
public class ClsValRequestAccountTriggerHandlerTest {
    @isTest(SeeAllData=true)
    public Static void createValidationRequestActivity(){
        Test.enableChangeDataCapture();
        Account acc =  [SELECT Id,FirstName,MiddleName,Salutation,PersonTitle,Gender__c,OK_Ind_Type__c,
                        LastName,OK_Specialty_1__c,Medical_Facility__r.Name,OK_Main_Category__c,ShippingStreet,ShippingCity,ShippingPostalCode,ShippingState FROM Account WHERE FirstName = 'NO' AND LastName = 'PRESCRIBER' AND Country__c = 'Germany' LIMIT 1];
        acc.IQVIA_OneKeyId__c = 'W87876';
        acc.FirstName = 'NO - Modified';
        Test.startTest();
        update acc;
        Test.stopTest();
    }
}