Prod-EU/force-app/main/default/objects/Account/fields/IQVIA_OneKeyId__c.field-meta.xml
<CustomField>
    <fullName>IQVIA_OneKeyId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>Contains unique IQVIA OneKey identifier</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>OneKey Id</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Prod-EU/force-app/main/default/objects/Account/fields/OK_Status__c.field-meta.xml
<CustomField>
    <fullName>OK_Status__c</fullName>
    <description>OneKey - Picklist Code = STA</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Provisional</fullName>
            </value>
            <value>
                <fullName>Valid</fullName>
            </value>
            <value>
                <fullName>Invalid</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Prod-EU/force-app/main/default/objects/Related_Account__c/Related_Account__c.object-meta.xml
<CustomObject>
    <description>Jagan 04/25/2017 - Object holds many to many relationship between Accounts.</description>
    <label>Related Account</label>
    <nameField>
        <displayFormat>RA-{00000}</displayFormat>
        <label>Relation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Related Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Prod-EU/force-app/main/default/objects/Related_Account__c/fields/Child_Account__c.field-meta.xml
<CustomField>
    <fullName>Child_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Field holds the child account (Prescriber) information</description>
    <label>Child Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>contains</operation>
            <value>Prescriber, Facility, Pharmacy</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Linked Accounts</relationshipLabel>
    <relationshipName>Related_Child_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

Prod-EU/force-app/main/default/objects/Related_Account__c/fields/IQVIA_OneKeyId__c.field-meta.xml
<CustomField>
    <fullName>IQVIA_OneKeyId__c</fullName>
    <description>OneKey - Records OneKey Id</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>OneKey Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

Prod-EU/force-app/main/default/objects/Related_Account__c/fields/OK_Status__c.field-meta.xml
<CustomField>
    <fullName>OK_Status__c</fullName>
    <description>OneKey - Status like Valid, Invalid, Provisional</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Provisional</fullName>
            </value>
            <value>
                <fullName>Valid</fullName>
            </value>
            <value>
                <fullName>Invalid</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Prod-EU/force-app/main/default/objects/Related_Account__c/fields/Parent_Child_Id__c.field-meta.xml
<CustomField>
    <fullName>Parent_Child_Id__c</fullName>
    <description>Concatenates the child and parent account ids</description>
    <formula>Child_Account__c +&apos;-&apos;+  Parent_Account__c</formula>
    <label>Parent Child Id</label>
    <type>Text</type>
</CustomField>

Prod-EU/force-app/main/default/classes/BClsClearDuplicateChildAccounts.cls
/*****************************************************************************************************************
@Author        : Jagan Periyakaruppan
@Date Modified    : 09/02/2020
@Description    : This Batch class will be invoked on a regular interval to clear out the duplicate related accounts
					that were created as part of OneKey Implementation
********************************************************************************************************************/ 
global class BClsClearDuplicateChildAccounts implements Database.Batchable<sobject>{
    //Get all the child accounts, which are created by Veeva
    global Database.QueryLocator start(Database.BatchableContext BC)
    {
        String query = 'SELECT Id, Parent_Child_Id__c, OK_Status__c FROM Related_Account__c WHERE (IQVIA_OneKeyId__c = null OR OK_Status__c = \'Invalid\') AND Child_Account__r.Recordtype.Name IN (\'DE Prescriber\', \'DE Medical Facility\', \'CA Prescriber\', \'CA Medical Facility\')';
        //String query = 'SELECT Id, Parent_Child_Id__c, OK_Status__c FROM Related_Account__c WHERE (IQVIA_OneKeyId__c = null OR OK_Status__c = \'Invalid\') AND Child_Account__r.Recordtype.Name IN (\'DE Prescriber\', \'DE Medical Facility\', \'CA Prescriber\', \'CA Medical Facility\') and Id in(\'a040Q000005LQIh\')';
        return Database.getQueryLocator(query);
    }
    
    //Execute the Account records in batch
    global void execute(Database.BatchableContext BC, List<Related_Account__c> childAccountsToBeDeletedList)
    {
        //List of Child acccounts to be deleted
        Map<Id, Related_Account__c> deleteChildAccounts = new Map<Id, Related_Account__c> ();
        Set<String> parentChildIdsToSearch = new Set<String>();
        Set<String> parentChildIdsFound = new Set<String>();
        
        for(Related_Account__c childAccount : childAccountsToBeDeletedList)
            parentChildIdsToSearch.add(childAccount.Parent_Child_Id__c);
        //Get all the child accounts that was populated by IQVIA
        for(Related_Account__c oneKeyChildAccnts : [SELECT Id, Parent_Child_Id__c FROM Related_Account__c WHERE IQVIA_OneKeyId__c != null AND Parent_Child_Id__c IN : parentChildIdsToSearch])
            parentChildIdsFound.add(oneKeyChildAccnts.Parent_Child_Id__c);

        for(Related_Account__c childAccount : childAccountsToBeDeletedList)
        {
            system.debug('****Id is ' + childAccount.Id);
            if(parentChildIdsFound.contains(childAccount.Parent_Child_Id__c) || childAccount.OK_Status__c == 'Invalid'){
                system.debug('****Found Id for delete ' + childAccount.Id);
                deleteChildAccounts.put(childAccount.Id, childAccount) ;
            }
        }
        //Delete the child accounts
        if(!deleteChildAccounts.isEmpty())
        {
            system.debug('Found accounts to delete');
            try{
                delete deleteChildAccounts.values();
            }catch (Exception e){
                system.debug('***CHILD ACCOUNTS CANNOT BE DELETED ERROR = ' + e.getMessage());
            }
        }
	}
    
    //Finish Method
    global void finish(Database.BatchableContext BC)
    {
      
    }
}