Prod-EU/force-app/main/default/objects/Account/fields/IQVIA_OneKeyId__c.field-meta.xml
<CustomField>
    <fullName>IQVIA_OneKeyId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>Contains unique IQVIA OneKey identifier</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>OneKey Id</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Prod-EU/force-app/main/default/objects/Account/fields/OK_Top_Level_Parent__c.field-meta.xml
<CustomField>
    <fullName>OK_Top_Level_Parent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Auto populates using Account Trigger before Insert</description>
    <label>Top Level Parent</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Accounts (Top Level Account)</relationshipLabel>
    <relationshipName>ChildAccount</relationshipName>
    <type>Lookup</type>
</CustomField>

Prod-EU/force-app/main/default/objects/Account/fields/OK_Top_Level_ParentID__c.field-meta.xml
<CustomField>
    <fullName>OK_Top_Level_ParentID__c</fullName>
    <formula>IF(NOT(ISBLANK(Parent.Parent.Parent.Parent.Parent.Name)), Parent.Parent.Parent.Parent.Parent.Id,
IF(NOT(ISBLANK(Parent.Parent.Parent.Parent.Name)), Parent.Parent.Parent.Parent.Id,
IF(NOT(ISBLANK(Parent.Parent.Parent.Name)), Parent.Parent.Parent.Id,
IF(NOT(ISBLANK(Parent.Parent.Name)), Parent.Parent.Id,
IF(NOT(ISBLANK(Parent.Name)),Parent.Id,
Id)))))</formula>
    <label>Top Level Parent ID</label>
    <type>Text</type>
</CustomField>

Prod-EU/force-app/main/default/classes/BclsUpdateTopParentAccount.cls
/****************************************************************************************************************
@Author        : Pradeep Sadasivan
@Date Created    : 25/08/2020
@Description    :Batch apex to update Top Parent Account on an Account- IQVIA requirement - NS-743
****************************************************************************************************************/
global class BclsUpdateTopParentAccount implements Database.Batchable <SObject> {
    global Database.QueryLocator start(Database.BatchableContext bc){
        String Query='Select id,ParentID,OK_Top_Level_Parent__c,OK_Top_Level_ParentID__c,IQVIA_OneKeyId__c from Account Where IQVIA_OneKeyId__c!=Null AND OK_Top_Level_ParentID__c != Null AND ParentID != Null';
        return Database.getQueryLocator(Query);
            }
    global void execute(Database.BatchableContext bc, List<Account> accList){
        List<Account> accountToUpdate = new List<Account>();
        if(!accList.isEmpty()){
        	for(Account acc: accList){
            	acc.OK_Top_Level_Parent__c= acc.OK_Top_Level_ParentID__c;
                accountToUpdate.add(acc);
            
        	}
        }
        if(!accountToUpdate.isEmpty()){ 
            Database.update(accountToUpdate, false);
        }
    }
    global void finish(Database.BatchableContext bc){
        Id job= bc.getJobId();
        System.debug(job);
    }
}