Prod-EU/force-app/main/default/objects/Account/fields/IQVIA_OneKeyId__c.field-meta.xml
<CustomField>
    <fullName>IQVIA_OneKeyId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>Contains unique IQVIA OneKey identifier</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>OneKey Id</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Prod-EU/force-app/main/default/objects/Account/fields/Preferred_Language__c.field-meta.xml
<CustomField>
    <fullName>Preferred_Language__c</fullName>
    <description>In some countries like Canada and Switzerland multiple languages are supported. This captures the preferred language of the Organization or Person.</description>
    <label>Preferred Language</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Preferred_Language</valueSetName>
    </valueSet>
</CustomField>

Prod-EU/force-app/main/default/objects/Address__c/Address__c.object-meta.xml
<CustomObject>
    <description>Created this custom object to track Address information.</description>
    <label>Address</label>
    <nameField>
        <displayFormat>A-{0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Prod-EU/force-app/main/default/objects/Address__c/fields/Address_Line_1__c.field-meta.xml
<CustomField>
    <fullName>Address_Line_1__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Straße, Hausnummer</inlineHelpText>
    <label>Address Line 1</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

Prod-EU/force-app/main/default/objects/Address__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>City</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

Prod-EU/force-app/main/default/objects/Address__c/fields/IQVIA_OneKeyId__c.field-meta.xml
<CustomField>
    <fullName>IQVIA_OneKeyId__c</fullName>
    <description>OneKey - Records OneKey Id</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>OneKey Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

Prod-EU/force-app/main/default/objects/Address__c/fields/Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Postal_Code__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Postal Code</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

Prod-EU/force-app/main/default/objects/Address__c/fields/Primary_Flag__c.field-meta.xml
<CustomField>
    <fullName>Primary_Flag__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Primary</label>
    <type>Checkbox</type>
</CustomField>

Prod-EU/force-app/main/default/objects/Address__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Bill To</fullName>
            </value>
            <value>
                <fullName>Ship To</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Prod-EU/force-app/main/default/objects/Sample_Order_Request_Event__e/Sample_Order_Request_Event__e.object-meta.xml
<CustomObject>
    <description>OCE to Salesforce</description>
    <label>Sample Order Request Event</label>
    <pluralLabel>Sample Order Request Events</pluralLabel>
</CustomObject>

Prod-EU/force-app/main/default/objects/Sample_Order_Request_Event__e/fields/AccCountryCode__c.field-meta.xml
<CustomField>
    <fullName>AccCountryCode__c</fullName>
    <label>AccCountryCode</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

Prod-EU/force-app/main/default/objects/Sample_Order_Request_Event__e/fields/AccountOnekeyId__c.field-meta.xml
<CustomField>
    <fullName>AccountOnekeyId__c</fullName>
    <label>AccountOnekeyId</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

Prod-EU/force-app/main/default/objects/Sample_Order_Request_Event__e/fields/AccountType__c.field-meta.xml
<CustomField>
    <fullName>AccountType__c</fullName>
    <label>AccountType</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

Prod-EU/force-app/main/default/objects/Sample_Order_Request_Event__e/fields/Address_Phone_Number__c.field-meta.xml
<CustomField>
    <fullName>Address_Phone_Number__c</fullName>
    <label>Address Phone Number</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

Prod-EU/force-app/main/default/objects/Sample_Order_Request_Event__e/fields/AddressLine1__c.field-meta.xml
<CustomField>
    <fullName>AddressLine1__c</fullName>
    <label>AddressLine1</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

Prod-EU/force-app/main/default/objects/Sample_Order_Request_Event__e/fields/AddressLine2__c.field-meta.xml
<CustomField>
    <fullName>AddressLine2__c</fullName>
    <label>AddressLine2</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

Prod-EU/force-app/main/default/objects/Sample_Order_Request_Event__e/fields/AddressLine3__c.field-meta.xml
<CustomField>
    <fullName>AddressLine3__c</fullName>
    <label>AddressLine3</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

Prod-EU/force-app/main/default/objects/Sample_Order_Request_Event__e/fields/AddressOneKeyId__c.field-meta.xml
<CustomField>
    <fullName>AddressOneKeyId__c</fullName>
    <label>AddressOneKeyId</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

Prod-EU/force-app/main/default/objects/Sample_Order_Request_Event__e/fields/BirthDate__c.field-meta.xml
<CustomField>
    <fullName>BirthDate__c</fullName>
    <label>BirthDate</label>
    <type>Date</type>
</CustomField>

Prod-EU/force-app/main/default/objects/Sample_Order_Request_Event__e/fields/CareOf_AddressFirstName__c.field-meta.xml
<CustomField>
    <fullName>CareOf_AddressFirstName__c</fullName>
    <label>CareOf AddressFirstName</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

Prod-EU/force-app/main/default/objects/Sample_Order_Request_Event__e/fields/CareOf_AddressLastName__c.field-meta.xml
<CustomField>
    <fullName>CareOf_AddressLastName__c</fullName>
    <label>CareOf AddressLastName</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

Prod-EU/force-app/main/default/objects/Sample_Order_Request_Event__e/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

Prod-EU/force-app/main/default/objects/Sample_Order_Request_Event__e/fields/FirstName__c.field-meta.xml
<CustomField>
    <fullName>FirstName__c</fullName>
    <label>FirstName</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

Prod-EU/force-app/main/default/objects/Sample_Order_Request_Event__e/fields/HomePhone__c.field-meta.xml
<CustomField>
    <fullName>HomePhone__c</fullName>
    <label>HomePhone</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

Prod-EU/force-app/main/default/objects/Sample_Order_Request_Event__e/fields/LastName__c.field-meta.xml
<CustomField>
    <fullName>LastName__c</fullName>
    <label>LastName</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

Prod-EU/force-app/main/default/objects/Sample_Order_Request_Event__e/fields/Mobile__c.field-meta.xml
<CustomField>
    <fullName>Mobile__c</fullName>
    <label>Mobile</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

Prod-EU/force-app/main/default/objects/Sample_Order_Request_Event__e/fields/OCEOrderReference__c.field-meta.xml
<CustomField>
    <fullName>OCEOrderReference__c</fullName>
    <label>OCEOrderReference</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

Prod-EU/force-app/main/default/objects/Sample_Order_Request_Event__e/fields/OtherPhone__c.field-meta.xml
<CustomField>
    <fullName>OtherPhone__c</fullName>
    <label>OtherPhone</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

Prod-EU/force-app/main/default/objects/Sample_Order_Request_Event__e/fields/PostalCode__c.field-meta.xml
<CustomField>
    <fullName>PostalCode__c</fullName>
    <label>PostalCode</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

Prod-EU/force-app/main/default/objects/Sample_Order_Request_Event__e/fields/Preferred_Language__c.field-meta.xml
<CustomField>
    <fullName>Preferred_Language__c</fullName>
    <label>Preferred Language</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

Prod-EU/force-app/main/default/objects/Sample_Order_Request_Event__e/fields/ProgramType__c.field-meta.xml
<CustomField>
    <fullName>ProgramType__c</fullName>
    <label>ProgramType</label>
    <length>25</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

Prod-EU/force-app/main/default/objects/Sample_Order_Request_Event__e/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <label>Quantity</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Prod-EU/force-app/main/default/objects/Sample_Order_Request_Event__e/fields/StateProvince__c.field-meta.xml
<CustomField>
    <fullName>StateProvince__c</fullName>
    <label>StateProvince</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

Prod-EU/force-app/main/default/objects/Sample_Order_Request_Event__e/fields/WorkPhone__c.field-meta.xml
<CustomField>
    <fullName>WorkPhone__c</fullName>
    <label>WorkPhone</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

Prod-EU/force-app/main/default/objects/Sample_Order_Response_Event__e/Sample_Order_Response_Event__e.object-meta.xml
<CustomObject>
    <label>Sample Order Response Event</label>
    <pluralLabel>Sample Order Response Events</pluralLabel>
</CustomObject>

Prod-EU/force-app/main/default/objects/Sample_Order_Response_Event__e/fields/IntegrationErrorMessage__c.field-meta.xml
<CustomField>
    <fullName>IntegrationErrorMessage__c</fullName>
    <label>IntegrationErrorMessage</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

Prod-EU/force-app/main/default/objects/Sample_Order_Response_Event__e/fields/IntegrationStatus__c.field-meta.xml
<CustomField>
    <fullName>IntegrationStatus__c</fullName>
    <label>IntegrationStatus</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

Prod-EU/force-app/main/default/objects/Sample_Order_Response_Event__e/fields/OCEOrderReference__c.field-meta.xml
<CustomField>
    <fullName>OCEOrderReference__c</fullName>
    <label>OCEOrderReference</label>
    <length>25</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

Prod-EU/force-app/main/default/objects/Sample_Order_Response_Event__e/fields/OrderNumber__c.field-meta.xml
<CustomField>
    <fullName>OrderNumber__c</fullName>
    <label>OrderNumber</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

Prod-EU/force-app/main/default/objects/Sample_Order_Response_Event__e/fields/OrderStatus__c.field-meta.xml
<CustomField>
    <fullName>OrderStatus__c</fullName>
    <label>OrderStatus</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

Prod-EU/force-app/main/default/classes/PEClsHandleBatchOCEEvent_Test.cls
@isTest
public class PEClsHandleBatchOCEEvent_Test {
    
    @isTest
    public static void publishOCEEventNonAccExist(){
        
        
        Map<String, String> mapPriceBook = ClsTestDataFactory.createCPB(new List<String>{'CAN No Charge'},'CAD');
        Map<String, Id> mapProduct = ClsTestDataFactory.createProducts(new List<String>{'STP-GS-113','STS-GS-008'});
        Map<Id, Decimal> productIdToPriceMap = new Map<Id, Decimal>();
        for(Id productId : mapProduct.values()){
            productIdToPriceMap.put(productId, 10); 
        }
        Map<Id, Id> mapPBE = ClsTestDataFactory.createCustomPricebookEntriesCA(productIdToPriceMap, mapPriceBook.get('CAN No Charge'));
        Account objAccount = ClsTestDataFactory.createAccountsWithBillingAddress(1, 'CA Consumer', 'Canada')[0];
        //String Sampletype= 'Stage 1';
        Account payorAccount = ClsTestDataFactory.createAccountsWithBillingAddress(1, 'CA Payor', 'Canada')[0];
        Id AddId=[Select Id from RecordType Where sObjectType='Address__c' AND Name='CA Address' Limit 1].Id;
        
        List<Address__c> lstAddress = new List<Address__c>{
            new Address__c(Account__c = objAccount.Id,RecordTypeId = AddId, Type__c = 'Bill To', Country__c = 'Canada', City__c = 'Rosemont', Address_Line_1__c = '10255 W Higgins Rd', Postal_Code__c = 'H0H 0H0', Primary_Flag__c = true),
                new Address__c(Account__c = objAccount.Id,RecordTypeId = AddId, Type__c = 'Ship To',Country__c = 'Canada', City__c = 'Rosemont', Address_Line_1__c = '10255 W Higgins Rd', Postal_Code__c = 'H0H 0H0', Primary_Flag__c = true),
                new Address__c(Account__c = payorAccount.Id,RecordTypeId = AddId, Type__c = 'Bill To', Country__c = 'Canada', City__c = 'Rosemont', Address_Line_1__c = '10255 W Higgins Rd', Postal_Code__c = 'H0H 0H0', Primary_Flag__c = true),
                new Address__c(Account__c = payorAccount.Id,RecordTypeId = AddId, Type__c = 'Ship To',Country__c = 'Canada', City__c = 'Rosemont', Address_Line_1__c = '10255 W Higgins Rd', Postal_Code__c = 'H0H 0H0', Primary_Flag__c = true)
                };
                    insert lstAddress;
        
        Sample_Order_Request_Event__e oce = new Sample_Order_Request_Event__e();
        oce.AccCountryCode__c = 'CA';
        oce.AccountType__c = 'Prescriber';
        oce.AccountOnekeyId__c = 'WDEM011910112';
        oce.AddressOneKeyId__c  = 'WDEE00030931WDE000000539PTTL';
        oce.AddressLine1__c = '420-210 Ave P S';
        oce.AddressLine2__c = '420';
        oce.AddressLine3__c = '';
        oce.OCEOrderReference__c = '1231242183';
        oce.ProgramType__c = 'CA Prescriber Sample';
        oce.BirthDate__c = System.today() - 4000;
        oce.CareOf_AddressFirstName__c = 'OCE';
        oce.CareOf_AddressLastName__c = 'Test';
        oce.Address_Phone_Number__c = '';
        oce.City__c = 'Saskatoon';
        oce.Email__c = 'oceEvntTest@dexcom9.invalid.com';
        oce.HomePhone__c = '1223412242';
        oce.LastName__c = 'OCE Sample';
        oce.FirstName__c = 'Account';
        oce.Mobile__c = '';
        oce.OtherPhone__c = '';
        oce.PostalCode__c = 'S7M 2W2';
        oce.Preferred_Language__c = 'en';
        oce.StateProvince__c = 'Alberta';
        oce.WorkPhone__c = '';
        oce.Quantity__c = 0;
        Test.startTest();
        Database.SaveResult svrs = EventBus.publish(oce);
        // ClsSampleProgramHandler.creteSampleOpportunity(objAccount.Id, '');
        Test.stopTest();
        System.debug('svrs--'+svrs);
    }
    @isTest
    public static void publishOCEEventAccExist(){
        
        
        Map<String, String> mapPriceBook = ClsTestDataFactory.createCPB(new List<String>{'CAN No Charge'},'CAD');
        Map<String, Id> mapProduct = ClsTestDataFactory.createProducts(new List<String>{'STP-GS-113','STS-GS-008'});
        Map<Id, Decimal> productIdToPriceMap = new Map<Id, Decimal>();
        for(Id productId : mapProduct.values()){
            productIdToPriceMap.put(productId, 10); 
        }
        Map<Id, Id> mapPBE = ClsTestDataFactory.createCustomPricebookEntriesCA(productIdToPriceMap, mapPriceBook.get('CAN No Charge'));
        Id accRectype=[Select Id from RecordType Where sObjectType='Account' AND Name='CA Consumer' Limit 1].Id;
        
        Account objAccount = new Account();
        objAccount.RecordTypeId = accRectype;
        objAccount.LastName ='LastName';
        objAccount.FirstName = 'OCE';
        objAccount.IQVIA_OneKeyId__c = 'WDEM011910112';
        objAccount.CurrencyIsoCode = 'CAD';
        insert objAccount;
        //Account objAccount = ClsTestDataFactory.createAccountsWithBillingAddress(1, 'CA Consumer', 'Canada')[0];
        //objAccount.IQVIA_OneKeyId__c = 'WDEM011910112';
        //update objAccount;
        //String Sampletype= 'Stage 1';
        //Account payorAccount = ClsTestDataFactory.createAccountsWithBillingAddress(1, 'CA Payor', 'Canada')[0];
        Id AddId=[Select Id from RecordType Where sObjectType='Address__c' AND Name='CA Address' Limit 1].Id;
        
        List<Address__c> lstAddress = new List<Address__c>{
            // new Address__c(Account__c = objAccount.Id,RecordTypeId = AddId, Type__c = 'Bill To', Country__c = 'Canada', City__c = 'Rosemont', Address_Line_1__c = '10255 W Higgins Rd', Postal_Code__c = 'H0H 0H0', Primary_Flag__c = true),
            new Address__c(Account__c = objAccount.Id,IQVIA_OneKeyId__c = 'WDEE00030931WDE000000539PTTL',RecordTypeId = AddId, Type__c = 'Ship To',Country__c = 'Canada', City__c = 'Rosemont', Address_Line_1__c = '10255 W Higgins Rd', Postal_Code__c = 'H0H 0H0', Primary_Flag__c = true)
                //new Address__c(Account__c = payorAccount.Id,RecordTypeId = AddId, Type__c = 'Bill To', Country__c = 'Canada', City__c = 'Rosemont', Address_Line_1__c = '10255 W Higgins Rd', Postal_Code__c = 'H0H 0H0', Primary_Flag__c = true),
                // new Address__c(Account__c = payorAccount.Id,RecordTypeId = AddId, Type__c = 'Ship To',Country__c = 'Canada', City__c = 'Rosemont', Address_Line_1__c = '10255 W Higgins Rd', Postal_Code__c = 'H0H 0H0', Primary_Flag__c = true)
                };
                    insert lstAddress;
        
        List<PricebookEntry> lstPBE = [SELECT Id, Pricebook2Id, Product2Id FROM PricebookEntry WHERE Pricebook2.Name = 'CAN No Charge'];
        
        Sample_Order_Request_Event__e oce = new Sample_Order_Request_Event__e();
        oce.AccCountryCode__c = 'CA';
        oce.AccountType__c = 'Prescriber';
        oce.AccountOnekeyId__c = 'WDEM011910112';
        oce.AddressOneKeyId__c  = 'WDEE00030931WDE000000539PTTL';
        oce.AddressLine1__c = '420-210 Ave P S';
        oce.AddressLine2__c = '420';
        oce.AddressLine3__c = '';
        oce.OCEOrderReference__c = '1231242183';
        oce.ProgramType__c = 'CA Prescriber Sample';
        oce.BirthDate__c = System.today() - 4000;
        oce.CareOf_AddressFirstName__c = 'OCE';
        oce.CareOf_AddressLastName__c = 'Test';
        oce.Address_Phone_Number__c = '';
        oce.City__c = 'Saskatoon';
        oce.Email__c = 'oceEvntTest@dexcom9.invalid.com';
        oce.HomePhone__c = '1223412242';
        oce.LastName__c = 'OCE Sample';
        oce.FirstName__c = 'Account';
        oce.Mobile__c = '';
        oce.OtherPhone__c = '';
        oce.PostalCode__c = 'S7M 2W2';
        oce.Preferred_Language__c = 'en';
        oce.StateProvince__c = 'Alberta';
        oce.WorkPhone__c = '';
        oce.Quantity__c = 0;
        Test.startTest();
        Database.SaveResult svrs = EventBus.publish(oce);
        // ClsSampleProgramHandler.creteSampleOpportunity(objAccount.Id, '');
        Test.stopTest();
        System.debug('svrs--'+svrs);
    }
    @isTest
    public static void publishOCEEventException_OCEOrderRef(){
        
        
        Map<String, String> mapPriceBook = ClsTestDataFactory.createCPB(new List<String>{'CAN No Charge'},'CAD');
        Map<String, Id> mapProduct = ClsTestDataFactory.createProducts(new List<String>{'STP-GS-113','STS-GS-008'});
        Map<Id, Decimal> productIdToPriceMap = new Map<Id, Decimal>();
        for(Id productId : mapProduct.values()){
            productIdToPriceMap.put(productId, 10); 
        }
        Map<Id, Id> mapPBE = ClsTestDataFactory.createCustomPricebookEntriesCA(productIdToPriceMap, mapPriceBook.get('CAN No Charge'));
        Account objAccount = ClsTestDataFactory.createAccountsWithBillingAddress(1, 'CA Consumer', 'Canada')[0];
        objAccount.IQVIA_OneKeyId__c = 'WDEM011910112';
        update objAccount;
        //String Sampletype= 'Stage 1';
        Account payorAccount = ClsTestDataFactory.createAccountsWithBillingAddress(1, 'CA Payor', 'Canada')[0];
        Id AddId=[Select Id from RecordType Where sObjectType='Address__c' AND Name='CA Address' Limit 1].Id;
        
        List<Address__c> lstAddress = new List<Address__c>{
            new Address__c(Account__c = objAccount.Id,IQVIA_OneKeyId__c = 'WDEE00030931WDE000000539PTTL',RecordTypeId = AddId, Type__c = 'Bill To', Country__c = 'Canada', City__c = 'Rosemont', Address_Line_1__c = '10255 W Higgins Rd', Postal_Code__c = 'H0H 0H0', Primary_Flag__c = true)
                //new Address__c(Account__c = objAccount.Id,IQVIA_OneKeyId__c = 'WDEE00030931WDE000000539PTTL',RecordTypeId = AddId, Type__c = 'Ship To',Country__c = 'Canada', City__c = 'Rosemont', Address_Line_1__c = '10255 W Higgins Rd', Postal_Code__c = 'H0H 0H0', Primary_Flag__c = true),
                //new Address__c(Account__c = payorAccount.Id,RecordTypeId = AddId, Type__c = 'Bill To', Country__c = 'Canada', City__c = 'Rosemont', Address_Line_1__c = '10255 W Higgins Rd', Postal_Code__c = 'H0H 0H0', Primary_Flag__c = true),
                //new Address__c(Account__c = payorAccount.Id,RecordTypeId = AddId, Type__c = 'Ship To',Country__c = 'Canada', City__c = 'Rosemont', Address_Line_1__c = '10255 W Higgins Rd', Postal_Code__c = 'H0H 0H0', Primary_Flag__c = true)
                };
                    //  insert lstAddress;
                    
                    
                    
                    Sample_Order_Request_Event__e oce = new Sample_Order_Request_Event__e();
        oce.AccCountryCode__c = 'CA';
        oce.AccountType__c = 'Prescriber';
        oce.AccountOnekeyId__c = 'WDEM011910112';
        oce.AddressOneKeyId__c  = 'WDEE00030931WDE000000539PTTL';
        oce.AddressLine1__c = '420-210 Ave P S';
        oce.AddressLine2__c = '420';
        oce.AddressLine3__c = '';
        oce.OCEOrderReference__c = '';
        oce.ProgramType__c = 'CA Prescriber Sample';
        oce.BirthDate__c = System.today() - 4000;
        oce.CareOf_AddressFirstName__c = 'OCE';
        oce.CareOf_AddressLastName__c = 'Test';
        oce.Address_Phone_Number__c = '';
        oce.City__c = 'Saskatoon';
        oce.Email__c = 'oceEvntTest@dexcom9.invalid.com';
        oce.HomePhone__c = '1223412242';
        oce.LastName__c = 'OCE Sample';
        oce.FirstName__c = 'Account';
        oce.Mobile__c = '';
        oce.OtherPhone__c = '';
        oce.PostalCode__c = 'S7M 2W2';
        oce.Preferred_Language__c = 'en';
        oce.StateProvince__c = 'Alberta';
        oce.WorkPhone__c = '';
        oce.Quantity__c = 0;
        Test.startTest();
        Database.SaveResult svrs = EventBus.publish(oce);
        
        Test.stopTest();
        System.debug('svrs--'+svrs);
    }
    
    @isTest
    public static void OCEEventNonAccExist_ADDRESS(){
        
        
        Sample_Order_Request_Event__e oce = new Sample_Order_Request_Event__e();
        oce.AccCountryCode__c = 'CA';
        oce.AccountType__c = 'Prescriber';
        oce.AccountOnekeyId__c = 'WDEM011910112';
        oce.AddressOneKeyId__c  = 'WDEE00030931WDE000000539PTTL';
        oce.AddressLine1__c = '';
        oce.AddressLine2__c = '420';
        oce.AddressLine3__c = '';
        oce.OCEOrderReference__c = '1231242183';
        oce.ProgramType__c = 'CA Prescriber Sample';
        oce.BirthDate__c = System.today() - 4000;
        oce.CareOf_AddressFirstName__c = 'OCE';
        oce.CareOf_AddressLastName__c = 'Test';
        oce.Address_Phone_Number__c = '';
        oce.City__c = 'Saskatoon';
        oce.Email__c = 'oceEvntTest@dexcom9.invalid.com';
        oce.HomePhone__c = '1223412242';
        oce.LastName__c = 'OCE Sample';
        oce.FirstName__c = 'Account';
        oce.Mobile__c = '';
        oce.OtherPhone__c = '';
        oce.PostalCode__c = 'S7M 2W2';
        oce.Preferred_Language__c = 'en';
        oce.StateProvince__c = 'Alberta';
        oce.WorkPhone__c = '';
        oce.Quantity__c = 0;
        Test.startTest();
        Database.SaveResult svrs = EventBus.publish(oce);
        // ClsSampleProgramHandler.creteSampleOpportunity(objAccount.Id, '');
        Test.stopTest();
        System.debug('svrs--'+svrs);
    }
    @isTest
    public static void OCEEventNonAccExist_POSTALCODE(){
        
        
        Sample_Order_Request_Event__e oce = new Sample_Order_Request_Event__e();
        oce.AccCountryCode__c = 'CA';
        oce.AccountType__c = 'Prescriber';
        oce.AccountOnekeyId__c = 'WDEM011910112';
        oce.AddressOneKeyId__c  = 'WDEE00030931WDE000000539PTTL';
        oce.AddressLine1__c = '420-210 Ave P S';
        oce.AddressLine2__c = '420';
        oce.AddressLine3__c = '';
        oce.OCEOrderReference__c = '1231242183';
        oce.ProgramType__c = 'CA Prescriber Sample';
        oce.BirthDate__c = System.today() - 4000;
        oce.CareOf_AddressFirstName__c = 'OCE';
        oce.CareOf_AddressLastName__c = 'Test';
        oce.Address_Phone_Number__c = '';
        oce.City__c = 'Saskatoon';
        oce.Email__c = 'oceEvntTest@dexcom9.invalid.com';
        oce.HomePhone__c = '1223412242';
        oce.LastName__c = 'OCE Sample';
        oce.FirstName__c = 'Account';
        oce.Mobile__c = '';
        oce.OtherPhone__c = '';
        oce.PostalCode__c = '';
        oce.Preferred_Language__c = 'en';
        oce.StateProvince__c = 'Alberta';
        oce.WorkPhone__c = '';
        oce.Quantity__c = 0;
        Test.startTest();
        Database.SaveResult svrs = EventBus.publish(oce);
        // ClsSampleProgramHandler.creteSampleOpportunity(objAccount.Id, '');
        Test.stopTest();
        System.debug('svrs--'+svrs);
    }
    @isTest
    public static void OCEEventNonAccExist_CITY(){
        
        Sample_Order_Request_Event__e oce = new Sample_Order_Request_Event__e();
        oce.AccCountryCode__c = 'CA';
        oce.AccountType__c = 'Prescriber';
        oce.AccountOnekeyId__c = 'WDEM011910112';
        oce.AddressOneKeyId__c  = 'WDEE00030931WDE000000539PTTL';
        oce.AddressLine1__c = '420-210 Ave P S';
        oce.AddressLine2__c = '420';
        oce.AddressLine3__c = '';
        oce.OCEOrderReference__c = '1231242183';
        oce.ProgramType__c = 'CA Prescriber Sample';
        oce.BirthDate__c = System.today() - 4000;
        oce.CareOf_AddressFirstName__c = 'OCE';
        oce.CareOf_AddressLastName__c = 'Test';
        oce.Address_Phone_Number__c = '';
        oce.City__c = '';
        oce.Email__c = 'oceEvntTest@dexcom9.invalid.com';
        oce.HomePhone__c = '1223412242';
        oce.LastName__c = 'OCE Sample';
        oce.FirstName__c = 'Account';
        oce.Mobile__c = '';
        oce.OtherPhone__c = '';
        oce.PostalCode__c = 'S7M 2W2';
        oce.Preferred_Language__c = 'en';
        oce.StateProvince__c = 'Alberta';
        oce.WorkPhone__c = '';
        oce.Quantity__c = 0;
        Test.startTest();
        Database.SaveResult svrs = EventBus.publish(oce);
        // ClsSampleProgramHandler.creteSampleOpportunity(objAccount.Id, '');
        Test.stopTest();
        System.debug('svrs--'+svrs);
    }
    @isTest
    public static void OCEEventNonAccExist_STATE(){
        
        Sample_Order_Request_Event__e oce = new Sample_Order_Request_Event__e();
        oce.AccCountryCode__c = 'CA';
        oce.AccountType__c = 'Prescriber';
        oce.AccountOnekeyId__c = 'WDEM011910112';
        oce.AddressOneKeyId__c  = 'WDEE00030931WDE000000539PTTL';
        oce.AddressLine1__c = '420-210 Ave P S';
        oce.AddressLine2__c = '420';
        oce.AddressLine3__c = '';
        oce.OCEOrderReference__c = '1231242183';
        oce.ProgramType__c = 'CA Prescriber Sample';
        oce.BirthDate__c = System.today() - 4000;
        oce.CareOf_AddressFirstName__c = 'OCE';
        oce.CareOf_AddressLastName__c = 'Test';
        oce.Address_Phone_Number__c = '';
        oce.City__c = 'Saskatoon';
        oce.Email__c = 'oceEvntTest@dexcom9.invalid.com';
        oce.HomePhone__c = '1223412242';
        oce.LastName__c = 'OCE Sample';
        oce.FirstName__c = 'Account';
        oce.Mobile__c = '';
        oce.OtherPhone__c = '';
        oce.PostalCode__c = 'S7M 2W2';
        oce.Preferred_Language__c = 'en';
        oce.StateProvince__c = '';
        oce.WorkPhone__c = '';
        oce.Quantity__c = 0;
        Test.startTest();
        Database.SaveResult svrs = EventBus.publish(oce);
        // ClsSampleProgramHandler.creteSampleOpportunity(objAccount.Id, '');
        Test.stopTest();
        System.debug('svrs--'+svrs);
    }
    @isTest
    public static void OCEEventNonAccExist_ACCOUNTKEY(){
        
        Sample_Order_Request_Event__e oce = new Sample_Order_Request_Event__e();
        oce.AccCountryCode__c = '';
        oce.AccountType__c = 'Prescriber';
        oce.AccountOnekeyId__c = 'WDEM011910112';
        oce.AddressOneKeyId__c  = 'WDEE00030931WDE000000539PTTL';
        oce.AddressLine1__c = '420-210 Ave P S';
        oce.AddressLine2__c = '420';
        oce.AddressLine3__c = '';
        oce.OCEOrderReference__c = '1231242183';
        oce.ProgramType__c = 'CA Prescriber Sample';
        oce.BirthDate__c = System.today() - 4000;
        oce.CareOf_AddressFirstName__c = 'OCE';
        oce.CareOf_AddressLastName__c = 'Test';
        oce.Address_Phone_Number__c = '';
        oce.City__c = 'Saskatoon';
        oce.Email__c = 'oceEvntTest@dexcom9.invalid.com';
        oce.HomePhone__c = '1223412242';
        oce.LastName__c = 'OCE Sample';
        oce.FirstName__c = 'Account';
        oce.Mobile__c = '';
        oce.OtherPhone__c = '';
        oce.PostalCode__c = 'S7M 2W2';
        oce.Preferred_Language__c = 'en';
        oce.StateProvince__c = 'Alberta';
        oce.WorkPhone__c = '';
        oce.Quantity__c = 0;
        Test.startTest();
        Database.SaveResult svrs = EventBus.publish(oce);
        // ClsSampleProgramHandler.creteSampleOpportunity(objAccount.Id, '');
        Test.stopTest();
        System.debug('svrs--'+svrs);
    }
    @isTest
    public static void OCEEventNonAccExist_ACCLASTNAME(){
        
        Sample_Order_Request_Event__e oce = new Sample_Order_Request_Event__e();
        oce.AccCountryCode__c = 'CA';
        oce.AccountType__c = 'Prescriber';
        oce.AccountOnekeyId__c = 'WDEM011910112';
        oce.AddressOneKeyId__c  = 'WDEE00030931WDE000000539PTTL';
        oce.AddressLine1__c = '420-210 Ave P S';
        oce.AddressLine2__c = '420';
        oce.AddressLine3__c = '';
        oce.OCEOrderReference__c = '1231242183';
        oce.ProgramType__c = 'CA Prescriber Sample';
        oce.BirthDate__c = System.today() - 4000;
        oce.CareOf_AddressFirstName__c = 'OCE';
        oce.CareOf_AddressLastName__c = 'Test';
        oce.Address_Phone_Number__c = '';
        oce.City__c = 'Saskatoon';
        oce.Email__c = 'oceEvntTest@dexcom9.invalid.com';
        oce.HomePhone__c = '1223412242';
        oce.LastName__c = '';
        oce.FirstName__c = 'Account';
        oce.Mobile__c = '';
        oce.OtherPhone__c = '';
        oce.PostalCode__c = 'S7M 2W2';
        oce.Preferred_Language__c = 'en';
        oce.StateProvince__c = 'Alberta';
        oce.WorkPhone__c = '';
        oce.Quantity__c = 0;
        Test.startTest();
        Database.SaveResult svrs = EventBus.publish(oce);
        // ClsSampleProgramHandler.creteSampleOpportunity(objAccount.Id, '');
        Test.stopTest();
        System.debug('svrs--'+svrs);
    }
    @isTest
    public static void OCEEventNonAccExist_ACCFIRSTNAME(){
        Sample_Order_Request_Event__e oce = new Sample_Order_Request_Event__e();
        oce.AccCountryCode__c = 'CA';
        oce.AccountType__c = 'Prescriber';
        oce.AccountOnekeyId__c = 'WDEM011910112';
        oce.AddressOneKeyId__c  = 'WDEE00030931WDE000000539PTTL';
        oce.AddressLine1__c = '420-210 Ave P S';
        oce.AddressLine2__c = '420';
        oce.AddressLine3__c = '';
        oce.OCEOrderReference__c = '1231242183';
        oce.ProgramType__c = 'CA Prescriber Sample';
        oce.BirthDate__c = System.today() - 4000;
        oce.CareOf_AddressFirstName__c = 'OCE';
        oce.CareOf_AddressLastName__c = 'Test';
        oce.Address_Phone_Number__c = '';
        oce.City__c = 'Saskatoon';
        oce.Email__c = 'oceEvntTest@dexcom9.invalid.com';
        oce.HomePhone__c = '1223412242';
        oce.LastName__c = 'Account';
        oce.FirstName__c = '';
        oce.Mobile__c = '';
        oce.OtherPhone__c = '';
        oce.PostalCode__c = 'S7M 2W2';
        oce.Preferred_Language__c = 'en';
        oce.StateProvince__c = 'Alberta';
        oce.WorkPhone__c = '';
        oce.Quantity__c = 0;
        Test.startTest();
        Database.SaveResult svrs = EventBus.publish(oce);
        // ClsSampleProgramHandler.creteSampleOpportunity(objAccount.Id, '');
        Test.stopTest();
        System.debug('svrs--'+svrs);
    }
    
    @isTest
    public static void OCE_OUTEvent(){
        
        Sample_Order_Request_Event__e oce = new Sample_Order_Request_Event__e();
        
        Sample_Order_Response_Event__e oceOut = new Sample_Order_Response_Event__e();
        oceOut.OrderStatus__c ='Created';
        oceOut.OCEOrderReference__c ='a01wewewewedgwer';
        //oceOut.IntegrationErrorMessage__c ='';
        //oceOut.IntegrationStatus__c = '';
        oceOut.OrderNumber__c = '1223213141';
        ClsTestSampleOrderMockService mocksample = new ClsTestSampleOrderMockService('OK');
        Test.setMock(HttpCalloutMock.class, mocksample);  
        
        Test.startTest();
        Database.SaveResult svrs = EventBus.publish(oceOut);
        // ClsSampleProgramHandler.creteSampleOpportunity(objAccount.Id, '');
        Test.stopTest();
        System.debug('svrs--'+svrs);
    }
    @isTest
    public static void OCE_OUTEvent_302(){        
        Sample_Order_Request_Event__e oce = new Sample_Order_Request_Event__e();        
        Sample_Order_Response_Event__e oceOut = new Sample_Order_Response_Event__e();
        oceOut.OrderStatus__c ='Created';
        oceOut.OCEOrderReference__c ='a01wewewewedgwer';
        //oceOut.IntegrationErrorMessage__c ='';
        //oceOut.IntegrationStatus__c = '';
        oceOut.OrderNumber__c = '1223213141';
        ClsTestSampleOrderMockService mocksample = new ClsTestSampleOrderMockService();
        Test.setMock(HttpCalloutMock.class, mocksample);  
        
        Test.startTest();
        Database.SaveResult svrs = EventBus.publish(oceOut);
        // ClsSampleProgramHandler.creteSampleOpportunity(objAccount.Id, '');
        Test.stopTest();
        System.debug('svrs--'+svrs);
    }
}