Prod-EU/force-app/main/default/objects/Account/fields/Price_Book__c.field-meta.xml
<CustomField>
    <fullName>Price_Book__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Price Book</label>
    <referenceTo>Pricebook2</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

Prod-EU/force-app/main/default/objects/Marketing_Interaction__c/Marketing_Interaction__c.object-meta.xml
<CustomObject>
    <description>Object used to trigger journeys in Marketing Cloud.</description>
    <label>Marketing Interaction</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Marketing Interaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Marketing Interactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Prod-EU/force-app/main/default/objects/Marketing_Interaction__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Marketing Interactions</relationshipLabel>
    <relationshipName>Marketing_Interactions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

Prod-EU/force-app/main/default/objects/Marketing_Interaction__c/fields/Communication_Type__c.field-meta.xml
<CustomField>
    <fullName>Communication_Type__c</fullName>
    <label>Communication Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CA - Customer Onboarding</fullName>
            </value>
            <value>
                <fullName>CA - Product Onboarding - G5</fullName>
            </value>
            <value>
                <fullName>CA - Reorder Reminder - G5</fullName>
            </value>
            <value>
                <fullName>CA - Product Onboarding - G6</fullName>
            </value>
            <value>
                <fullName>CA - Reorder Reminder - G6 Starter Kit</fullName>
            </value>
            <value>
                <fullName>CA - Subscription Renewal - Signature</fullName>
            </value>
            <value>
                <fullName>CA - Subscription Renewal - Auto</fullName>
            </value>
            <value>
                <fullName>CA - Subscription Upsell - G6</fullName>
            </value>
            <value>
                <fullName>UKIE - Customer Onboarding - G6</fullName>
            </value>
            <value>
                <fullName>UKIE - Customer Review</fullName>
            </value>
            <value>
                <fullName>UKIE - Warrior Recruitment</fullName>
            </value>
            <value>
                <fullName>UKIE - Subscription Renewal - G6</fullName>
            </value>
            <value>
                <fullName>UKIE - Subscription Upsell - G6</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Prod-EU/force-app/main/default/objects/Marketing_Interaction__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <description>Country should always be required for all records entered in this object.</description>
    <label>Country</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country</valueSetName>
    </valueSet>
</CustomField>

Prod-EU/force-app/main/default/objects/Marketing_Interaction__c/fields/Related_Information__c.field-meta.xml
<CustomField>
    <fullName>Related_Information__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Related Information</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

Prod-EU/force-app/main/default/objects/Marketing_Interaction__c/fields/Source_Record_Id__c.field-meta.xml
<CustomField>
    <fullName>Source_Record_Id__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Source Record Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

Prod-EU/force-app/main/default/objects/SSIP_Rule__c/SSIP_Rule__c.object-meta.xml
<CustomObject>
    <description>Object stores all SSIP rule for the customers.</description>
    <label>SSIP Rule</label>
    <nameField>
        <displayFormat>SP-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SSIP Rule</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Prod-EU/force-app/main/default/objects/SSIP_Rule__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Master detail relationship to the account.</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>SSIP Rule</relationshipLabel>
    <relationshipName>SSIP_Rule</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Prod-EU/force-app/main/default/objects/SSIP_Rule__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <description>Country to which this rule is tied to</description>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country</valueSetName>
    </valueSet>
</CustomField>

Prod-EU/force-app/main/default/objects/SSIP_Rule__c/fields/Price_Book__c.field-meta.xml
<CustomField>
    <fullName>Price_Book__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Price book, which will filter out only SSIP Pricebooks</description>
    <label>Price Book</label>
    <referenceTo>Pricebook2</referenceTo>
    <relationshipLabel>SSIP Rule</relationshipLabel>
    <relationshipName>SSIP_Rule</relationshipName>
    <type>Lookup</type>
</CustomField>

Prod-EU/force-app/main/default/objects/SSIP_Rule__c/fields/PriceBookEntryId__c.field-meta.xml
<CustomField>
    <fullName>PriceBookEntryId__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>PriceBookEntryId</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

Prod-EU/force-app/main/default/objects/SSIP_Rule__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>SSIP Rule</relationshipLabel>
    <relationshipName>SSIP_Rule</relationshipName>
    <type>Lookup</type>
</CustomField>

Prod-EU/force-app/main/default/objects/SSIP_Rule__c/fields/Renewal_Date__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Date__c</fullName>
    <description>Date when the contract can be renewed</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Date should be greater than or equal to today&apos;s date.</inlineHelpText>
    <label>Renewal Date</label>
    <type>Date</type>
</CustomField>

Prod-EU/force-app/main/default/objects/SSIP_Rule__c/fields/Rule_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Rule_End_Date__c</fullName>
    <description>Date when the rule will end.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Date should be greater than or equal to today&apos;s date. Setting this date will delete any open schedules past this date.</inlineHelpText>
    <label>Rule End Date</label>
    <type>Date</type>
</CustomField>

Prod-EU/force-app/main/default/objects/SSIP_Rule__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&apos;Active&apos;</defaultValue>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Prod-EU/force-app/main/default/objects/SSIP_Rule__c/recordTypes/CA_SSIP_Rule.recordType-meta.xml
<RecordType>
    <fullName>CA_SSIP_Rule</fullName>
    <active>true</active>
    <label>CA SSIP Rule</label>
</RecordType>

Prod-EU/force-app/main/default/classes/BClsMarketingInteractionCA_Test.cls
@isTest
public class BClsMarketingInteractionCA_Test {
    
    @isTest static void MIRuleEndDateBatch(){
        
        //Insert 1 consumer account record
        List<Account> consumerAccts = ClsTestDataFactory.createAccountsWithBillingAddress(1, 'CA Consumer', 'Canada');
        
        //Create Pricebook
        Map<String, Id> customPricebookMap = ClsTestDataFactory.createCustomPricebook(new List <String>{'CAN G6 SUBSCRIPTION 12MOS NO Renewal'});
        String customPricebookId = customPricebookMap.get('CAN G6 SUBSCRIPTION 12MOS NO Renewal');
        
        //Create Products
        Map<String, Id> products = ClsTestDataFactory.createProducts(new List<String> {'MTRNTCAGS-12MOS'});
        
        //Update the virtual sku productIdToPbeId
        Product2 virtualProd = [SELECT Id, Is_Virtual_Product__c FROM Product2 WHERE NAME = 'MTRNTCAGS-12MOS'];
        virtualProd.Is_Virtual_Product__c = true;
        update virtualProd;
        
        //Create Pricebook EntryPair
        Map<Id, Decimal> productIdToPriceMap = new Map<Id, Decimal>();
        for(String productName : products.keySet()){
            productIdToPriceMap.put(products.get(productName), 125.00);
            
        }
        
        Map<Id, Id> productIdToPbeId = ClsTestDataFactory.createCustomPricebookEntriesCA(productIdToPriceMap, customPricebookId);
        List<PricebookEntry> lstPBE = [SELECT Id, Pricebook2Id, Product2Id FROM PricebookEntry WHERE Pricebook2.Name = 'CAN G6 SUBSCRIPTION 12MOS NO Renewal'];
        Id caRecdTypeId = Schema.SObjectType.SSIP_Rule__c.getRecordTypeInfosByDeveloperName().get('CA_SSIP_Rule').getRecordTypeId();
        Date tenDate= date.today().adddays(90);
        SSIP_Rule__c ssip = new SSIP_Rule__c();
        ssip.RecordTypeId=caRecdTypeId;
        ssip.Account__c=consumerAccts[0].Id;
        ssip.Rule_End_Date__c =tenDate;
        ssip.Country__c='Canada';
        ssip.Price_Book__c = customPricebookId;
        ssip.PriceBookEntryId__c =lstPBE[0].id;
        ssip.product__c=products.get('MTRNTCAGS-12MOS');
        ssip.Status__c='Active';
        insert ssip;
        
        Marketing_interaction__c mi = new Marketing_interaction__c();
        mi.Account__c = consumerAccts[0].Id;
        mi.Communication_Type__c = 'CA - Subscription Renewal - Signature';
        mi.Country__c = 'Canada';
        mi.CurrencyIsoCode = 'CAD';
        mi.Source_Record_Id__c = ssip.Id;
        mi.Related_Information__c = String.valueOf(ssip.Rule_End_Date__c);
        insert mi;
        Datetime beforeSixMon = Datetime.now().addDays(-98);
        Test.setCreatedDate(mi.Id, beforeSixMon);
        Test.startTest();
        BclsMarketingInteractionCARuleEndBatch sbatch = new BclsMarketingInteractionCARuleEndBatch();
        Id batchInstanceId = Database.executeBatch(sbatch, 1);
        
        Test.stopTest();
    }
     @isTest static void MIRenewalDateBatch(){
        
        //Insert 1 consumer account record
        List<Account> consumerAccts = ClsTestDataFactory.createAccountsWithBillingAddress(1, 'CA Consumer', 'Canada');
        
        //Create Pricebook
        Map<String, Id> customPricebookMap = ClsTestDataFactory.createCustomPricebook(new List <String>{'CAN G6 SUBSCRIPTION 12MOS Auto Renewal'});
        String customPricebookId = customPricebookMap.get('CAN G6 SUBSCRIPTION 12MOS Auto Renewal');
        
        //Create Products
        Map<String, Id> products = ClsTestDataFactory.createProducts(new List<String> {'MTRNTCAGS-12MOS'});
        
        //Update the virtual sku productIdToPbeId
        Product2 virtualProd = [SELECT Id, Is_Virtual_Product__c FROM Product2 WHERE NAME = 'MTRNTCAGS-12MOS'];
        virtualProd.Is_Virtual_Product__c = true;
        update virtualProd;
        
        //Create Pricebook EntryPair
        Map<Id, Decimal> productIdToPriceMap = new Map<Id, Decimal>();
        for(String productName : products.keySet()){
            productIdToPriceMap.put(products.get(productName), 125.00);
            
        }
        
        Map<Id, Id> productIdToPbeId = ClsTestDataFactory.createCustomPricebookEntriesCA(productIdToPriceMap, customPricebookId);
        List<PricebookEntry> lstPBE = [SELECT Id, Pricebook2Id, Product2Id FROM PricebookEntry WHERE Pricebook2.Name = 'CAN G6 SUBSCRIPTION 12MOS Auto Renewal'];
        Id caRecdTypeId = Schema.SObjectType.SSIP_Rule__c.getRecordTypeInfosByDeveloperName().get('CA_SSIP_Rule').getRecordTypeId();
        Date tenDate= date.today().adddays(60);
        SSIP_Rule__c ssip = new SSIP_Rule__c();
        ssip.RecordTypeId=caRecdTypeId;
        ssip.Account__c=consumerAccts[0].Id;
        ssip.Renewal_Date__c  =tenDate;
        ssip.Country__c='Canada';
        ssip.Price_Book__c = customPricebookId;
        ssip.PriceBookEntryId__c =lstPBE[0].id;
        ssip.product__c=products.get('MTRNTCAGS-12MOS');
        ssip.Status__c='Active';
        insert ssip;
        
        Marketing_interaction__c mi = new Marketing_interaction__c();
        mi.Account__c = consumerAccts[0].Id;
        mi.Communication_Type__c = 'CA - Subscription Renewal - Auto';
        mi.Country__c = 'Canada';
        mi.CurrencyIsoCode = 'CAD';
        mi.Source_Record_Id__c = ssip.Id;
        mi.Related_Information__c = String.valueOf(ssip.Renewal_Date__c);
        insert mi;
        Datetime beforeSixMon = Datetime.now().addDays(-98);
        Test.setCreatedDate(mi.Id, beforeSixMon);
        Test.startTest();
        BclsMarketingInteractionCARenewalBatch sbatch = new BclsMarketingInteractionCARenewalBatch();
        Id batchInstanceId = Database.executeBatch(sbatch, 1);
        
        Test.stopTest();
    }
}