Prod-EU/force-app/main/default/objects/Account/fields/Price_Book__c.field-meta.xml
<CustomField>
    <fullName>Price_Book__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Price Book</label>
    <referenceTo>Pricebook2</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

Prod-EU/force-app/main/default/objects/Marketing_Interaction__c/Marketing_Interaction__c.object-meta.xml
<CustomObject>
    <description>Object used to trigger journeys in Marketing Cloud.</description>
    <label>Marketing Interaction</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Marketing Interaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Marketing Interactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Prod-EU/force-app/main/default/objects/Marketing_Interaction__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Marketing Interactions</relationshipLabel>
    <relationshipName>Marketing_Interactions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

Prod-EU/force-app/main/default/objects/Marketing_Interaction__c/fields/Communication_Type__c.field-meta.xml
<CustomField>
    <fullName>Communication_Type__c</fullName>
    <label>Communication Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CA - Customer Onboarding</fullName>
            </value>
            <value>
                <fullName>CA - Product Onboarding - G5</fullName>
            </value>
            <value>
                <fullName>CA - Reorder Reminder - G5</fullName>
            </value>
            <value>
                <fullName>CA - Product Onboarding - G6</fullName>
            </value>
            <value>
                <fullName>CA - Reorder Reminder - G6 Starter Kit</fullName>
            </value>
            <value>
                <fullName>CA - Subscription Renewal - Signature</fullName>
            </value>
            <value>
                <fullName>CA - Subscription Renewal - Auto</fullName>
            </value>
            <value>
                <fullName>CA - Subscription Upsell - G6</fullName>
            </value>
            <value>
                <fullName>UKIE - Customer Onboarding - G6</fullName>
            </value>
            <value>
                <fullName>UKIE - Customer Review</fullName>
            </value>
            <value>
                <fullName>UKIE - Warrior Recruitment</fullName>
            </value>
            <value>
                <fullName>UKIE - Subscription Renewal - G6</fullName>
            </value>
            <value>
                <fullName>UKIE - Subscription Upsell - G6</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Prod-EU/force-app/main/default/objects/Marketing_Interaction__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <description>Country should always be required for all records entered in this object.</description>
    <label>Country</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country</valueSetName>
    </valueSet>
</CustomField>

Prod-EU/force-app/main/default/objects/Marketing_Interaction__c/fields/Related_Information__c.field-meta.xml
<CustomField>
    <fullName>Related_Information__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Related Information</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

Prod-EU/force-app/main/default/objects/Marketing_Interaction__c/fields/Source_Record_Id__c.field-meta.xml
<CustomField>
    <fullName>Source_Record_Id__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Source Record Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

Prod-EU/force-app/main/default/objects/SSIP_Rule__c/SSIP_Rule__c.object-meta.xml
<CustomObject>
    <description>Object stores all SSIP rule for the customers.</description>
    <label>SSIP Rule</label>
    <nameField>
        <displayFormat>SP-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SSIP Rule</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Prod-EU/force-app/main/default/objects/SSIP_Rule__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Master detail relationship to the account.</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>SSIP Rule</relationshipLabel>
    <relationshipName>SSIP_Rule</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Prod-EU/force-app/main/default/objects/SSIP_Rule__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <description>Country to which this rule is tied to</description>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country</valueSetName>
    </valueSet>
</CustomField>

Prod-EU/force-app/main/default/objects/SSIP_Rule__c/fields/Price_Book__c.field-meta.xml
<CustomField>
    <fullName>Price_Book__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Price book, which will filter out only SSIP Pricebooks</description>
    <label>Price Book</label>
    <referenceTo>Pricebook2</referenceTo>
    <relationshipLabel>SSIP Rule</relationshipLabel>
    <relationshipName>SSIP_Rule</relationshipName>
    <type>Lookup</type>
</CustomField>

Prod-EU/force-app/main/default/objects/SSIP_Rule__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>SSIP Rule</relationshipLabel>
    <relationshipName>SSIP_Rule</relationshipName>
    <type>Lookup</type>
</CustomField>

Prod-EU/force-app/main/default/objects/SSIP_Rule__c/fields/Renewal_Date__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Date__c</fullName>
    <description>Date when the contract can be renewed</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Date should be greater than or equal to today&apos;s date.</inlineHelpText>
    <label>Renewal Date</label>
    <type>Date</type>
</CustomField>

Prod-EU/force-app/main/default/objects/SSIP_Rule__c/fields/Rule_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Rule_End_Date__c</fullName>
    <description>Date when the rule will end.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Date should be greater than or equal to today&apos;s date. Setting this date will delete any open schedules past this date.</inlineHelpText>
    <label>Rule End Date</label>
    <type>Date</type>
</CustomField>

Prod-EU/force-app/main/default/objects/SSIP_Rule__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&apos;Active&apos;</defaultValue>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Prod-EU/force-app/main/default/classes/BclsMarketingInteractionCARuleEndBatch.cls
global class BclsMarketingInteractionCARuleEndBatch implements database.Batchable<SObject>  { 
    global Database.QueryLocator start(Database.BatchableContext bc){
        Date CANoRuleEndNxt90Date = date.today().adddays(90); 
        Date CANoRuleRenwlNxt85Date = date.today().adddays(85);
        Date CANoRuleRenwlNxt95Date = date.today().adddays(95);
        String SSIPQuery = 'SELECT Id, Account__c, Account__r.Id, Renewal_Date__c,Rule_End_Date__c, ' ;
        SSIPQuery += ' Product__c, Product__r.Name, Account__r.RecordType.DeveloperName,Price_Book__r.Name ';
        SSIPQuery += ' from SSIP_Rule__c' ;
        SSIPQuery += ' WHERE (Status__c=\'Active\') AND (Account__r.RecordType.DeveloperName =\'CA_Consumer\')';
        //SSIPQuery += ' AND (Product__r.Name =\'MTRNTCAGS-12MOS\')';
        SSIPQuery += ' AND (Product__r.Name =\'MTRNTCAGS-12MOS\') AND (Rule_End_Date__c>=:CANoRuleRenwlNxt85Date AND Rule_End_Date__c<=:CANoRuleRenwlNxt95Date)';
        SSIPQuery += ' AND (Price_Book__r.Name =\'CAN G6 SUBSCRIPTION 12MOS NO Renewal\')';
        
        System.debug('--SSIPQuery--'+SSIPQuery);
        return Database.getQueryLocator(SSIPQuery);
   }
     global void execute(Database.BatchableContext bc, List<SObject> scope){
         
        System.debug('**scope--'+scope.size()); 
        Date sixDate= date.today();
        sixdate=sixdate.addmonths(-6);
        
        List<id> validDateId=new list<id>();
        map<id, SSIP_Rule__c> idToSSIP= new map<id,SSIP_Rule__c>();
        
        for(SSIP_Rule__c a : (List<SSIP_Rule__c>)scope){
            if(string.isNotBlank(a.Rule_End_Date__c.format())){              
                validDateId.add(a.Account__r.Id);
                idToSSIP.put(a.Account__r.Id, a);
            }
        }
        for(marketing_interaction__c mi: [SELECT id, Account__c, CreatedDate FROM marketing_interaction__c WHERE account__c in :validDateId AND 
                                          Communication_Type__c='CA - Subscription Renewal - Signature' ]){
                                              if(mi.CreatedDate>sixDate){
                                                  if(idToSSIP.containskey(mi.account__c)){
                                                      idToSSIP.remove(mi.account__c);
                                                  }
                                              }
                                          }
        List<marketing_interaction__c> newMI = new list<marketing_interaction__c>();
        for(SSIP_Rule__c a :idToSSIP.values()){
            marketing_interaction__c mi = new marketing_interaction__c();
            mi.Account__c=a.Account__r.Id;
            mi.Communication_Type__c='CA - Subscription Renewal - Signature';
            mi.Source_Record_Id__c=a.id;
            mi.Related_Information__c=a.Rule_End_Date__c.format();
            if(a.Account__r.RecordType.DeveloperName =='CA_Consumer'){
                mi.Country__c='Canada';
            }
            newMI.add(mi);
        }
        insert newMI;
        //System.debug('**MI Records To Insert-->'+newMI); 
    }
    global void finish(Database.BatchableContext bc){
        System.debug('BClsMIRuleEndBatch_V1 -- Batch Execution Finished!!!');
    }
}