Prod-EU/force-app/main/default/objects/Account/fields/Price_Book__c.field-meta.xml
<CustomField>
    <fullName>Price_Book__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Price Book</label>
    <referenceTo>Pricebook2</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

Prod-EU/force-app/main/default/objects/Account/fields/System_Of_Origin__c.field-meta.xml
<CustomField>
    <fullName>System_Of_Origin__c</fullName>
    <defaultValue>&apos;crm&apos;</defaultValue>
    <encryptionScheme>None</encryptionScheme>
    <label>System Of Origin</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

Prod-EU/force-app/main/default/objects/Account/fields/System_Of_Origin_Id__c.field-meta.xml
<CustomField>
    <fullName>System_Of_Origin_Id__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>System Of Origin ID</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

Prod-EU/force-app/main/default/objects/Address__c/Address__c.object-meta.xml
<CustomObject>
    <description>Created this custom object to track Address information.</description>
    <label>Address</label>
    <nameField>
        <displayFormat>A-{0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Prod-EU/force-app/main/default/objects/Address__c/fields/Address_Line_1__c.field-meta.xml
<CustomField>
    <fullName>Address_Line_1__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Straße, Hausnummer</inlineHelpText>
    <label>Address Line 1</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

Prod-EU/force-app/main/default/objects/Address__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>City</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

Prod-EU/force-app/main/default/objects/Address__c/fields/Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Postal_Code__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Postal Code</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

Prod-EU/force-app/main/default/objects/Address__c/fields/Primary_Flag__c.field-meta.xml
<CustomField>
    <fullName>Primary_Flag__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Primary</label>
    <type>Checkbox</type>
</CustomField>

Prod-EU/force-app/main/default/objects/Address__c/fields/System_Of_Origin__c.field-meta.xml
<CustomField>
    <fullName>System_Of_Origin__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>System Of Origin</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

Prod-EU/force-app/main/default/objects/Address__c/fields/System_Of_Origin_Id__c.field-meta.xml
<CustomField>
    <fullName>System_Of_Origin_Id__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>System Of Origin ID</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

Prod-EU/force-app/main/default/objects/Address__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Bill To</fullName>
            </value>
            <value>
                <fullName>Ship To</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Prod-EU/force-app/main/default/objects/Address__c/recordTypes/CA_Address.recordType-meta.xml
<RecordType>
    <fullName>CA_Address</fullName>
    <active>true</active>
    <description>Canadian Address</description>
    <label>CA Address</label>
</RecordType>

Prod-EU/force-app/main/default/objects/Address__c/recordTypes/CH_Address.recordType-meta.xml
<RecordType>
    <fullName>CH_Address</fullName>
    <active>true</active>
    <description>Switzerland Address</description>
    <label>CH Address</label>
</RecordType>

Prod-EU/force-app/main/default/objects/SSIP_Rule__c/SSIP_Rule__c.object-meta.xml
<CustomObject>
    <description>Object stores all SSIP rule for the customers.</description>
    <label>SSIP Rule</label>
    <nameField>
        <displayFormat>SP-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SSIP Rule</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Prod-EU/force-app/main/default/objects/SSIP_Rule__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Master detail relationship to the account.</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>SSIP Rule</relationshipLabel>
    <relationshipName>SSIP_Rule</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Prod-EU/force-app/main/default/objects/SSIP_Rule__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <description>Country to which this rule is tied to</description>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country</valueSetName>
    </valueSet>
</CustomField>

Prod-EU/force-app/main/default/objects/SSIP_Rule__c/fields/First_Order__c.field-meta.xml
<CustomField>
    <fullName>First_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>First Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>SSIP Rule</relationshipLabel>
    <relationshipName>SSIP_Rule</relationshipName>
    <type>Lookup</type>
</CustomField>

Prod-EU/force-app/main/default/objects/SSIP_Rule__c/fields/First_Repeat_Order_Lead_Days__c.field-meta.xml
<CustomField>
    <fullName>First_Repeat_Order_Lead_Days__c</fullName>
    <inlineHelpText>Lead days for the first shipment</inlineHelpText>
    <label>First Repeat Order Lead Days</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Prod-EU/force-app/main/default/objects/SSIP_Rule__c/fields/First_Shipment_Date__c.field-meta.xml
<CustomField>
    <fullName>First_Shipment_Date__c</fullName>
    <description>Date when the first shipment needs to happen for this Schedule. It cam be immediate or in the future and should fall between the Rule Start and End date.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Date should be within the Rule Start Date and Rule End Date (if applicable). This date is set with the first order is shipped. Setting this date will create the Schedules.</inlineHelpText>
    <label>First Shipment Date</label>
    <type>Date</type>
</CustomField>

Prod-EU/force-app/main/default/objects/SSIP_Rule__c/fields/Frequency_In_Days__c.field-meta.xml
<CustomField>
    <fullName>Frequency_In_Days__c</fullName>
    <description>Schedule interval between each shipments.</description>
    <label>Frequency (In Days)</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Prod-EU/force-app/main/default/objects/SSIP_Rule__c/fields/Price_Book__c.field-meta.xml
<CustomField>
    <fullName>Price_Book__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Price book, which will filter out only SSIP Pricebooks</description>
    <label>Price Book</label>
    <referenceTo>Pricebook2</referenceTo>
    <relationshipLabel>SSIP Rule</relationshipLabel>
    <relationshipName>SSIP_Rule</relationshipName>
    <type>Lookup</type>
</CustomField>

Prod-EU/force-app/main/default/objects/SSIP_Rule__c/fields/PriceBookEntryId__c.field-meta.xml
<CustomField>
    <fullName>PriceBookEntryId__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>PriceBookEntryId</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

Prod-EU/force-app/main/default/objects/SSIP_Rule__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>SSIP Rule</relationshipLabel>
    <relationshipName>SSIP_Rule</relationshipName>
    <type>Lookup</type>
</CustomField>

Prod-EU/force-app/main/default/objects/SSIP_Rule__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <description>Product quantity populated based on the product that is chosen. Information is recorded in the pricebook entry level.</description>
    <label>Quantity</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Prod-EU/force-app/main/default/objects/SSIP_Rule__c/fields/Rule_Re_schedule_Date__c.field-meta.xml
<CustomField>
    <fullName>Rule_Re_schedule_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Rule Re-schedule Date</label>
    <type>Date</type>
</CustomField>

Prod-EU/force-app/main/default/objects/SSIP_Rule__c/fields/Schedule_Count__c.field-meta.xml
<CustomField>
    <fullName>Schedule_Count__c</fullName>
    <description>Field holds the number of Schedules that can be created for this rule.</description>
    <inlineHelpText>Count determines how many schedules will be created at first for this Rule.</inlineHelpText>
    <label>Schedule Count</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Prod-EU/force-app/main/default/objects/SSIP_Rule__c/fields/Shipping_Address__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Address__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>List of all Ship To addresses tied to the customer.</description>
    <label>Shipping Address</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Address__c.Account__c</field>
            <operation>equals</operation>
            <valueField>$Source.Account__c</valueField>
        </filterItems>
        <filterItems>
            <field>Address__c.Type__c</field>
            <operation>equals</operation>
            <value>Ship To</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Address__c</referenceTo>
    <relationshipLabel>SSIP Rule</relationshipLabel>
    <relationshipName>SSIP_Rule</relationshipName>
    <type>Lookup</type>
</CustomField>

Prod-EU/force-app/main/default/objects/SSIP_Rule__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&apos;Active&apos;</defaultValue>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Prod-EU/force-app/main/default/objects/SSIP_Rule__c/recordTypes/CA_SSIP_Rule.recordType-meta.xml
<RecordType>
    <fullName>CA_SSIP_Rule</fullName>
    <active>true</active>
    <label>CA SSIP Rule</label>
</RecordType>

Prod-EU/force-app/main/default/objects/SSIP_Rule__c/recordTypes/CH_SSIP_Rule.recordType-meta.xml
<RecordType>
    <fullName>CH_SSIP_Rule</fullName>
    <active>true</active>
    <description>SSIP Rule Recordtype for CH</description>
    <label>CH SSIP Rule</label>
</RecordType>

Prod-EU/force-app/main/default/objects/SSIP_Schedule__c/SSIP_Schedule__c.object-meta.xml
<CustomObject>
    <description>Object stores all the schedules related to the rule.</description>
    <label>SSIP Schedule</label>
    <nameField>
        <displayFormat>SP-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SSIP Schedule</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Prod-EU/force-app/main/default/objects/SSIP_Schedule__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Will be referencing the grand parent and will be defaulted at the time of the Schedule creation. Need this for constraining the addressed tied to the customer.</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>SSIP Schedule</relationshipLabel>
    <relationshipName>SSIP_Schedule</relationshipName>
    <type>Lookup</type>
</CustomField>

Prod-EU/force-app/main/default/objects/SSIP_Schedule__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <description>Will be defaulted from SSIP Rule at the time of creation.</description>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country</valueSetName>
    </valueSet>
</CustomField>

Prod-EU/force-app/main/default/objects/SSIP_Schedule__c/fields/First_Shipment_Date__c.field-meta.xml
<CustomField>
    <fullName>First_Shipment_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Scheduled Shipment Date</label>
    <type>Date</type>
</CustomField>

Prod-EU/force-app/main/default/objects/SSIP_Schedule__c/fields/Price_Book__c.field-meta.xml
<CustomField>
    <fullName>Price_Book__c</fullName>
    <formula>IF(  NOT(ISBLANK(Order__c))  , 
 HYPERLINK(&quot;/&quot;+     Order__r.Pricebook2.Id, Order__r.Pricebook2.Name, &quot;_blank&quot;), 
 HYPERLINK(&quot;/&quot;+SSIP_Rule__r.Price_Book__c, SSIP_Rule__r.Price_Book__r.Name, &quot;_blank&quot;)   )</formula>
    <label>Price Book</label>
    <type>Text</type>
</CustomField>

Prod-EU/force-app/main/default/objects/SSIP_Schedule__c/fields/Schedule_Date__c.field-meta.xml
<CustomField>
    <fullName>Schedule_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Date when the Order will be shipped.</inlineHelpText>
    <label>Schedule Date</label>
    <type>Date</type>
</CustomField>

Prod-EU/force-app/main/default/objects/SSIP_Schedule__c/fields/Shipping_Address__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Address__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>List of all Ship To addresses tied to the customer.</description>
    <inlineHelpText>This address will be used as Shipping address for the Order. If this field is not filled in then default Primary Shipping address tied to the account will be chosen.</inlineHelpText>
    <label>Changed Shipping Address</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Address__c.Account__c</field>
            <operation>equals</operation>
            <valueField>$Source.Account__c</valueField>
        </filterItems>
        <filterItems>
            <field>Address__c.Type__c</field>
            <operation>equals</operation>
            <value>Ship To</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Address__c</referenceTo>
    <relationshipLabel>SSIP Schedule</relationshipLabel>
    <relationshipName>SSIP_Schedule</relationshipName>
    <type>Lookup</type>
</CustomField>

Prod-EU/force-app/main/default/objects/SSIP_Schedule__c/fields/SSIP_Rule__c.field-meta.xml
<CustomField>
    <fullName>SSIP_Rule__c</fullName>
    <description>Master Detail relationship to the parent Rule.</description>
    <label>SSIP Rule</label>
    <referenceTo>SSIP_Rule__c</referenceTo>
    <relationshipLabel>SSIP Schedule</relationshipLabel>
    <relationshipName>SSIP_Schedule</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Prod-EU/force-app/main/default/objects/SSIP_Schedule__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&apos;Open&apos;</defaultValue>
    <description>Will be defaulted to Open. Depending on the Order processing other values will be set.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>In Error</fullName>
            </value>
            <value>
                <fullName>In Draft</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Prod-EU/force-app/main/default/classes/ClsSSIPRuleRenewal_Test.cls
@isTest
public class ClsSSIPRuleRenewal_Test {
    
    @isTest static void TestOrderCreationAndUpdateCA(){
        
        //Insert 1 consumer account record
        List<Account> consumerAccts = ClsTestDataFactory.createAccountsWithBillingAddress(1, 'CA Consumer', 'Canada');
        System.debug('**consumerAccts--'+consumerAccts);
        //Create Pricebook
        Map<String, Id> customPricebookMap = ClsTestDataFactory.createCustomPricebook(new List <String>{'CA Cash'});
        String customPricebookId = customPricebookMap.get('CA Cash');
        
        //Create Products
        Map<String, Id> products = ClsTestDataFactory.createProducts(new List<String> {'MTLYCHARGE', 'STT-GF-006', 'DEX-SHIP-02'});
        
        //Update the virtual sku productIdToPbeId
        Product2 virtualProd = [SELECT Id, Is_Virtual_Product__c FROM Product2 WHERE NAME = 'MTLYCHARGE'];
        virtualProd.Is_Virtual_Product__c = true;
        update virtualProd;
        
        //Create Pricebook EntryPair
        Map<Id, Decimal> productIdToPriceMap = new Map<Id, Decimal>();
        for(String productName : products.keySet()){
            productIdToPriceMap.put(products.get(productName), 125.00);
            
        }
        Map<Id, Id> productIdToPbeId = ClsTestDataFactory.createCustomPricebookEntriesCA(productIdToPriceMap, customPricebookId);
        Id caOrderRecdTypeId = Schema.SObjectType.Order.getRecordTypeInfosByDeveloperName().get('CA_Sales_Order').getRecordTypeId();
        Id caSSIPRecdTypeId = Schema.SObjectType.SSIP_Rule__c.getRecordTypeInfosByDeveloperName().get('CA_SSIP_Rule').getRecordTypeId();
        Id CASAddreRedTypeId = Schema.SObjectType.Address__c.getRecordTypeInfosByDeveloperName().get('CA_Address').getRecordTypeId();
        List<Address__c> lstAddress = new List<Address__c>{
            new Address__c(Account__c = consumerAccts[0].Id,RecordtypeId=CASAddreRedTypeId,Type__c = 'Bill To', Country__c = 'Canada', City__c = 'Victoria', Address_Line_1__c = 'W Higgins Rd', Postal_Code__c = 'V5Z 2M9', Primary_Flag__c = true, System_Of_Origin__c = '12345', System_Of_Origin_Id__c = 'abcdefg'),
                new Address__c(Account__c = consumerAccts[0].Id,RecordtypeId=CASAddreRedTypeId,Type__c = 'Ship To',Country__c = 'Canada', City__c = 'Victoria', Address_Line_1__c = 'W Higgins Rd', Postal_Code__c = 'V5Z 2M9', Primary_Flag__c = true, System_Of_Origin__c = '12345', System_Of_Origin_Id__c = 'abcdefg')
                // new Address__c(Account__c = payorAccount.Id,Type__c = 'Bill To', Country__c = 'Canada', City__c = 'Rosemont', Address_Line_1__c = 'W Higgins Rd', Postal_Code__c = '60089', Primary_Flag__c = true, System_Of_Origin__c = '12345', System_Of_Origin_Id__c = 'abcdefg'),
                //new Address__c(Account__c = payorAccount.Id,Type__c = 'Ship To',Country__c = 'Canada', City__c = 'Rosemont', Address_Line_1__c = ' W Higgins Rd', Postal_Code__c = '60089', Primary_Flag__c = true, System_Of_Origin__c = '12345', System_Of_Origin_Id__c = 'abcdefg')
                };
                    insert lstAddress;
        
        List<PricebookEntry> lstPBE = [SELECT Id, Pricebook2Id, Product2Id FROM PricebookEntry WHERE Pricebook2.Name = 'CA Cash'];
        System.debug('lstPBE--'+lstPBE.size());
        List<SSIP_Rule__c> lstSSIPRule = new List<SSIP_Rule__c>();
        
        Date firstDayOfMonth = System.today().toStartOfMonth();
        Date lastDayOfMonth = firstDayOfMonth.addDays(Date.daysInMonth(firstDayOfMonth.year(), firstDayOfMonth.month()) - 1);
        Integer counter = 0;
        //for(PricebookEntry pbe : lstPBE){
        for(Integer i =0 ;i<3;i++){
            lstSSIPRule.add(new SSIP_Rule__c(Account__c = consumerAccts[0].Id,  Schedule_Count__c = 3, Frequency_In_Days__c = 30, //First_Order__c = null,
                                             First_Repeat_Order_Lead_Days__c = 7, Price_Book__c = lstPBE[i].Pricebook2Id, PriceBookEntryId__c = lstPBE[i].Id,
                                             First_Shipment_Date__c = Date.today(),Rule_Re_schedule_Date__c = Date.today()+1,RecordTypeId=caSSIPRecdTypeId,
                                             Country__c = 'Canada',
                                             Product__c = lstPBE[i].Product2Id, Quantity__c = 1, Shipping_Address__c = null, Status__c = 'Active'));
        }
        
        
        
        //}
        Test.startTest();
        insert lstSSIPRule;
        //System.debug('**Date--'+;
        for(SSIP_Rule__c ssipRule : lstSSIPRule){
            ssipRule.Rule_End_Date__c = Date.today()+100;
        }
        
        List<SSIP_Schedule__c> lstSSIPSchedule2 = [SELECT Id,Account__c FROM SSIP_Schedule__c where Account__c=:consumerAccts[0].Id Limit 2];
        for(SSIP_Schedule__c ssipSchedule : lstSSIPSchedule2){
            ssipSchedule.Status__c = 'In Progress';
            
        }
        System.debug('====lstSSIPSchedule2===='+lstSSIPSchedule2);
        update lstSSIPSchedule2;
        
        
        //update lstSSIPRule;
        List<SSIP_Schedule__c> lstSSIPSchedule = [SELECT Id,Account__c FROM SSIP_Schedule__c where Account__c=:consumerAccts[0].Id limit 1];
        for(SSIP_Schedule__c ssipSchedule : lstSSIPSchedule){
            ssipSchedule.Status__c = 'Open';
            
        }
        System.debug('====lstSSIPSchedule===='+lstSSIPSchedule);
        update lstSSIPSchedule;
        
        for(SSIP_Rule__c ssipRule : lstSSIPRule){
            ssipRule.Rule_End_Date__c = Date.today()+100;
        }
        update lstSSIPRule;
        
        test.stopTest();
    }
    @isTest static void TestOrderCreationAndUpdateCA2(){        
        //Insert 1 consumer account record
        List<Account> consumerAccts = ClsTestDataFactory.createAccountsWithBillingAddress(1, 'CA Consumer', 'Canada');
        System.debug('**consumerAccts--'+consumerAccts);
        //Create Pricebook
        Map<String, Id> customPricebookMap = ClsTestDataFactory.createCustomPricebook(new List <String>{'CA Cash'});
        String customPricebookId = customPricebookMap.get('CA Cash');
        
        //Create Products
        Map<String, Id> products = ClsTestDataFactory.createProducts(new List<String> {'MTLYCHARGE', 'STT-GF-006', 'DEX-SHIP-02'});
        
        //Update the virtual sku productIdToPbeId
        Product2 virtualProd = [SELECT Id, Is_Virtual_Product__c FROM Product2 WHERE NAME = 'MTLYCHARGE'];
        virtualProd.Is_Virtual_Product__c = true;
        update virtualProd;
        
        //Create Pricebook EntryPair
        Map<Id, Decimal> productIdToPriceMap = new Map<Id, Decimal>();
        for(String productName : products.keySet()){
            productIdToPriceMap.put(products.get(productName), 125.00);
            
        }
        Map<Id, Id> productIdToPbeId = ClsTestDataFactory.createCustomPricebookEntriesCA(productIdToPriceMap, customPricebookId);
        Id caOrderRecdTypeId = Schema.SObjectType.Order.getRecordTypeInfosByDeveloperName().get('CA_Sales_Order').getRecordTypeId();
        Id caSSIPRecdTypeId = Schema.SObjectType.SSIP_Rule__c.getRecordTypeInfosByDeveloperName().get('CA_SSIP_Rule').getRecordTypeId();
        Id CASAddreRedTypeId = Schema.SObjectType.Address__c.getRecordTypeInfosByDeveloperName().get('CA_Address').getRecordTypeId();
        List<Address__c> lstAddress = new List<Address__c>{
            new Address__c(Account__c = consumerAccts[0].Id,RecordtypeId=CASAddreRedTypeId,Type__c = 'Bill To', Country__c = 'Canada', City__c = 'Victoria', Address_Line_1__c = 'W Higgins Rd', Postal_Code__c = 'V5Z 2M9', Primary_Flag__c = true, System_Of_Origin__c = '12345', System_Of_Origin_Id__c = 'abcdefg'),
                new Address__c(Account__c = consumerAccts[0].Id,RecordtypeId=CASAddreRedTypeId,Type__c = 'Ship To',Country__c = 'Canada', City__c = 'Victoria', Address_Line_1__c = 'W Higgins Rd', Postal_Code__c = 'V5Z 2M9', Primary_Flag__c = true, System_Of_Origin__c = '12345', System_Of_Origin_Id__c = 'abcdefg')
                // new Address__c(Account__c = payorAccount.Id,Type__c = 'Bill To', Country__c = 'Canada', City__c = 'Rosemont', Address_Line_1__c = 'W Higgins Rd', Postal_Code__c = '60089', Primary_Flag__c = true, System_Of_Origin__c = '12345', System_Of_Origin_Id__c = 'abcdefg'),
                //new Address__c(Account__c = payorAccount.Id,Type__c = 'Ship To',Country__c = 'Canada', City__c = 'Rosemont', Address_Line_1__c = ' W Higgins Rd', Postal_Code__c = '60089', Primary_Flag__c = true, System_Of_Origin__c = '12345', System_Of_Origin_Id__c = 'abcdefg')
                };
                    insert lstAddress;
        
        List<PricebookEntry> lstPBE = [SELECT Id, Pricebook2Id, Product2Id FROM PricebookEntry WHERE Pricebook2.Name = 'CA Cash'];
        System.debug('lstPBE--'+lstPBE.size());
        List<SSIP_Rule__c> lstSSIPRule = new List<SSIP_Rule__c>();
        
        Date firstDayOfMonth = System.today().toStartOfMonth();
        Date lastDayOfMonth = firstDayOfMonth.addDays(Date.daysInMonth(firstDayOfMonth.year(), firstDayOfMonth.month()) - 1);
        Integer counter = 0;
        //for(PricebookEntry pbe : lstPBE){
        for(Integer i =0 ;i<3;i++){
            lstSSIPRule.add(new SSIP_Rule__c(Account__c = consumerAccts[0].Id,  Schedule_Count__c = 3, Frequency_In_Days__c = 30, //First_Order__c = null,
                                             First_Repeat_Order_Lead_Days__c = 7, Price_Book__c = lstPBE[i].Pricebook2Id, PriceBookEntryId__c = lstPBE[i].Id,
                                             First_Shipment_Date__c = Date.today(),Rule_Re_schedule_Date__c = Date.today()+1,RecordTypeId=caSSIPRecdTypeId,
                                             Country__c = 'Canada',
                                             Product__c = lstPBE[i].Product2Id, Quantity__c = 1, Shipping_Address__c = null, Status__c = 'Active'));
        }
        
        
        
        //}
        Test.startTest();
        insert lstSSIPRule;
        //System.debug('**Date--'+;
        for(SSIP_Rule__c ssipRule : lstSSIPRule){
            ssipRule.Rule_End_Date__c = Date.today()+100;
        }
        
        List<SSIP_Schedule__c> lstSSIPSchedule2 = [SELECT Id,Account__c FROM SSIP_Schedule__c where Account__c=:consumerAccts[0].Id Limit 3];
        for(SSIP_Schedule__c ssipSchedule : lstSSIPSchedule2){
            ssipSchedule.Status__c = 'In Progress';
            
        }
        System.debug('====lstSSIPSchedule2===='+lstSSIPSchedule2);
        update lstSSIPSchedule2;
        
        
        
        for(SSIP_Rule__c ssipRule : lstSSIPRule){
            ssipRule.Rule_End_Date__c = Date.today()+100;
        }
        update lstSSIPRule;
        
        test.stopTest();
    }  
   /* @isTest static void TestOrderCreationAndUpdateCA3(){        
        //Insert 1 consumer account record
        List<Account> consumerAccts = ClsTestDataFactory.createAccountsWithBillingAddress(1, 'CA Consumer', 'Canada');
        System.debug('**consumerAccts--'+consumerAccts);
        //Create Pricebook
        Map<String, Id> customPricebookMap = ClsTestDataFactory.createCustomPricebook(new List <String>{'CA Cash'});
        String customPricebookId = customPricebookMap.get('CA Cash');
        
        //Create Products
        Map<String, Id> products = ClsTestDataFactory.createProducts(new List<String> {'MTLYCHARGE', 'STT-GF-006', 'DEX-SHIP-02'});
        
        //Update the virtual sku productIdToPbeId
        Product2 virtualProd = [SELECT Id, Is_Virtual_Product__c FROM Product2 WHERE NAME = 'MTLYCHARGE'];
        virtualProd.Is_Virtual_Product__c = true;
        update virtualProd;
        
        //Create Pricebook EntryPair
        Map<Id, Decimal> productIdToPriceMap = new Map<Id, Decimal>();
        for(String productName : products.keySet()){
            productIdToPriceMap.put(products.get(productName), 125.00);
            
        }
        Map<Id, Id> productIdToPbeId = ClsTestDataFactory.createCustomPricebookEntriesCA(productIdToPriceMap, customPricebookId);
        Id caOrderRecdTypeId = Schema.SObjectType.Order.getRecordTypeInfosByDeveloperName().get('CA_Sales_Order').getRecordTypeId();
        Id caSSIPRecdTypeId = Schema.SObjectType.SSIP_Rule__c.getRecordTypeInfosByDeveloperName().get('CA_SSIP_Rule').getRecordTypeId();
        Id CASAddreRedTypeId = Schema.SObjectType.Address__c.getRecordTypeInfosByDeveloperName().get('CA_Address').getRecordTypeId();
        List<Address__c> lstAddress = new List<Address__c>{
            new Address__c(Account__c = consumerAccts[0].Id,RecordtypeId=CASAddreRedTypeId,Type__c = 'Bill To', Country__c = 'Canada', City__c = 'Victoria', Address_Line_1__c = 'W Higgins Rd', Postal_Code__c = 'V5Z 2M9', Primary_Flag__c = true, System_Of_Origin__c = '12345', System_Of_Origin_Id__c = 'abcdefg'),
                new Address__c(Account__c = consumerAccts[0].Id,RecordtypeId=CASAddreRedTypeId,Type__c = 'Ship To',Country__c = 'Canada', City__c = 'Victoria', Address_Line_1__c = 'W Higgins Rd', Postal_Code__c = 'V5Z 2M9', Primary_Flag__c = true, System_Of_Origin__c = '12345', System_Of_Origin_Id__c = 'abcdefg')
                // new Address__c(Account__c = payorAccount.Id,Type__c = 'Bill To', Country__c = 'Canada', City__c = 'Rosemont', Address_Line_1__c = 'W Higgins Rd', Postal_Code__c = '60089', Primary_Flag__c = true, System_Of_Origin__c = '12345', System_Of_Origin_Id__c = 'abcdefg'),
                //new Address__c(Account__c = payorAccount.Id,Type__c = 'Ship To',Country__c = 'Canada', City__c = 'Rosemont', Address_Line_1__c = ' W Higgins Rd', Postal_Code__c = '60089', Primary_Flag__c = true, System_Of_Origin__c = '12345', System_Of_Origin_Id__c = 'abcdefg')
                };
                    insert lstAddress;
        
        List<PricebookEntry> lstPBE = [SELECT Id, Pricebook2Id, Product2Id FROM PricebookEntry WHERE Pricebook2.Name = 'CA Cash'];
        System.debug('lstPBE--'+lstPBE.size());
        List<SSIP_Rule__c> lstSSIPRule = new List<SSIP_Rule__c>();
        
        Date firstDayOfMonth = System.today().toStartOfMonth();
        Date lastDayOfMonth = firstDayOfMonth.addDays(Date.daysInMonth(firstDayOfMonth.year(), firstDayOfMonth.month()) - 1);
        Integer counter = 0;
        //for(PricebookEntry pbe : lstPBE){
        for(Integer i =0 ;i<1;i++){
            Date cd = System.today();
            date d = Date.newInstance(cd.year(),cd.month(),29);
            lstSSIPRule.add(new SSIP_Rule__c(Account__c = consumerAccts[0].Id,  Schedule_Count__c = 3, Frequency_In_Days__c = 30, //First_Order__c = null,
                                             First_Repeat_Order_Lead_Days__c = 7, Price_Book__c = lstPBE[i].Pricebook2Id, PriceBookEntryId__c = lstPBE[i].Id,
                                             First_Shipment_Date__c = d,RecordTypeId=caSSIPRecdTypeId,
                                             Country__c = 'Canada',
                                             Product__c = lstPBE[i].Product2Id, Quantity__c = 1, Shipping_Address__c = null, Status__c = 'Active'));
        }
        
        
        
        //}
        Test.startTest();
        insert lstSSIPRule;
        //System.debug('**Date--'+;
        for(SSIP_Rule__c ssipRule : lstSSIPRule){
            ssipRule.Rule_End_Date__c = Date.today()+100;
        }
        
        List<SSIP_Schedule__c> lstSSIPSchedule2 = [SELECT Id,Account__c,Schedule_Date__c FROM SSIP_Schedule__c where Account__c=:consumerAccts[0].Id Limit 3];
        for(SSIP_Schedule__c ssipSchedule : lstSSIPSchedule2){
            ssipSchedule.Status__c = 'In Progress';
            Integer dayofMonth = ssipSchedule.Schedule_Date__c.day();
            if(dayofMonth<28){
                Date cd = System.today();
                date d = Date.newInstance(cd.year(),cd.month(),29);
                ssipSchedule.Schedule_Date__c = d;
            }
            System.debug('--CA3ssipSchedule---'+ssipSchedule.Schedule_Date__c);
            
        }
        System.debug('====lstSSIPSchedule2===='+lstSSIPSchedule2);
        update lstSSIPSchedule2;
        
        
        
        for(SSIP_Rule__c ssipRule : lstSSIPRule){
            ssipRule.Rule_End_Date__c = Date.today()+100;
        }
        update lstSSIPRule;
        
        test.stopTest();
    } */
    @isTest static void TestOrderCreationCH(){        
        //Insert 1 consumer account record
        List<Account> consumerAccts = ClsTestDataFactory.createAccountsWithBillingAddress(1, 'CH Consumer', 'Switzerland');
        System.debug('**consumerAccts--'+consumerAccts);
        //Create Pricebook
        Map<String, Id> customPricebookMap = ClsTestDataFactory.createCustomPricebook(new List <String>{'CH Cash'});
        String customPricebookId = customPricebookMap.get('CH Cash');
        
        //Create Products
        Map<String, Id> products = ClsTestDataFactory.createProducts(new List<String> {'STT-GF-013', 'STT-GF-006', 'DEX-SHIP-02'});
        
        //Update the virtual sku productIdToPbeId
        Product2 virtualProd = [SELECT Id, Is_Virtual_Product__c FROM Product2 WHERE NAME = 'STT-GF-006'];
        virtualProd.Is_Virtual_Product__c = true;
        update virtualProd;
        
        //Create Pricebook EntryPair
        Map<Id, Decimal> productIdToPriceMap = new Map<Id, Decimal>();
        for(String productName : products.keySet()){
            productIdToPriceMap.put(products.get(productName), 125.00);
            
        }
        Map<Id, Id> productIdToPbeId = ClsTestDataFactory.createCustomPricebookEntriesCA(productIdToPriceMap, customPricebookId);
        //Id caOrderRecdTypeId = Schema.SObjectType.Order.getRecordTypeInfosByDeveloperName().get('CA_Sales_Order').getRecordTypeId();
        Id CHSSIPRecdTypeId = Schema.SObjectType.SSIP_Rule__c.getRecordTypeInfosByDeveloperName().get('CH_SSIP_Rule').getRecordTypeId();
        Id CHSAddreRedTypeId = Schema.SObjectType.Address__c.getRecordTypeInfosByDeveloperName().get('CH_Address').getRecordTypeId();
        List<Address__c> lstAddress = new List<Address__c>{
            new Address__c(Account__c = consumerAccts[0].Id,RecordtypeId=CHSAddreRedTypeId,Type__c = 'Bill To', Country__c = 'Switzerland', City__c = 'Rosemont', Address_Line_1__c = 'W Higgins Rd', Postal_Code__c = '60089', Primary_Flag__c = true, System_Of_Origin__c = '12345', System_Of_Origin_Id__c = 'abcdefg'),
                new Address__c(Account__c = consumerAccts[0].Id,RecordtypeId=CHSAddreRedTypeId,Type__c = 'Ship To',Country__c = 'Switzerland', City__c = 'Rosemont', Address_Line_1__c = 'W Higgins Rd', Postal_Code__c = '60089', Primary_Flag__c = true, System_Of_Origin__c = '12345', System_Of_Origin_Id__c = 'abcdefg')
                //new Address__c(Account__c = consumerAccts[0].Id,Type__c = 'Bill To', Country__c = 'Switzerland', City__c = 'Rosemont', Address_Line_1__c = 'W Higgins Rd', Postal_Code__c = '60089', Primary_Flag__c = true, System_Of_Origin__c = '12345', System_Of_Origin_Id__c = 'abcdefg'),
                //new Address__c(Account__c = consumerAccts[0].Id,Type__c = 'Ship To',Country__c = 'Switzerland', City__c = 'Rosemont', Address_Line_1__c = ' W Higgins Rd', Postal_Code__c = '60089', Primary_Flag__c = true, System_Of_Origin__c = '12345', System_Of_Origin_Id__c = 'abcdefg')
                };
                    insert lstAddress;
        
        List<PricebookEntry> lstPBE = [SELECT Id, Pricebook2Id, Product2Id FROM PricebookEntry WHERE Pricebook2.Name = 'CH Cash'];
        System.debug('lstPBE--'+lstPBE.size());
        List<SSIP_Rule__c> lstSSIPRule = new List<SSIP_Rule__c>();
        
        Date firstDayOfMonth = System.today().toStartOfMonth();
        Date lastDayOfMonth = firstDayOfMonth.addDays(Date.daysInMonth(firstDayOfMonth.year(), firstDayOfMonth.month()) - 1);
        Integer counter = 0;
        
        for(Integer i =0 ;i<3;i++){
            lstSSIPRule.add(new SSIP_Rule__c(Account__c = consumerAccts[0].Id,  Schedule_Count__c = 3, Frequency_In_Days__c = 30, //First_Order__c = null,
                                             First_Repeat_Order_Lead_Days__c = 7, Price_Book__c = lstPBE[i].Pricebook2Id, PriceBookEntryId__c = lstPBE[i].Id,
                                             First_Shipment_Date__c = Date.today(),Rule_Re_schedule_Date__c = Date.today()+1,RecordTypeId=CHSSIPRecdTypeId,
                                             Country__c = 'Switzerland',
                                             Product__c = lstPBE[i].Product2Id, Quantity__c = 1, Shipping_Address__c = null, Status__c = 'Active'));
        }
        Test.startTest();
        insert lstSSIPRule;
        
        
        List<SSIP_Schedule__c> lstSSIPSchedule = [SELECT Id,Account__c FROM SSIP_Schedule__c where Account__c=:consumerAccts[0].Id Limit 2];
        for(SSIP_Schedule__c ssipSchedule : lstSSIPSchedule){
            ssipSchedule.Status__c = 'Open';             
        }
        System.debug('====lstSSIPSchedule===='+lstSSIPSchedule);
        update lstSSIPSchedule; 
        
        List<SSIP_Schedule__c> lstSSIPSchedule2 = [SELECT Id,Account__c FROM SSIP_Schedule__c where Account__c=:consumerAccts[0].Id Limit 2];
        for(SSIP_Schedule__c ssipSchedule : lstSSIPSchedule2){
            ssipSchedule.Status__c = 'In Progress';             
        }
        System.debug('====lstSSIPSchedule2===='+lstSSIPSchedule2);
        update lstSSIPSchedule2;
        
        for(SSIP_Rule__c ssipRule : lstSSIPRule){
            ssipRule.Rule_End_Date__c = Date.today()+100;
        }
        update lstSSIPRule;
        
        test.stopTest();
    }
    @isTest static void TestOrderCreationCH2(){        
        //Insert 1 consumer account record
        List<Account> consumerAccts = ClsTestDataFactory.createAccountsWithBillingAddress(1, 'CH Consumer', 'Switzerland');
        System.debug('**consumerAccts--'+consumerAccts);
        //Create Pricebook
        Map<String, Id> customPricebookMap = ClsTestDataFactory.createCustomPricebook(new List <String>{'CH Cash'});
        String customPricebookId = customPricebookMap.get('CH Cash');
        
        //Create Products
        Map<String, Id> products = ClsTestDataFactory.createProducts(new List<String> {'STT-GF-013', 'STT-GF-006', 'DEX-SHIP-02'});
        
        //Update the virtual sku productIdToPbeId
        Product2 virtualProd = [SELECT Id, Is_Virtual_Product__c FROM Product2 WHERE NAME = 'STT-GF-006'];
        virtualProd.Is_Virtual_Product__c = true;
        update virtualProd;
        
        //Create Pricebook EntryPair
        Map<Id, Decimal> productIdToPriceMap = new Map<Id, Decimal>();
        for(String productName : products.keySet()){
            productIdToPriceMap.put(products.get(productName), 125.00);
            
        }
        Map<Id, Id> productIdToPbeId = ClsTestDataFactory.createCustomPricebookEntriesCA(productIdToPriceMap, customPricebookId);
        //Id caOrderRecdTypeId = Schema.SObjectType.Order.getRecordTypeInfosByDeveloperName().get('CA_Sales_Order').getRecordTypeId();
        Id CHSSIPRecdTypeId = Schema.SObjectType.SSIP_Rule__c.getRecordTypeInfosByDeveloperName().get('CH_SSIP_Rule').getRecordTypeId();
        Id CHSAddreRedTypeId = Schema.SObjectType.Address__c.getRecordTypeInfosByDeveloperName().get('CH_Address').getRecordTypeId();
        List<Address__c> lstAddress = new List<Address__c>{
            new Address__c(Account__c = consumerAccts[0].Id,RecordtypeId=CHSAddreRedTypeId,Type__c = 'Bill To', Country__c = 'Switzerland', City__c = 'Rosemont', Address_Line_1__c = 'W Higgins Rd', Postal_Code__c = '60089', Primary_Flag__c = true, System_Of_Origin__c = '12345', System_Of_Origin_Id__c = 'abcdefg'),
                new Address__c(Account__c = consumerAccts[0].Id,RecordtypeId=CHSAddreRedTypeId,Type__c = 'Ship To',Country__c = 'Switzerland', City__c = 'Rosemont', Address_Line_1__c = 'W Higgins Rd', Postal_Code__c = '60089', Primary_Flag__c = true, System_Of_Origin__c = '12345', System_Of_Origin_Id__c = 'abcdefg')
                //new Address__c(Account__c = consumerAccts[0].Id,Type__c = 'Bill To', Country__c = 'Switzerland', City__c = 'Rosemont', Address_Line_1__c = 'W Higgins Rd', Postal_Code__c = '60089', Primary_Flag__c = true, System_Of_Origin__c = '12345', System_Of_Origin_Id__c = 'abcdefg'),
                //new Address__c(Account__c = consumerAccts[0].Id,Type__c = 'Ship To',Country__c = 'Switzerland', City__c = 'Rosemont', Address_Line_1__c = ' W Higgins Rd', Postal_Code__c = '60089', Primary_Flag__c = true, System_Of_Origin__c = '12345', System_Of_Origin_Id__c = 'abcdefg')
                };
                    insert lstAddress;
        
        List<PricebookEntry> lstPBE = [SELECT Id, Pricebook2Id, Product2Id FROM PricebookEntry WHERE Pricebook2.Name = 'CH Cash'];
        System.debug('lstPBE--'+lstPBE.size());
        List<SSIP_Rule__c> lstSSIPRule = new List<SSIP_Rule__c>();
        
        Date firstDayOfMonth = System.today().toStartOfMonth();
        Date lastDayOfMonth = firstDayOfMonth.addDays(Date.daysInMonth(firstDayOfMonth.year(), firstDayOfMonth.month()) - 1);
        Integer counter = 0;
        
        for(Integer i =0 ;i<3;i++){
            lstSSIPRule.add(new SSIP_Rule__c(Account__c = consumerAccts[0].Id,  Schedule_Count__c = 3, Frequency_In_Days__c = 30, //First_Order__c = null,
                                             First_Repeat_Order_Lead_Days__c = 7, Price_Book__c = lstPBE[i].Pricebook2Id, PriceBookEntryId__c = lstPBE[i].Id,
                                             First_Shipment_Date__c = Date.today(),Rule_Re_schedule_Date__c = Date.today()+1,RecordTypeId=CHSSIPRecdTypeId,
                                             Country__c = 'Switzerland',
                                             Product__c = lstPBE[i].Product2Id, Quantity__c = 1, Shipping_Address__c = null, Status__c = 'Active'));
        }
        Test.startTest();
        insert lstSSIPRule;
        
        
        List<SSIP_Schedule__c> lstSSIPSchedule = [SELECT Id,Account__c FROM SSIP_Schedule__c where Account__c=:consumerAccts[0].Id Limit 2];
        for(SSIP_Schedule__c ssipSchedule : lstSSIPSchedule){
            ssipSchedule.Status__c = 'Open';             
        }
        System.debug('====lstSSIPSchedule===='+lstSSIPSchedule);
        //update lstSSIPSchedule; 
        
        List<SSIP_Schedule__c> lstSSIPSchedule2 = [SELECT Id,Account__c FROM SSIP_Schedule__c where Account__c=:consumerAccts[0].Id Limit 3];
        for(SSIP_Schedule__c ssipSchedule : lstSSIPSchedule2){
            ssipSchedule.Status__c = 'In Progress';             
        }
        System.debug('====lstSSIPSchedule2===='+lstSSIPSchedule2);
        update lstSSIPSchedule2;
        
        for(SSIP_Rule__c ssipRule : lstSSIPRule){
            ssipRule.Rule_End_Date__c = Date.today()+100;
        }
        update lstSSIPRule;
        
        test.stopTest();
    }
    
}