Prod-EU/force-app/main/default/objects/Sample_Order_Response_Event__e/Sample_Order_Response_Event__e.object-meta.xml
<CustomObject>
    <label>Sample Order Response Event</label>
    <pluralLabel>Sample Order Response Events</pluralLabel>
</CustomObject>

Prod-EU/force-app/main/default/objects/Sample_Order_Response_Event__e/fields/IntegrationErrorMessage__c.field-meta.xml
<CustomField>
    <fullName>IntegrationErrorMessage__c</fullName>
    <label>IntegrationErrorMessage</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

Prod-EU/force-app/main/default/objects/Sample_Order_Response_Event__e/fields/IntegrationStatus__c.field-meta.xml
<CustomField>
    <fullName>IntegrationStatus__c</fullName>
    <label>IntegrationStatus</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

Prod-EU/force-app/main/default/objects/Sample_Order_Response_Event__e/fields/OCEOrderReference__c.field-meta.xml
<CustomField>
    <fullName>OCEOrderReference__c</fullName>
    <label>OCEOrderReference</label>
    <length>25</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

Prod-EU/force-app/main/default/objects/Sample_Order_Response_Event__e/fields/OrderNumber__c.field-meta.xml
<CustomField>
    <fullName>OrderNumber__c</fullName>
    <label>OrderNumber</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

Prod-EU/force-app/main/default/objects/Sample_Order_Response_Event__e/fields/OrderStatus__c.field-meta.xml
<CustomField>
    <fullName>OrderStatus__c</fullName>
    <label>OrderStatus</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

Prod-EU/force-app/main/default/objects/Sample_Order_Response_Event__e/fields/TrackingUrl__c.field-meta.xml
<CustomField>
    <fullName>TrackingUrl__c</fullName>
    <label>TrackingURL</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

Prod-EU/force-app/main/default/classes/PEClsHandlerOCEEvent.cls
public class PEClsHandlerOCEEvent {
    public static void publishOCEAccOrderEvent(String OCEOrderRefNumber,String OrderNumber,String ordStatus,String OrdtrackingNumber,String IntegrationStatus,String IntegrationMsg){
        System.debug('**SPEOUT--OCE OutEvent Publish Method Call--');
        try{
            Sample_Order_Response_Event__e evtOut = new Sample_Order_Response_Event__e();            
            evtOut.OCEOrderReference__c = OCEOrderRefNumber;
            evtOut.OrderNumber__c = OrderNumber;
            evtOut.OrderStatus__c = ordStatus;                        
            evtOut.TrackingUrl__c = OrdtrackingNumber;
            evtOut.IntegrationErrorMessage__c = IntegrationMsg;
            evtOut.IntegrationStatus__c = IntegrationStatus;            
            Database.SaveResult svrs = EventBus.publish(evtOut);
            if(svrs.isSuccess()){
                System.debug('**SPEOUT--Event Published Successfully');
                ErrorUtility.LogError('Publish', 'PEClsHandlerOCEEvent', 'Writing Event into OCE Out Channel', 'Order', 'crm', 'Succesfully published Event', evtOut.OCEOrderReference__c, 'Success Log');
            }else{
                System.debug('**SPEOUT--Event Failed to Published ');
                ErrorUtility.LogErrorWithEvent('Publish', 'PEClsHandlerOCEEvent','Writing Event into OCE Out Channel', 'Order', 'crm', 'Failed to Publish Event. Error: ' + svrs.getErrors(), evtOut.OrderNumber__c, 'Fatal Error - Bailing out', String.valueOf(evtOut));
            }
        }catch(Exception ex){
            System.debug('**SPEOUT--Error--'+ex);
            System.debug('**SPEOUT--ErrorLine--'+ex.getLineNumber());            
        }       
    }
}