Prod-EU/force-app/main/default/objects/Fund__c/Fund__c.object-meta.xml
<CustomObject>
    <description>Object will track information related to Funded Patients.</description>
    <label>Fund</label>
    <nameField>
        <displayFormat>F-{00000}</displayFormat>
        <label>Fund Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fund</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Prod-EU/force-app/main/default/objects/Fund__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <defaultValue>If(OR(BEGINS($Profile.Name , &apos;UK&apos;), BEGINS($Profile.Name , &apos;System&apos;)), &apos;United Kingdom&apos;, &apos;&apos;)</defaultValue>
    <description>Possible countries that can be selected defaulted based on the Profile</description>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country</valueSetName>
    </valueSet>
</CustomField>

Prod-EU/force-app/main/default/objects/SSIP_Rule__c/SSIP_Rule__c.object-meta.xml
<CustomObject>
    <description>Object stores all SSIP rule for the customers.</description>
    <label>SSIP Rule</label>
    <nameField>
        <displayFormat>SP-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SSIP Rule</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Prod-EU/force-app/main/default/objects/SSIP_Rule__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Master detail relationship to the account.</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>SSIP Rule</relationshipLabel>
    <relationshipName>SSIP_Rule</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Prod-EU/force-app/main/default/objects/SSIP_Rule__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <description>Country to which this rule is tied to</description>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country</valueSetName>
    </valueSet>
</CustomField>

Prod-EU/force-app/main/default/objects/SSIP_Rule__c/fields/First_Order__c.field-meta.xml
<CustomField>
    <fullName>First_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>First Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>SSIP Rule</relationshipLabel>
    <relationshipName>SSIP_Rule</relationshipName>
    <type>Lookup</type>
</CustomField>

Prod-EU/force-app/main/default/objects/SSIP_Rule__c/fields/First_Repeat_Order_Lead_Days__c.field-meta.xml
<CustomField>
    <fullName>First_Repeat_Order_Lead_Days__c</fullName>
    <inlineHelpText>Lead days for the first shipment</inlineHelpText>
    <label>First Repeat Order Lead Days</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Prod-EU/force-app/main/default/objects/SSIP_Rule__c/fields/First_Shipment_Date__c.field-meta.xml
<CustomField>
    <fullName>First_Shipment_Date__c</fullName>
    <description>Date when the first shipment needs to happen for this Schedule. It cam be immediate or in the future and should fall between the Rule Start and End date.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Date should be within the Rule Start Date and Rule End Date (if applicable). This date is set with the first order is shipped. Setting this date will create the Schedules.</inlineHelpText>
    <label>First Shipment Date</label>
    <type>Date</type>
</CustomField>

Prod-EU/force-app/main/default/objects/SSIP_Rule__c/fields/Frequency_In_Days__c.field-meta.xml
<CustomField>
    <fullName>Frequency_In_Days__c</fullName>
    <description>Schedule interval between each shipments.</description>
    <label>Frequency (In Days)</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Prod-EU/force-app/main/default/objects/SSIP_Rule__c/fields/Last_Renewed_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_Renewed_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Last Renewed Date</label>
    <type>Date</type>
</CustomField>

Prod-EU/force-app/main/default/objects/SSIP_Rule__c/fields/Payment_Term__c.field-meta.xml
<CustomField>
    <fullName>Payment_Term__c</fullName>
    <defaultValue>IF( $RecordType.DeveloperName = &apos;CH_SSIP_Rule&apos;, &apos;net30&apos;, &apos;net30&apos;)</defaultValue>
    <description>Payment terms that will be used to track the payment. The default value will be based on the country&apos; preference</description>
    <label>Payment Term</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Payment_Term</valueSetName>
    </valueSet>
</CustomField>

Prod-EU/force-app/main/default/objects/SSIP_Rule__c/fields/Product_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Product Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Prod-EU/force-app/main/default/objects/SSIP_Rule__c/fields/Renewal_Date__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Date__c</fullName>
    <description>Date when the contract can be renewed</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Date should be greater than or equal to today&apos;s date.</inlineHelpText>
    <label>Renewal Date</label>
    <type>Date</type>
</CustomField>

Prod-EU/force-app/main/default/objects/SSIP_Rule__c/fields/Rule_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Rule_End_Date__c</fullName>
    <description>Date when the rule will end.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Date should be greater than or equal to today&apos;s date. Setting this date will delete any open schedules past this date.</inlineHelpText>
    <label>Rule End Date</label>
    <type>Date</type>
</CustomField>

Prod-EU/force-app/main/default/objects/SSIP_Rule__c/fields/Rule_Re_schedule_Date__c.field-meta.xml
<CustomField>
    <fullName>Rule_Re_schedule_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Rule Re-schedule Date</label>
    <type>Date</type>
</CustomField>

Prod-EU/force-app/main/default/objects/SSIP_Rule__c/fields/Schedule_Count__c.field-meta.xml
<CustomField>
    <fullName>Schedule_Count__c</fullName>
    <description>Field holds the number of Schedules that can be created for this rule.</description>
    <inlineHelpText>Count determines how many schedules will be created at first for this Rule.</inlineHelpText>
    <label>Schedule Count</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Prod-EU/force-app/main/default/objects/SSIP_Rule__c/fields/Shipping_Address__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Address__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>List of all Ship To addresses tied to the customer.</description>
    <label>Shipping Address</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Address__c.Account__c</field>
            <operation>equals</operation>
            <valueField>$Source.Account__c</valueField>
        </filterItems>
        <filterItems>
            <field>Address__c.Type__c</field>
            <operation>equals</operation>
            <value>Ship To</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Address__c</referenceTo>
    <relationshipLabel>SSIP Rule</relationshipLabel>
    <relationshipName>SSIP_Rule</relationshipName>
    <type>Lookup</type>
</CustomField>

Prod-EU/force-app/main/default/objects/SSIP_Rule__c/fields/Shipping_Method__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Method__c</fullName>
    <description>Shipping method will be constrained by Country</description>
    <inlineHelpText>Chosen value will be defaulted to all the schedules associated to this Rule.</inlineHelpText>
    <label>Shipping Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Shipping_Method</valueSetName>
    </valueSet>
</CustomField>

Prod-EU/force-app/main/default/objects/SSIP_Rule__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&apos;Active&apos;</defaultValue>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Prod-EU/force-app/main/default/objects/SSIP_Schedule__c/SSIP_Schedule__c.object-meta.xml
<CustomObject>
    <description>Object stores all the schedules related to the rule.</description>
    <label>SSIP Schedule</label>
    <nameField>
        <displayFormat>SP-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SSIP Schedule</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Prod-EU/force-app/main/default/objects/SSIP_Schedule__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Will be referencing the grand parent and will be defaulted at the time of the Schedule creation. Need this for constraining the addressed tied to the customer.</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>SSIP Schedule</relationshipLabel>
    <relationshipName>SSIP_Schedule</relationshipName>
    <type>Lookup</type>
</CustomField>

Prod-EU/force-app/main/default/objects/SSIP_Schedule__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <description>Will be defaulted from SSIP Rule at the time of creation.</description>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country</valueSetName>
    </valueSet>
</CustomField>

Prod-EU/force-app/main/default/objects/SSIP_Schedule__c/fields/First_Shipment_Date__c.field-meta.xml
<CustomField>
    <fullName>First_Shipment_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Scheduled Shipment Date</label>
    <type>Date</type>
</CustomField>

Prod-EU/force-app/main/default/objects/SSIP_Schedule__c/fields/Fund__c.field-meta.xml
<CustomField>
    <fullName>Fund__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Fund</label>
    <referenceTo>Fund__c</referenceTo>
    <relationshipLabel>SSIP Schedule</relationshipLabel>
    <relationshipName>SSIP_Schedule</relationshipName>
    <type>Lookup</type>
</CustomField>

Prod-EU/force-app/main/default/objects/SSIP_Schedule__c/fields/Payment_Term__c.field-meta.xml
<CustomField>
    <fullName>Payment_Term__c</fullName>
    <description>Will be defaulted from Parent SSIP Rule</description>
    <inlineHelpText>Value can be overridden only for this schedule.</inlineHelpText>
    <label>Payment Term</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Payment_Term</valueSetName>
    </valueSet>
</CustomField>

Prod-EU/force-app/main/default/objects/SSIP_Schedule__c/fields/Product_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Name__c</fullName>
    <formula>SSIP_Rule__r.Product__r.Name</formula>
    <inlineHelpText>Product Name tied to the Rule.</inlineHelpText>
    <label>Product Name</label>
    <type>Text</type>
</CustomField>

Prod-EU/force-app/main/default/objects/SSIP_Schedule__c/fields/Schedule_Date__c.field-meta.xml
<CustomField>
    <fullName>Schedule_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Date when the Order will be shipped.</inlineHelpText>
    <label>Schedule Date</label>
    <type>Date</type>
</CustomField>

Prod-EU/force-app/main/default/objects/SSIP_Schedule__c/fields/Shipping_Address__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Address__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>List of all Ship To addresses tied to the customer.</description>
    <inlineHelpText>This address will be used as Shipping address for the Order. If this field is not filled in then default Primary Shipping address tied to the account will be chosen.</inlineHelpText>
    <label>Changed Shipping Address</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Address__c.Account__c</field>
            <operation>equals</operation>
            <valueField>$Source.Account__c</valueField>
        </filterItems>
        <filterItems>
            <field>Address__c.Type__c</field>
            <operation>equals</operation>
            <value>Ship To</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Address__c</referenceTo>
    <relationshipLabel>SSIP Schedule</relationshipLabel>
    <relationshipName>SSIP_Schedule</relationshipName>
    <type>Lookup</type>
</CustomField>

Prod-EU/force-app/main/default/objects/SSIP_Schedule__c/fields/Shipping_Method__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Method__c</fullName>
    <description>Shipping Method will be defaulted based on the country default value.</description>
    <inlineHelpText>Value can be overridden only for this schedule. 
Make sure all other product schedules that will be shipped out on the same day for this account is also chosen the corresponding Shipping method.</inlineHelpText>
    <label>Shipping Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Shipping_Method</valueSetName>
    </valueSet>
</CustomField>

Prod-EU/force-app/main/default/objects/SSIP_Schedule__c/fields/SSIP_Rule__c.field-meta.xml
<CustomField>
    <fullName>SSIP_Rule__c</fullName>
    <description>Master Detail relationship to the parent Rule.</description>
    <label>SSIP Rule</label>
    <referenceTo>SSIP_Rule__c</referenceTo>
    <relationshipLabel>SSIP Schedule</relationshipLabel>
    <relationshipName>SSIP_Schedule</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Prod-EU/force-app/main/default/objects/SSIP_Schedule__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&apos;Open&apos;</defaultValue>
    <description>Will be defaulted to Open. Depending on the Order processing other values will be set.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>In Error</fullName>
            </value>
            <value>
                <fullName>In Draft</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Prod-EU/force-app/main/default/classes/ClsSSIPRuleRenewal.cls
/************************************************************************
* Author - Pravin Jagadale.
* Description - Class will create the Open Schedule Based on Rule End Date Change * 
* NS-1482
* Date - 16/09/2020
***************************************************************************/

public class ClsSSIPRuleRenewal {
    
    public static void handleSSIPRuleRenwal(List<SSIP_Rule__c> lstSSIPRuleNew, Map<Id, SSIP_Rule__c> mapSSIPRuleOld){
        try{
            if( ClsCheckRecursive.runOnce()){  
                System.debug('**handleSSIPRuleRenwal--');
                List<SSIP_Rule__c> lstSSIPUpdate = new List<SSIP_Rule__c>();
                List<SSIP_Schedule__c> lstSSIPScheduleUpdate = new List<SSIP_Schedule__c>();
                List<SSIP_Schedule__c> lstSSIPScheduleUpdate2 = new List<SSIP_Schedule__c>();
                List<SSIP_Schedule__c> lstScheduleInsert = new List<SSIP_Schedule__c>();
                Map<Id, Id> ruleToFundMap = new Map<Id, Id>();
                Set<Id> setSSIPSchedule = new Set<Id>();
                map<Id,List<SSIP_Schedule__c>> mapSSIPSchedule = new Map<Id,List<SSIP_Schedule__c>>();
                List<SSIP_Rule__c> ssipruleLst = [Select id,Renewal_Date__c,Last_Renewed_Date__c,Country__c ,Frequency_In_Days__c,
                                                  Rule_End_Date__c,Rule_Re_schedule_Date__c,Account__c,Payment_Term__c,Shipping_Address__c,
                                                  Shipping_Method__c,Schedule_Count__c,First_Repeat_Order_Lead_Days__c
                                                  from SSIP_rule__c where Id IN:lstSSIPRuleNew];
                
                List<SSIP_Schedule__c> lstSSIPSchedule = [Select id,Schedule_Date__c,SSIP_Rule__c,SSIP_Rule__r.Id,status__c,Product_Name__c
                                                          from SSIP_Schedule__c 
                                                          where SSIP_Rule__c IN:ssipruleLst order by Schedule_Date__c desc ];
                
                for(SSIP_Schedule__c ssipSch: lstSSIPSchedule){
                    if(mapSSIPSchedule.containsKey(ssipSch.SSIP_Rule__c)){
                        List<SSIP_Schedule__c> lst = mapSSIPSchedule.get(ssipSch.SSIP_Rule__c);
                        lst.add(ssipSch);
                        mapSSIPSchedule.put(ssipSch.SSIP_Rule__c,lst);  
                    }else{
                        List<SSIP_Schedule__c> lstadd = new List<SSIP_Schedule__c>();
                        lstadd.add(ssipSch);
                        mapSSIPSchedule.put(ssipSch.SSIP_Rule__c,lstadd);
                    }               
                }
                
                for(SSIP_Rule__c objSSIPRule : [SELECT Id, First_Order__r.Fund__c FROM SSIP_Rule__c WHERE First_Order__c != null AND Id IN: ssipruleLst]){
                    if(objSSIPRule.First_Order__r.Fund__c != null)
                        ruleToFundMap.put(objSSIPRule.Id, objSSIPRule.First_Order__r.Fund__c);
                } 
                for(SSIP_Rule__c ssipIt: ssipruleLst){
                    System.debug('---Processed-ssipIt--'+ssipIt);
                    if (ssipIt.Rule_End_Date__c <= mapSSIPRuleOld.get(ssipIt.Id).Rule_End_Date__c) continue;
                    if(Trigger.isUpdate && ssipIt.Rule_End_Date__c != null && ssipIt.Rule_End_Date__c != mapSSIPRuleOld.get(ssipIt.Id).Rule_End_Date__c){
                        //List<SSIP_Schedule__c> lstRuleScheules = mapSSIPSchedule.get(ssipIt.Id);
                        System.debug('--schedule--'+ssipIt.Schedule_Count__c);
                        Integer scheduleCount = ssipIt.Schedule_Count__c == null ? 3 : Integer.valueOf(ssipIt.Schedule_Count__c);
                        // ssipIt.Schedule_Count__c != 0 || ssipIt.Schedule_Count__c != null ? Integer.valueOf(ssipIt.Schedule_Count__c) : 3;
                        System.debug('--scheduleCount--'+scheduleCount);
                        Integer firstRepeatOrderLeadDays = ssipIt.First_Repeat_Order_Lead_Days__c != null ? Integer.valueOf(ssipIt.First_Repeat_Order_Lead_Days__c) : 0;
                        List<SSIP_Schedule__c> lstSchedules = new List<SSIP_Schedule__c>(); 
                        List<SSIP_Schedule__c> lstopenSchedules = new List<SSIP_Schedule__c>();
                        lstSchedules =  mapSSIPSchedule.get(ssipIt.Id);
                        System.debug('lstScheules--'+lstSchedules);
                        if(lstSchedules != null){
                            lstopenSchedules = checkOpenScheule(lstSchedules);
                        }
                        //List<SSIP_Schedule__c> lstopenScheules = lstScheules.size()>0 ? checkOpenScheule(lstScheules) : new List<SSIP_Schedule__c>();
                        Integer presentOpenSchCount = lstopenSchedules!= null ? lstopenSchedules.size() : 0;
                        System.debug('**presentOpenSchCount--'+presentOpenSchCount);
                        if(presentOpenSchCount > 0 && presentOpenSchCount < scheduleCount){
                            
                            //Find Last Scheudle Date
                            SSIP_Schedule__c scheduleObj = 	findLastShippedDate(lstopenSchedules);
                            Date nexScheduleDate = System.today();
                            System.debug('***scheduleObj.Schedule_Date__c--'+scheduleObj.Schedule_Date__c);
                            Integer daystoAdd = Integer.valueOf(ssipIt.Frequency_In_Days__c);
                            nexScheduleDate = scheduleObj.Schedule_Date__c;//.addDays(daystoAdd);                            
                            Integer dayofMonth = scheduleObj.Schedule_Date__c.Day();
                            String Prdname = scheduleObj.Product_Name__c; 
                            if(ssipIt.Rule_End_Date__c == null || scheduleObj.Schedule_Date__c <= ssipIt.Rule_End_Date__c){
                                if(ssipIt.Country__c == 'Canada' && prdName.startsWith('MT')){
                                    
                                    System.debug('**Canada--');
                                    if(dayofMonth <= 28){
                                        for(Integer i = presentOpenSchCount; i < scheduleCount; i++){ 
                                            lstScheduleInsert.add(new SSIP_Schedule__c(Account__c = ssipIt.Account__c, Country__c = ssipIt.Country__c, Payment_Term__c = ssipIt.Payment_Term__c, Shipping_Address__c = ssipIt.Shipping_Address__c,
                                                                                       Shipping_Method__c = ssipIt.Shipping_Method__c, SSIP_Rule__c = ssipIt.Id, Status__c = 'Open',
                                                                                       Fund__c = !ruleToFundMap.isEmpty() ? ruleToFundMap.get(ssipIt.Id) : null,     
                                                                                       Schedule_Date__c = nexScheduleDate.addMonths(1 * i)));
                                        }
                                    }else if(dayofMonth > 28){
                                        //date myDate = ssipIt.First_Shipment_Date__c; 
                                        date newDate = nexScheduleDate.addMonths(1);
                                        date expectedDate = newDate.toStartOfMonth();
                                        for(Integer i = presentOpenSchCount; i < scheduleCount; i++){
                                            lstScheduleInsert.add(new SSIP_Schedule__c(Account__c = ssipIt.Account__c, Country__c = ssipIt.Country__c, Payment_Term__c = ssipIt.Payment_Term__c, Shipping_Address__c = ssipIt.Shipping_Address__c,
                                                                                       Shipping_Method__c = ssipIt.Shipping_Method__c, SSIP_Rule__c = ssipIt.Id, Status__c = 'Open',
                                                                                       Fund__c = !ruleToFundMap.isEmpty() ? ruleToFundMap.get(ssipIt.Id) : null,     
                                                                                       Schedule_Date__c = expectedDate.addMonths(1 * i)));
                                        }
                                    } 
                                    
                                }else{
                                    System.debug('**Non-Canada--');
                                    for(Integer i = presentOpenSchCount; i < scheduleCount; i++){
                                        lstScheduleInsert.add(new SSIP_Schedule__c(Account__c = ssipIt.Account__c, Country__c = ssipIt.Country__c, Payment_Term__c = ssipIt.Payment_Term__c, Shipping_Address__c = ssipIt.Shipping_Address__c,
                                                                                   Shipping_Method__c = ssipIt.Shipping_Method__c, SSIP_Rule__c = ssipIt.Id, Status__c = 'Open',
                                                                                   Fund__c = !ruleToFundMap.isEmpty() ? ruleToFundMap.get(ssipIt.Id) : null,     
                                                                                   Schedule_Date__c = nexScheduleDate.addDays(Integer.valueOf(ssipIt.Frequency_In_Days__c) * i)));
                                    }
                                }
                            }
                            
                        }
                        if(presentOpenSchCount == 0 ){
                            System.debug('**presentOpenSchCount---'+0);
                            
                            SSIP_Schedule__c scheduleObj = 	findNonOpenLastShippedDate(ssipIt);
                            Date latestScheduled = System.today();
                            Date todaysDate = System.today();
                            if(scheduleObj != null){                                
                                Integer daystoAdd = Integer.valueOf(ssipIt.Frequency_In_Days__c);                            
                                latestScheduled = scheduleObj.Schedule_Date__c;                                
                                //latestScheduled = latestScheduled.addDays(daystoAdd);
                            }else{
                                SSIP_Rule__c rule = (SSIP_Rule__c)trigger.newMap.get(ssipIt.id);
                                rule.addError('Can not add the new schedules as no valid previous schedules found, please create new Subscription'); return;
                                // latestScheduled = System.today().addDays(1);
                            }
                            /*
if(latestScheduled.format() == todaysDate.format()){
latestScheduled = latestScheduled.addDays(1);
}
*/
                            if(scheduleObj.Schedule_Date__c.addDays(Integer.valueOf(ssipIt.Frequency_In_Days__c)) < todaysDate.addDays(1)){
                                SSIP_Rule__c rule = (SSIP_Rule__c)trigger.newMap.get(ssipIt.id);
                                rule.addError('Can not add the new schedules, please create new Subscription'); return;
                            }else{
                                System.debug('**Else Part to inset 3 Open Schedules');
                                Integer dayofMonth = scheduleObj.Schedule_Date__c.Day();
                                System.debug('**dayofMonth--'+dayofMonth);
                                String Prdname = scheduleObj.Product_Name__c;
                                
                                if(ssipIt.Rule_End_Date__c == null || scheduleObj.Schedule_Date__c <= ssipIt.Rule_End_Date__c){
                                    if(ssipIt.Country__c == 'Canada' && prdName.startsWith('MT')){
                                        System.debug('**Canada--');
                                        if(dayofMonth <= 28){
                                            for(Integer i = 0;i<scheduleCount;i++){
                                                lstScheduleInsert.add(new SSIP_Schedule__c(Account__c = ssipIt.Account__c, Country__c = ssipIt.Country__c, Payment_Term__c = ssipIt.Payment_Term__c, Shipping_Address__c = ssipIt.Shipping_Address__c,
                                                                                           Shipping_Method__c = ssipIt.Shipping_Method__c, SSIP_Rule__c = ssipIt.Id, Status__c = 'Open',
                                                                                           Fund__c = !ruleToFundMap.isEmpty() ? ruleToFundMap.get(ssipIt.Id) : null,     
                                                                                           Schedule_Date__c = latestScheduled.addDays(Integer.valueOf(ssipIt.Frequency_In_Days__c) * (i+1) )));
                                            }
                                        } else if(dayofMonth > 28){
                                            //date myDate = ssipIt.First_Shipment_Date__c; 
                                            date newDate = latestScheduled.addMonths(1);
                                            date expectedDate = newDate.toStartOfMonth();
                                            for(Integer i = 0;i<scheduleCount;i++){
                                                lstScheduleInsert.add(new SSIP_Schedule__c(Account__c = ssipIt.Account__c, Country__c = ssipIt.Country__c, Payment_Term__c = ssipIt.Payment_Term__c, Shipping_Address__c = ssipIt.Shipping_Address__c,
                                                                                           Shipping_Method__c = ssipIt.Shipping_Method__c, SSIP_Rule__c = ssipIt.Id, Status__c = 'Open',
                                                                                           Fund__c = !ruleToFundMap.isEmpty() ? ruleToFundMap.get(ssipIt.Id) : null,     
                                                                                           Schedule_Date__c = expectedDate.addDays(Integer.valueOf(ssipIt.Frequency_In_Days__c) * (i+1) )));
                                            }
                                        }
                                    }else{
                                        System.debug('**Non-Canada--');
                                        for(Integer i = 0; i < scheduleCount; i++){
                                            lstScheduleInsert.add(new SSIP_Schedule__c(Account__c = ssipIt.Account__c, Country__c = ssipIt.Country__c, Payment_Term__c = ssipIt.Payment_Term__c, Shipping_Address__c = ssipIt.Shipping_Address__c,
                                                                                       Shipping_Method__c = ssipIt.Shipping_Method__c, SSIP_Rule__c = ssipIt.Id, Status__c = 'Open',
                                                                                       Fund__c = !ruleToFundMap.isEmpty() ? ruleToFundMap.get(ssipIt.Id) : null,     
                                                                                       Schedule_Date__c = latestScheduled.addDays(Integer.valueOf(ssipIt.Frequency_In_Days__c) * (i+1))));
                                        }
                                    }
                                }
                                
                                
                                
                            }
                        }// Main If Ends
                    }
                }// For Loop Ends
                
                if(lstScheduleInsert.size()>0){
                    System.debug('**--Size--'+lstScheduleInsert.size());
                    insert lstScheduleInsert;
                }
            }
        }catch(Exception ex){
            System.debug('ErrLine--'+ex.getLineNumber());
            System.debug('Err--'+ex);
        }        
    }
    
    public static SSIP_Schedule__c findLastShippedDate(List<SSIP_Schedule__c> lstScheIt){
        
        //List<Object> someList = new List<Object>{1,2,3,4,5};
        List<SSIP_Schedule__c> reversed = new List<SSIP_Schedule__c>();
        for(Integer i = lstScheIt.size() - 1; i >= 0; i--){
            reversed.add(lstScheIt[i]);
        }
        //System.debug('**Schedule--'+reversed[0]);
        return reversed[0];
    }
    
    public static SSIP_Schedule__c findNonOpenLastShippedDate(SSIP_Rule__c ssipRule){
        
        List<SSIP_Schedule__c> lstSSIPSchedule = [Select id,Schedule_Date__c,SSIP_Rule__c,SSIP_Rule__r.Id,status__c,Product_Name__c
                                                  from SSIP_Schedule__c 
                                                  where SSIP_Rule__c =:ssipRule.id order by Schedule_Date__c desc ];
        if(lstSSIPSchedule.size()>0){
            return lstSSIPSchedule[0];
        }
        return null;
    }
    
    public static List<SSIP_Schedule__c> checkOpenScheule(List<SSIP_Schedule__c> lstScheIt){
        List<SSIP_Schedule__c> lstOpenSchedule = new List<SSIP_Schedule__c>();
        if(lstScheIt.size()>0){           
            for(SSIP_Schedule__c sch : lstScheIt ){
                if(sch.Status__c == 'Open'){
                    lstOpenSchedule.add(sch);
                }	    
            }
        }
        return lstOpenSchedule;  
    }
    
    
}