Prod-EU/force-app/main/default/objects/Fund__c/Fund__c.object-meta.xml
<CustomObject>
    <description>Object will track information related to Funded Patients.</description>
    <label>Fund</label>
    <nameField>
        <displayFormat>F-{00000}</displayFormat>
        <label>Fund Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fund</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Prod-EU/force-app/main/default/objects/Fund__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <defaultValue>If(OR(BEGINS($Profile.Name , &apos;UK&apos;), BEGINS($Profile.Name , &apos;System&apos;)), &apos;United Kingdom&apos;, &apos;&apos;)</defaultValue>
    <description>Possible countries that can be selected defaulted based on the Profile</description>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country</valueSetName>
    </valueSet>
</CustomField>

Prod-EU/force-app/main/default/objects/SSIP_Rule__c/SSIP_Rule__c.object-meta.xml
<CustomObject>
    <description>Object stores all SSIP rule for the customers.</description>
    <label>SSIP Rule</label>
    <nameField>
        <displayFormat>SP-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SSIP Rule</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Prod-EU/force-app/main/default/objects/SSIP_Rule__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Master detail relationship to the account.</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>SSIP Rule</relationshipLabel>
    <relationshipName>SSIP_Rule</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Prod-EU/force-app/main/default/objects/SSIP_Rule__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <description>Country to which this rule is tied to</description>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country</valueSetName>
    </valueSet>
</CustomField>

Prod-EU/force-app/main/default/objects/SSIP_Rule__c/fields/Frequency_In_Days__c.field-meta.xml
<CustomField>
    <fullName>Frequency_In_Days__c</fullName>
    <description>Schedule interval between each shipments.</description>
    <label>Frequency (In Days)</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Prod-EU/force-app/main/default/objects/SSIP_Rule__c/fields/Payment_Term__c.field-meta.xml
<CustomField>
    <fullName>Payment_Term__c</fullName>
    <defaultValue>IF( $RecordType.DeveloperName = &apos;CH_SSIP_Rule&apos;, &apos;net30&apos;, &apos;net30&apos;)</defaultValue>
    <description>Payment terms that will be used to track the payment. The default value will be based on the country&apos; preference</description>
    <label>Payment Term</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Payment_Term</valueSetName>
    </valueSet>
</CustomField>

Prod-EU/force-app/main/default/objects/SSIP_Rule__c/fields/Product_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Product Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Prod-EU/force-app/main/default/objects/SSIP_Rule__c/fields/Rule_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Rule_End_Date__c</fullName>
    <description>Date when the rule will end.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Date should be greater than or equal to today&apos;s date. Setting this date will delete any open schedules past this date.</inlineHelpText>
    <label>Rule End Date</label>
    <type>Date</type>
</CustomField>

Prod-EU/force-app/main/default/objects/SSIP_Rule__c/fields/Shipping_Address__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Address__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>List of all Ship To addresses tied to the customer.</description>
    <label>Shipping Address</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Address__c.Account__c</field>
            <operation>equals</operation>
            <valueField>$Source.Account__c</valueField>
        </filterItems>
        <filterItems>
            <field>Address__c.Type__c</field>
            <operation>equals</operation>
            <value>Ship To</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Address__c</referenceTo>
    <relationshipLabel>SSIP Rule</relationshipLabel>
    <relationshipName>SSIP_Rule</relationshipName>
    <type>Lookup</type>
</CustomField>

Prod-EU/force-app/main/default/objects/SSIP_Rule__c/fields/Shipping_Method__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Method__c</fullName>
    <description>Shipping method will be constrained by Country</description>
    <inlineHelpText>Chosen value will be defaulted to all the schedules associated to this Rule.</inlineHelpText>
    <label>Shipping Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Shipping_Method</valueSetName>
    </valueSet>
</CustomField>

Prod-EU/force-app/main/default/objects/SSIP_Rule__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&apos;Active&apos;</defaultValue>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Prod-EU/force-app/main/default/objects/SSIP_Schedule__c/SSIP_Schedule__c.object-meta.xml
<CustomObject>
    <description>Object stores all the schedules related to the rule.</description>
    <label>SSIP Schedule</label>
    <nameField>
        <displayFormat>SP-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SSIP Schedule</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Prod-EU/force-app/main/default/objects/SSIP_Schedule__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Will be referencing the grand parent and will be defaulted at the time of the Schedule creation. Need this for constraining the addressed tied to the customer.</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>SSIP Schedule</relationshipLabel>
    <relationshipName>SSIP_Schedule</relationshipName>
    <type>Lookup</type>
</CustomField>

Prod-EU/force-app/main/default/objects/SSIP_Schedule__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <description>Will be defaulted from SSIP Rule at the time of creation.</description>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country</valueSetName>
    </valueSet>
</CustomField>

Prod-EU/force-app/main/default/objects/SSIP_Schedule__c/fields/Fund__c.field-meta.xml
<CustomField>
    <fullName>Fund__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Fund</label>
    <referenceTo>Fund__c</referenceTo>
    <relationshipLabel>SSIP Schedule</relationshipLabel>
    <relationshipName>SSIP_Schedule</relationshipName>
    <type>Lookup</type>
</CustomField>

Prod-EU/force-app/main/default/objects/SSIP_Schedule__c/fields/Payment_Term__c.field-meta.xml
<CustomField>
    <fullName>Payment_Term__c</fullName>
    <description>Will be defaulted from Parent SSIP Rule</description>
    <inlineHelpText>Value can be overridden only for this schedule.</inlineHelpText>
    <label>Payment Term</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Payment_Term</valueSetName>
    </valueSet>
</CustomField>

Prod-EU/force-app/main/default/objects/SSIP_Schedule__c/fields/Product_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Name__c</fullName>
    <formula>SSIP_Rule__r.Product__r.Name</formula>
    <inlineHelpText>Product Name tied to the Rule.</inlineHelpText>
    <label>Product Name</label>
    <type>Text</type>
</CustomField>

Prod-EU/force-app/main/default/objects/SSIP_Schedule__c/fields/Schedule_Date__c.field-meta.xml
<CustomField>
    <fullName>Schedule_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Date when the Order will be shipped.</inlineHelpText>
    <label>Schedule Date</label>
    <type>Date</type>
</CustomField>

Prod-EU/force-app/main/default/objects/SSIP_Schedule__c/fields/Shipping_Address__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Address__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>List of all Ship To addresses tied to the customer.</description>
    <inlineHelpText>This address will be used as Shipping address for the Order. If this field is not filled in then default Primary Shipping address tied to the account will be chosen.</inlineHelpText>
    <label>Changed Shipping Address</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Address__c.Account__c</field>
            <operation>equals</operation>
            <valueField>$Source.Account__c</valueField>
        </filterItems>
        <filterItems>
            <field>Address__c.Type__c</field>
            <operation>equals</operation>
            <value>Ship To</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Address__c</referenceTo>
    <relationshipLabel>SSIP Schedule</relationshipLabel>
    <relationshipName>SSIP_Schedule</relationshipName>
    <type>Lookup</type>
</CustomField>

Prod-EU/force-app/main/default/objects/SSIP_Schedule__c/fields/Shipping_Method__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Method__c</fullName>
    <description>Shipping Method will be defaulted based on the country default value.</description>
    <inlineHelpText>Value can be overridden only for this schedule. 
Make sure all other product schedules that will be shipped out on the same day for this account is also chosen the corresponding Shipping method.</inlineHelpText>
    <label>Shipping Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Shipping_Method</valueSetName>
    </valueSet>
</CustomField>

Prod-EU/force-app/main/default/objects/SSIP_Schedule__c/fields/SSIP_Rule__c.field-meta.xml
<CustomField>
    <fullName>SSIP_Rule__c</fullName>
    <description>Master Detail relationship to the parent Rule.</description>
    <label>SSIP Rule</label>
    <referenceTo>SSIP_Rule__c</referenceTo>
    <relationshipLabel>SSIP Schedule</relationshipLabel>
    <relationshipName>SSIP_Schedule</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Prod-EU/force-app/main/default/objects/SSIP_Schedule__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&apos;Open&apos;</defaultValue>
    <description>Will be defaulted to Open. Depending on the Order processing other values will be set.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>In Error</fullName>
            </value>
            <value>
                <fullName>In Draft</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Prod-EU/force-app/main/default/classes/SSIPScheduleTriggerHandler.cls
public class SSIPScheduleTriggerHandler {
    
    public Map<Id, SSIP_Rule__c> mapRule = new Map<Id, SSIP_Rule__c>();
    public void onAfterUpdate(List<SSIP_Schedule__c> lstSSIPScheduleNew, Map<Id, SSIP_Schedule__c> mapScheduleOld){
        List<SSIP_Schedule__c> lstSSIPSchedule = new List<SSIP_Schedule__c>();
        List<SSIP_Schedule__c> lstSSIPScheduleFilter = new List<SSIP_Schedule__c>();
        List<SSIP_Schedule__c> lstCASSIPScheduleFilter = new List<SSIP_Schedule__c>();
        Set<Id> setSSIPRuleIds = new Set<Id>();
        for(SSIP_Schedule__c ssipRule : lstSSIPScheduleNew){
            
            String prdName = ssipRule.Product_Name__c;
            
            if( (ssipRule.Status__c == 'In Progress' || ssipRule.Status__c == 'In Draft') && ssipRule.Status__c != mapScheduleOld.get(ssipRule.Id).Status__c && ssipRule.Country__c != 'Canada' && !prdName.startsWith('MT')){
                setSSIPRuleIds.add(ssipRule.SSIP_Rule__c);
                lstSSIPScheduleFilter.add(ssipRule);
            }
            
            if(ssipRule.Country__c == 'Canada' && prdName.startsWith('MT') && (ssipRule.Status__c == 'In Progress' || ssipRule.Status__c == 'In Draft') && ssipRule.Status__c != mapScheduleOld.get(ssipRule.Id).Status__c ){
                lstCASSIPScheduleFilter.add(ssipRule);
                
            }
        }
        mapRule = new Map<Id, SSIP_Rule__c>([SELECT Id, Rule_End_Date__c, Frequency_In_Days__c, Payment_Term__c, Shipping_Address__c, Shipping_Method__c, (SELECT Id, Schedule_Date__c FROM SSIP_Schedule__r ORDER BY Schedule_Date__c DESC LIMIT 1) FROM SSIP_Rule__c WHERE Id IN: setSSIPRuleIds]);
        for(SSIP_Schedule__c ssipSchedule : lstSSIPScheduleFilter){
            if(mapRule.containsKey(ssipSchedule.SSIP_Rule__c) && mapRule.get(ssipSchedule.SSIP_Rule__c).Frequency_In_Days__c != null){
                SSIP_Rule__c rule = mapRule.get(ssipSchedule.SSIP_Rule__c);
                Date scheduleDate = rule.SSIP_Schedule__r.size() > 0 ? rule.SSIP_Schedule__r[0].Schedule_Date__c.addDays(Integer.valueOf(rule.Frequency_In_Days__c)) : Date.today().addDays(Integer.valueOf(rule.Frequency_In_Days__c));
                if(rule.Rule_End_Date__c == null || scheduleDate <= rule.Rule_End_Date__c){
                    lstSSIPSchedule.add(new SSIP_Schedule__c(Account__c = ssipSchedule.Account__c, Country__c = ssipSchedule.Country__c, Payment_Term__c = rule.Payment_Term__c,
                                                             Shipping_Address__c = rule.Shipping_Address__c, Shipping_Method__c = rule.Shipping_Method__c, 
                                                             SSIP_Rule__c = ssipSchedule.SSIP_Rule__c, Status__c = 'Open', Fund__c = ssipSchedule.Fund__c, Schedule_Date__c = scheduleDate));
                }
            }
        }
        if(lstSSIPSchedule.size()>0){
            insert lstSSIPSchedule; 
        }
        if(lstCASSIPScheduleFilter.size()>0){
            scheduleCanadaRules(lstCASSIPScheduleFilter);
        }
        
    }
    
    public void scheduleCanadaRules(List<SSIP_Schedule__c> lstCASSIPScheduleFilter){
        System.debug('scheduleCanadaRules--');
        List<SSIP_Schedule__c> lstSSIPSchedule = new List<SSIP_Schedule__c>();
        Set<Id> setSSIPRuleIds = new Set<Id>();
        for(SSIP_Schedule__c ssipRule : lstCASSIPScheduleFilter) setSSIPRuleIds.add(ssipRule.SSIP_Rule__c);
        mapRule = new Map<Id, SSIP_Rule__c>([SELECT Id, Rule_End_Date__c, Frequency_In_Days__c, Payment_Term__c, Shipping_Address__c, Shipping_Method__c, (SELECT Id, Schedule_Date__c FROM SSIP_Schedule__r ORDER BY Schedule_Date__c DESC LIMIT 1) FROM SSIP_Rule__c WHERE Id IN: setSSIPRuleIds]);
        for(SSIP_Schedule__c ssipSchedule : lstCASSIPScheduleFilter){
            if(mapRule.containsKey(ssipSchedule.SSIP_Rule__c)){
                
                SSIP_Rule__c rule = mapRule.get(ssipSchedule.SSIP_Rule__c);
                Date scheduleDate = rule.SSIP_Schedule__r.size() > 0 ? rule.SSIP_Schedule__r[0].Schedule_Date__c.addMonths(1) : Date.today().addMonths(1);
                Integer dayofMonth = scheduleDate.day();
                System.debug('rule.Rule_End_Date__c--'+rule.Rule_End_Date__c);
                System.debug('scheduleDate--'+scheduleDate);
                if(rule.Rule_End_Date__c == null || scheduleDate <= rule.Rule_End_Date__c){
                    if(dayofMonth <= 28){
                        lstSSIPSchedule.add(new SSIP_Schedule__c(Account__c = ssipSchedule.Account__c, Country__c = ssipSchedule.Country__c, Payment_Term__c = rule.Payment_Term__c,
                                                                 Shipping_Address__c = rule.Shipping_Address__c, Shipping_Method__c = rule.Shipping_Method__c, 
                                                                 SSIP_Rule__c = ssipSchedule.SSIP_Rule__c, Status__c = 'Open', Fund__c = ssipSchedule.Fund__c, Schedule_Date__c = scheduleDate));
                        
                    }else if(dayofMonth > 28){
                        date myDate = scheduleDate;
                        date newDate = myDate.addMonths(1);
                        date expectedDate = newDate.toStartOfMonth();
                        lstSSIPSchedule.add(new SSIP_Schedule__c(Account__c = ssipSchedule.Account__c, Country__c = ssipSchedule.Country__c, Payment_Term__c = rule.Payment_Term__c,
                                                                 Shipping_Address__c = rule.Shipping_Address__c, Shipping_Method__c = rule.Shipping_Method__c, 
                                                                 SSIP_Rule__c = ssipSchedule.SSIP_Rule__c, Status__c = 'Open', Fund__c = ssipSchedule.Fund__c,
                                                                 Schedule_Date__c = expectedDate));
                        
                    }
                }
            }
        }
        if(lstSSIPSchedule.size()>0){
            insert lstSSIPSchedule; 
        }
        
    }
}