Prod-EU/force-app/main/default/objects/Patient_Document__c/Patient_Document__c.object-meta.xml
<CustomObject>
    <label>Patient Document</label>
    <nameField>
        <displayFormat>PDOC-{00000}</displayFormat>
        <label>PDOC</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Patient Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Prod-EU/force-app/main/default/objects/Patient_Document__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Patient Documents</relationshipLabel>
    <relationshipName>Patient_Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

Prod-EU/force-app/main/default/objects/Patient_Document__c/fields/Collect_From__c.field-meta.xml
<CustomField>
    <fullName>Collect_From__c</fullName>
    <label>Collect From</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Online Form</fullName>
            </value>
            <value>
                <fullName>Patient</fullName>
            </value>
            <value>
                <fullName>Physician</fullName>
            </value>
            <value>
                <fullName>Caseworker</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Prod-EU/force-app/main/default/objects/Patient_Document__c/fields/Doc_Type__c.field-meta.xml
<CustomField>
    <fullName>Doc_Type__c</fullName>
    <label>Doc Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>PIAF</fullName>
            </value>
            <value>
                <fullName>CMN</fullName>
            </value>
            <value>
                <fullName>T1D Note</fullName>
            </value>
            <value>
                <fullName>Claim Form</fullName>
            </value>
            <value>
                <fullName>A1c</fullName>
            </value>
            <value>
                <fullName>BG Logs</fullName>
            </value>
            <value>
                <fullName>CGM Quest</fullName>
            </value>
            <value>
                <fullName>LIC</fullName>
            </value>
            <value>
                <fullName>Pregnancy Rx</fullName>
            </value>
            <value>
                <fullName>Narrative Letter</fullName>
            </value>
            <value>
                <fullName>ODSP Info Form</fullName>
            </value>
            <value>
                <fullName>NIHB Claim Form</fullName>
            </value>
            <value>
                <fullName>NIHB Estimate</fullName>
            </value>
            <value>
                <fullName>Prior-Auth Form</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Prod-EU/force-app/main/default/objects/Patient_Document__c/fields/PDoc_To_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>PDoc_To_Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>PDoc To Opportunity</label>
    <referenceTo>PDoc_To_Opportunity__c</referenceTo>
    <relationshipLabel>Patient Documents</relationshipLabel>
    <relationshipName>Patient_Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

Prod-EU/force-app/main/default/objects/Patient_Document__c/fields/Sent_Date__c.field-meta.xml
<CustomField>
    <fullName>Sent_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Sent Date</label>
    <type>Date</type>
</CustomField>

Prod-EU/force-app/main/default/objects/Patient_Document__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sent</fullName>
            </value>
            <value>
                <fullName>Not Sent</fullName>
            </value>
            <value>
                <fullName>Received</fullName>
            </value>
            <value>
                <fullName>Not Required</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Prod-EU/force-app/main/default/objects/PDoc_To_Opportunity__c/PDoc_To_Opportunity__c.object-meta.xml
<CustomObject>
    <label>PDoc To Opportunity</label>
    <nameField>
        <displayFormat>PDOPP-{0000}</displayFormat>
        <label>PDOPP</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PDoc To Opportunity</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Prod-EU/force-app/main/default/objects/PDoc_To_Opportunity__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>PDoc To Opportunity</relationshipLabel>
    <relationshipName>PDoc_To_Opportunity</relationshipName>
    <type>Lookup</type>
</CustomField>

Prod-EU/force-app/main/default/objects/PDoc_To_Opportunity__c/fields/Patient_Document__c.field-meta.xml
<CustomField>
    <fullName>Patient_Document__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Patient Document</label>
    <referenceTo>Patient_Document__c</referenceTo>
    <relationshipLabel>PDoc To Opportunity</relationshipLabel>
    <relationshipName>PDoc_To_Opportunity</relationshipName>
    <type>Lookup</type>
</CustomField>

Prod-EU/force-app/main/default/classes/ClsPdocHandler.cls
public class ClsPdocHandler {
    
    public static Boolean runOnce = true;    
    public static void afterPdocOpportunityInsert(List<PDoc_To_Opportunity__c> lstPdocOpportunity){
        System.debug('***Inside Handler***'+lstPdocOpportunity.size());
        if(ClsPdocHandler.runOnce){
            ClsPdocHandler.runOnce = false;
            boolean runTrigger = false;
            Set<Id> setPatientDoc = new Set<Id>();
            Set<Id> setOpportunity = new Set<Id>();
            Set<Id> setOpptToProcess = new Set<Id>();
            for(PDoc_To_Opportunity__c pdocOpprtunity :  lstPdocOpportunity){
                setPatientDoc.add(pdocOpprtunity.Patient_Document__c);
                setOpportunity.add(pdocOpprtunity.Opportunity__c);
            }
            
            //Check Opportunity StageName -- if stagename is New Opportunity then update the opportunity
            if(setOpportunity.size()>0){             
                for(Opportunity opp : [Select id,StageName from opportunity where id IN:setOpportunity]){
                    if(opp.StageName == 'New Opportunity' || opp.StageName == 'Customer Doc Collection' ){
                        setOpptToProcess.add(opp.Id);
                    }
                }
            }
            
            System.debug('***setPatientDoc***'+setPatientDoc);
            List<Patient_Document__c> lstPatientInfo = new List<Patient_Document__c>();
            lstPatientInfo = [SELECT Id, Doc_Type__c,Account__c, Status__c, Collect_From__c, Sent_Date__c, Received_Date__c 
                              FROM Patient_Document__c
                              where Id IN:setPatientDoc];
            
            Set<Id> setPayor = new Set<Id>();
            System.debug('**lstPatientInfo**'+lstPatientInfo.size());
            Map<String,List<Patient_Document__c>> mapPdocInfo = new Map<String,List<Patient_Document__c>>();
            for(Patient_Document__c pdc : lstPatientInfo){
                String strKey = pdc.id+'-'+pdc.Account__c;
                if(mapPdocInfo.Containskey(strKey)){
                    List<Patient_Document__c> lst = mapPdocInfo.get(strKey);
                    lst.add(pdc);
                    mapPdocInfo.put(strKey,lst);
                }else{
                    List<Patient_Document__c> newLst = new List<Patient_Document__c>();
                    newLst.add(pdc);
                    mapPdocInfo.put(strKey,newLst);
                }
            }
            System.debug('**mapPdocInfo**'+mapPdocInfo.values());
            Map<String,PDoc_To_Opportunity__c> mapPDocOp = new Map<String,PDoc_To_Opportunity__c>();
            Map<String,Opportunity> mapOpportunityUpdate = new Map<String,Opportunity>();
            //Map<String,Opportunity> mapOpportunityUpdateV2 = new Map<String,Opportunity>();
            Map<String,String> mapUpdateOpp = new Map<String,String>();
            Set<Id> setOppId = new Set<Id>();
            Integer statusnullCounter = 0;
            //Integer statusnotnullCounter = 0;
            List<Opportunity> lstupdateOp = new List<Opportunity>();
            List<PDoc_To_Opportunity__c> lstPdcOp = [Select id,Patient_Document__c,Patient_Document__r.Account__r.Id,Opportunity__c from PDoc_To_Opportunity__c 
                                                     where Patient_Document__c IN:setPatientDoc and Opportunity__c IN:setOpptToProcess];
            System.debug('**lstPdcOp--'+lstPdcOp.size());
            if(lstPdcOp.size()>0){
                Map<String,Integer> mapStatus = new Map<String,Integer>();
                mapStatus.put('Not Required',0);
                mapStatus.put('Received',1);
                mapStatus.put('Sent',2);
                mapStatus.put('Not Sent',3);
                
                Map<String,Integer> mapCollectfrm = new Map<String,Integer>();
                mapCollectfrm.put(null,-1);
                mapCollectfrm.put('Physician',0);
                mapCollectfrm.put('Patient',1);
                mapCollectfrm.put('Caseworker',2);
                mapCollectfrm.put('Online Form',3);
                Opportunity opp = new Opportunity();
                opp.CA_Customer_Docs_Collection_Status__c = 'Not Required';
                opp.CA_Prescriber_Docs_Collection_Status__c = 'Not Required';
                Boolean pendingflag = false;
                for(PDoc_To_Opportunity__c pdOp :  lstPdcOp){ 
                    String pdocKey = pdOp.Patient_Document__c+'-'+pdOp.Patient_Document__r.Account__r.Id;
                    System.debug('**--pdocKey--'+pdocKey);
                    if(mapPdocInfo.containsKey(pdocKey)){
                        for(Patient_Document__c pdc :mapPdocInfo.get(pdocKey)){
                            System.debug('**pdc--'+pdc);
                            if(mapStatus.containskey(pdc.Status__c)){
                                Integer key = mapStatus.get(pdc.Status__c);
                                Integer cfKey = mapCollectfrm.get(pdc.Collect_from__c);
                                System.debug('**--collectFrom'+mapCollectfrm.get(pdc.Collect_from__c));
                                opp.Id = pdOp.Opportunity__c;
                                system.debug('**key--'+key+'--cfKey--'+cfKey);
                                if(key == 1 && cfKey >= 1 && pendingflag == false ){
                                    opp.CA_Customer_Docs_Collection_Status__c = 'All Docs Received';
                                  //system.debug('**1 If');
                                }else if((key == 2 && cfKey >= 1) || (key==3 && cfKey >= 1)){
                                    opp.CA_Customer_Docs_Collection_Status__c = 'Pending';
                                    pendingflag = true;                                    
                                }else if(key == 1 && cfKey == 0 ){
                                    opp.CA_Prescriber_Docs_Collection_Status__c = 'Docs Received';
                                    
                                }else if(key == 2 && cfKey == 0 ){
                                    opp.CA_Prescriber_Docs_Collection_Status__c = 'Pending';
                                   //system.debug('**4 If');
                                }else if((key == 2 && cfKey == -1) || (key==3 && cfKey == -1)){
                                    opp.CA_Customer_Docs_Collection_Status__c = 'Pending';
                                    pendingflag = true;
                                }
                            }     
                        }
                    }
                }
               update opp;
            }
        }
    }
}